In [1]:
import pickle
import numpy as np

In [2]:
with open('eu_firms_by_employed_number.xp', 'rb') as f:
            eu_firms_by_employed_number = pickle.load(f)

In [3]:
# from sbs_countries.ipynb

#eu_firms_by_employed_number[0].loc[4].sum(axis=1)
eu_firms_by_employed_number

[                                                        Austria   Belgium  \
 ID IND_USE (Labels)
 0  Total                                               0.000000  0.000000
 1  Products of agriculture, hunting and related se...  0.000000  0.000000
 2  Products of forestry, logging and related services  0.000000  0.000000
 3  Fish and other fishing products; aquaculture pr...  0.000000  0.000000
 4  Mining and quarrying                                0.017681  0.010671
 ...                                                         ...       ...
 61 Services furnished by membership organisations      0.000000  0.000000
 62 Repair services of computers and personal and h...  0.009581  0.017827
 63 Other personal services                             0.025514  0.019894
 64 Services of households as employers; undifferen...  0.000000  0.000000
 65 Services provided by extraterritorial organisat...  0.000000  0.000000

                                                        Bulgaria   Croatia  \
 ID IND_USE (Labels)
 0  Total                                               0.000000  0.000000
 1  Products of agriculture, hunting and related se...  0.000000  0.000000
 2  Products of forestry, logging and related services  0.000000  0.000000
 3  Fish and other fishing products; aquaculture pr...  0.000000  0.000000
 4  Mining and quarrying                                0.013864  0.010904
 ...                                                         ...       ...
 61 Services furnished by membership organisations      0.000000  0.000000
 62 Repair services of computers and personal and h...  0.015706  0.011174
 63 Other personal services                             0.014331  0.008391
 64 Services of households as employers; undifferen...  0.000000  0.000000
 65 Services provided by extraterritorial organisat...  0.000000  0.000000

                                                          Cyprus   Czechia  \
 ID IND_USE (Labels)
 0  Total                                               0.000000  0.000000
 1  Products of agriculture, hunting and related se...  0.000000  0.000000
 2  Products of forestry, logging and related services  0.000000  0.000000
 3  Fish and other fishing products; aquaculture pr...  0.000000  0.000000
 4  Mining and quarrying                                0.000000  0.029052
 ...                                                         ...       ...
 61 Services furnished by membership organisations      0.000000  0.000000
 62 Repair services of computers and personal and h...  0.002219  0.043398
 63 Other personal services                             0.003669  0.038231
 64 Services of households as employers; undifferen...  0.000000  0.000000
 65 Services provided by extraterritorial organisat...  0.000000  0.000000

                                                         Denmark   Estonia  \
 ID IND_USE (Labels)
 0  Total                                               0.000000  0.000000
 1  Products of agriculture, hunting and related se...  0.000000  0.000000
 2  Products of forestry, logging and related services  0.000000  0.000000
 3  Fish and other fishing products; aquaculture pr...  0.000000  0.000000
 4  Mining and quarrying                                0.013708  0.009502
 ...                                                         ...       ...
 61 Services furnished by membership organisations      0.000000  0.000000
 62 Repair services of computers and personal and h...  0.006472  0.002550
 63 Other personal services                             0.007493  0.004563
 64 Services of households as employers; undifferen...  0.000000  0.000000
 65 Services provided by extraterritorial organisat...  0.000000  0.000000

                                                         Finland    France  \
 ID IND_USE (Labels)
 0  Total                                               0.000000  0.000000
 1  Products of agriculture, hunting and related se...  0.000000  0.000000
 2  Products of forestry, logging and related services  0.000000  0.000000
 3  Fish and other fishing products; aquaculture pr...  0.000000  0.000000
 4  Mining and quarrying                                0.073526  0.058494
 ...                                                         ...       ...
 61 Services furnished by membership organisations      0.000000  0.000000
 62 Repair services of computers and personal and h...  0.000000  0.196654
 63 Other personal services                             0.018361  0.181595
 64 Services of households as employers; undifferen...  0.000000  0.000000
 65 Services provided by extraterritorial organisat...  0.000000  0.000000

                                                        ...  Luxembourg  \
 ID IND_USE (Labels)                                    ...
 0  Total                                               ...    0.000000
 1  Products of agriculture, hunting and related se...  ...    0.000000
 2  Products of forestry, logging and related services  ...    0.000000
 3  Fish and other fishing products; aquaculture pr...  ...    0.000000
 4  Mining and quarrying                                ...    0.000234
 ...                                                    ...         ...
 61 Services furnished by membership organisations      ...    0.000000
 62 Repair services of computers and personal and h...  ...    0.000647
 63 Other personal services                             ...    0.001009
 64 Services of households as employers; undifferen...  ...    0.000000
 65 Services provided by extraterritorial organisat...  ...    0.000000

                                                           Malta  Netherlands  \
 ID IND_USE (Labels)
 0  Total                                               0.000000     0.000000
 1  Products of agriculture, hunting and related se...  0.000000     0.000000
 2  Products of forestry, logging and related services  0.000000     0.000000
 3  Fish and other fishing products; aquaculture pr...  0.000000     0.000000
 4  Mining and quarrying                                0.004128     0.045253
 ...                                                         ...          ...
 61 Services furnished by membership organisations      0.000000     0.000000
 62 Repair services of computers and personal and h...  0.002959     0.053289
 63 Other personal services                             0.001859     0.065756
 64 Services of households as employers; undifferen...  0.000000     0.000000
 65 Services provided by extraterritorial organisat...  0.000000     0.000000

                                                          Poland  Portugal  \
 ID IND_USE (Labels)
 0  Total                                               0.000000  0.000000
 1  Products of agriculture, hunting and related se...  0.000000  0.000000
 2  Products of forestry, logging and related services  0.000000  0.000000
 3  Fish and other fishing products; aquaculture pr...  0.000000  0.000000
 4  Mining and quarrying                                0.155464  0.062310
 ...                                                         ...       ...
 61 Services furnished by membership organisations      0.000000  0.000000
 62 Repair services of computers and personal and h...  0.090671  0.023828
 63 Other personal services                             0.072157  0.041665
 64 Services of households as employers; undifferen...  0.000000  0.000000
 65 Services provided by extraterritorial organisat...  0.000000  0.000000

                                                         Romania  Slovakia  \
 ID IND_USE (Labels)
 0  Total                                               0.000000  0.000000
 1  Products of agriculture, hunting and related se...  0.000000  0.000000
 2  Products of forestry, logging and related services  0.000000  0.000000
 3  Fish and other fishing products; aquaculture pr...  0.000000  0.000000
 4  Mining and quarrying                                0.064725  0.017758
 ...                                                         ...       ...
 61 Services furnished by membership organisations      0.000000  0.000000
 62 Repair services of computers and personal and h...  0.039885  0.015514
 63 Other personal services                             0.028602  0.013204
 64 Services of households as employers; undifferen...  0.000000  0.000000
 65 Services provided by extraterritorial organisat...  0.000000  0.000000

                                                        Slovenia     Spain  \
 ID IND_USE (Labels)
 0  Total                                               0.000000  0.000000
 1  Products of agriculture, hunting and related se...  0.000000  0.000000
 2  Products of forestry, logging and related services  0.000000  0.000000
 3  Fish and other fishing products; aquaculture pr...  0.000000  0.000000
 4  Mining and quarrying                                0.004907  0.092297
 ...                                                         ...       ...
 61 Services furnished by membership organisations      0.000000  0.000000
 62 Repair services of computers and personal and h...  0.006668  0.156143
 63 Other personal services                             0.005165  0.103214
 64 Services of households as employers; undifferen...  0.000000  0.000000
 65 Services provided by extraterritorial organisat...  0.000000  0.000000

                                                          Sweden
 ID IND_USE (Labels)
 0  Total                                               0.000000
 1  Products of agriculture, hunting and related se...  0.000000
 2  Products of forestry, logging and related services  0.000000
 3  Fish and other fishing products; aquaculture pr...  0.000000
 4  Mining and quarrying                                0.041280
 ...                                                         ...
 61 Services furnished by membership organisations      0.000000
 62 Repair services of computers and personal and h...  0.018396
 63 Other personal services                             0.028715
 64 Services of households as employers; undifferen...  0.000000
 65 Services provided by extraterritorial organisat...  0.000000

 [66 rows x 27 columns],
                                                         Austria   Belgium  \
 ID IND_USE (Labels)
 0  Total                                               0.000000  0.000000
 1  Products of agriculture, hunting and related se...  0.000000  0.000000
 2  Products of forestry, logging and related services  0.000000  0.000000
 3  Fish and other fishing products; aquaculture pr...  0.000000  0.000000
 4  Mining and quarrying                                0.027066  0.000000
 ...                                                         ...       ...
 61 Services furnished by membership organisations      0.000000  0.000000
 62 Repair services of computers and personal and h...  0.017953  0.000000
 63 Other personal services                             0.026935  0.011368
 64 Services of households as employers; undifferen...  0.000000  0.000000
 65 Services provided by extraterritorial organisat...  0.000000  0.000000

                                                        Bulgaria   Croatia  \
 ID IND_USE (Labels)
 0  Total                                               0.000000  0.000000
 1  Products of agriculture, hunting and related se...  0.000000  0.000000
 2  Products of forestry, logging and related services  0.000000  0.000000
 3  Fish and other fishing products; aquaculture pr...  0.000000  0.000000
 4  Mining and quarrying                                0.006410  0.017094
 ...                                                         ...       ...
 61 Services furnished by membership organisations      0.000000  0.000000
 62 Repair services of computers and personal and h...  0.011370  0.016158
 63 Other personal services                             0.010916  0.004974
 64 Services of households as employers; undifferen...  0.000000  0.000000
 65 Services provided by extraterritorial organisat...  0.000000  0.000000

                                                          Cyprus   Czechia  \
 ID IND_USE (Labels)
 0  Total                                               0.000000  0.000000
 1  Products of agriculture, hunting and related se...  0.000000  0.000000
 2  Products of forestry, logging and related services  0.000000  0.000000
 3  Fish and other fishing products; aquaculture pr...  0.000000  0.000000
 4  Mining and quarrying                                0.000000  0.026353
 ...                                                         ...       ...
 61 Services furnished by membership organisations      0.000000  0.000000
 62 Repair services of computers and personal and h...  0.000000  0.024536
 63 Other personal services                             0.001873  0.010335
 64 Services of households as employers; undifferen...  0.000000  0.000000
 65 Services provided by extraterritorial organisat...  0.000000  0.000000

                                                         Denmark   Estonia  \
 ID IND_USE (Labels)
 0  Total                                               0.000000  0.000000
 1  Products of agriculture, hunting and related se...  0.000000  0.000000
 2  Products of forestry, logging and related services  0.000000  0.000000
 3  Fish and other fishing products; aquaculture pr...  0.000000  0.000000
 4  Mining and quarrying                                0.011396  0.010684
 ...                                                         ...       ...
 61 Services furnished by membership organisations      0.000000  0.000000
 62 Repair services of computers and personal and h...  0.028725  0.001795
 63 Other personal services                             0.009430  0.003165
 64 Services of households as employers; undifferen...  0.000000  0.000000
 65 Services provided by extraterritorial organisat...  0.000000  0.000000

                                                         Finland    France  \
 ID IND_USE (Labels)
 0  Total                                               0.000000  0.000000
 1  Products of agriculture, hunting and related se...  0.000000  0.000000
 2  Products of forestry, logging and related services  0.000000  0.000000
 3  Fish and other fishing products; aquaculture pr...  0.000000  0.000000
 4  Mining and quarrying                                0.023504  0.053419
 ...                                                         ...       ...
 61 Services furnished by membership organisations      0.000000  0.000000
 62 Repair services of computers and personal and h...  0.012567  0.111909
 63 Other personal services                             0.004651  0.095272
 64 Services of households as employers; undifferen...  0.000000  0.000000
 65 Services provided by extraterritorial organisat...  0.000000  0.000000

                                                        ...  Luxembourg  \
 ID IND_USE (Labels)                                    ...
 0  Total                                               ...    0.000000
 1  Products of agriculture, hunting and related se...  ...    0.000000
 2  Products of forestry, logging and related services  ...    0.000000
 3  Fish and other fishing products; aquaculture pr...  ...    0.000000
 4  Mining and quarrying                                ...    0.000712
 ...                                                    ...         ...
 61 Services furnished by membership organisations      ...    0.000000
 62 Repair services of computers and personal and h...  ...    0.001197
 63 Other personal services                             ...    0.002777
 64 Services of households as employers; undifferen...  ...    0.000000
 65 Services provided by extraterritorial organisat...  ...    0.000000

                                                           Malta  Netherlands  \
 ID IND_USE (Labels)
 0  Total                                               0.000000     0.000000
 1  Products of agriculture, hunting and related se...  0.000000     0.000000
 2  Products of forestry, logging and related services  0.000000     0.000000
 3  Fish and other fishing products; aquaculture pr...  0.000000     0.000000
 4  Mining and quarrying                                0.002849     0.009259
 ...                                                         ...          ...
 61 Services furnished by membership organisations      0.000000     0.000000
 62 Repair services of computers and personal and h...  0.000000     0.028725
 63 Other personal services                             0.000775     0.022736
 64 Services of households as employers; undifferen...  0.000000     0.000000
 65 Services provided by extraterritorial organisat...  0.000000     0.000000

                                                          Poland  Portugal  \
 ID IND_USE (Labels)
 0  Total                                               0.000000  0.000000
 1  Products of agriculture, hunting and related se...  0.000000  0.000000
 2  Products of forestry, logging and related services  0.000000  0.000000
 3  Fish and other fishing products; aquaculture pr...  0.000000  0.000000
 4  Mining and quarrying                                0.136752  0.078348
 ...                                                         ...       ...
 61 Services furnished by membership organisations      0.000000  0.000000
 62 Repair services of computers and personal and h...  0.057451  0.025135
 63 Other personal services                             0.030810  0.011303
 64 Services of households as employers; undifferen...  0.000000  0.000000
 65 Services provided by extraterritorial organisat...  0.000000  0.000000

                                                         Romania  Slovakia  \
 ID IND_USE (Labels)
 0  Total                                               0.000000  0.000000
 1  Products of agriculture, hunting and related se...  0.000000  0.000000
 2  Products of forestry, logging and related services  0.000000  0.000000
 3  Fish and other fishing products; aquaculture pr...  0.000000  0.000000
 4  Mining and quarrying                                0.104701  0.000000
 ...                                                         ...       ...
 61 Services furnished by membership organisations      0.000000  0.000000
 62 Repair services of computers and personal and h...  0.036505  0.010174
 63 Other personal services                             0.016406  0.003875
 64 Services of households as employers; undifferen...  0.000000  0.000000
 65 Services provided by extraterritorial organisat...  0.000000  0.000000

                                                        Slovenia     Spain  \
 ID IND_USE (Labels)
 0  Total                                               0.000000  0.000000
 1  Products of agriculture, hunting and related se...  0.000000  0.000000
 2  Products of forestry, logging and related services  0.000000  0.000000
 3  Fish and other fishing products; aquaculture pr...  0.000000  0.000000
 4  Mining and quarrying                                0.011396  0.000000
 ...                                                         ...       ...
 61 Services furnished by membership organisations      0.000000  0.000000
 62 Repair services of computers and personal and h...  0.003591  0.134051
 63 Other personal services                             0.001550  0.087586
 64 Services of households as employers; undifferen...  0.000000  0.000000
 65 Services provided by extraterritorial organisat...  0.000000  0.000000

                                                          Sweden
 ID IND_USE (Labels)
 0  Total                                               0.000000
 1  Products of agriculture, hunting and related se...  0.000000
 2  Products of forestry, logging and related services  0.000000
 3  Fish and other fishing products; aquaculture pr...  0.000000
 4  Mining and quarrying                                0.007123
 ...                                                         ...
 61 Services furnished by membership organisations      0.000000

In [8]:
import pandas as pd

results = []

for i, df in enumerate(eu_firms_by_employed_number):

    # totale per riga
    row_totals = df.sum(axis=1)

    # differenza rispetto a 1
    diff_from_one = row_totals - 1

    # se il totale è 0 → metti 0
    diff_from_one = diff_from_one.where(row_totals != 0, 0)

    summary = pd.DataFrame({
        "row_total": row_totals,
        "diff_from_1": diff_from_one
    })

    # filtro: totale != 0 e errore > 1e-12
    mask = (row_totals != 0) & (diff_from_one.abs() > 0)

    print(f"\nDataFrame {i}")
    display(summary[mask])

    results.append(summary)

DataFrame 0

                                                       row_total   diff_from_1
ID IND_USE (Labels)
5  Food, beverages and tobacco products                      1.0 -1.110223e-16
6  Textiles, wearing apparel, leather and related ...        1.0 -1.110223e-16
9  Printing and recording services                           1.0  2.220446e-16
10 Coke and refined petroleum products                       1.0  2.220446e-16
11 Chemicals and chemical products                           1.0 -1.110223e-16
14 Other non-metallic mineral products                       1.0 -1.110223e-16
18 Electrical equipment                                      1.0 -2.220446e-16
19 Machinery and equipment n.e.c.                            1.0  2.220446e-16
22 Furniture and other manufactured goods                    1.0  2.220446e-16
24 Electricity, gas, steam and air conditioning              1.0 -1.110223e-16
25 Natural water; water treatment and supply services        1.0  2.220446e-16
26 Sewerage services; sewage sludge; waste collect...        1.0 -2.220446e-16
27 Constructions and construction works                      1.0 -1.110223e-16
28 Wholesale and retail trade and repair services ...        1.0  2.220446e-16
29 Wholesale trade services, except of motor vehic...        1.0 -1.110223e-16
31 Land transport services and transport services ...        1.0  2.220446e-16
34 Warehousing and support services for transporta...        1.0 -1.110223e-16
35 Postal and courier services                               1.0 -1.110223e-16
36 Accommodation and food services                           1.0 -1.110223e-16
37 Publishing services                                       1.0 -1.110223e-16
38 Motion picture, video and television programme ...        1.0 -1.110223e-16
39 Telecommunications services                               1.0 -2.220446e-16
41 Financial services, except insurance and pensio...        1.0 -1.110223e-16
42 Insurance, reinsurance and pension funding serv...        1.0  2.220446e-16
43 Services auxiliary to financial services and in...        1.0 -1.110223e-16
45 Real estate services excluding imputed rents              1.0 -3.330669e-16
46 Legal and accounting services; services of head...        1.0 -1.110223e-16
48 Scientific research and development services              1.0 -2.220446e-16
51 Rental and leasing services                               1.0 -1.110223e-16
52 Employment services                                       1.0 -1.110223e-16
54 Security and investigation services; services t...        1.0 -1.110223e-16
55 Public administration and defence services; com...        1.0 -2.220446e-16
57 Human health services                                     1.0  2.220446e-16
58 Residential care services; social work services...        1.0 -1.110223e-16
60 Sporting services and amusement and recreation ...        1.0 -1.110223e-16
62 Repair services of computers and personal and h...        1.0  2.220446e-16
63 Other personal services                                   1.0 -2.220446e-16

DataFrame 1

                                                       row_total   diff_from_1
ID IND_USE (Labels)
6  Textiles, wearing apparel, leather and related ...        1.0 -1.110223e-16
7  Wood and of products of wood and cork, except f...        1.0  2.220446e-16
8  Paper and paper products                                  1.0 -2.220446e-16
9  Printing and recording services                           1.0 -1.110223e-16
12 Basic pharmaceutical products and pharmaceutica...        1.0 -1.110223e-16
13 Rubber and plastic products                               1.0 -1.110223e-16
16 Fabricated metal products, except machinery and...        1.0 -1.110223e-16
18 Electrical equipment                                      1.0 -3.330669e-16
21 Other transport equipment                                 1.0  2.220446e-16
22 Furniture and other manufactured goods                    1.0 -3.330669e-16
23 Repair and installation services of machinery a...        1.0  2.220446e-16
25 Natural water; water treatment and supply services        1.0 -1.110223e-16
27 Constructions and construction works                      1.0 -1.110223e-16
28 Wholesale and retail trade and repair services ...        1.0  2.220446e-16
30 Retail trade services, except of motor vehicles...        1.0  2.220446e-16
31 Land transport services and transport services ...        1.0  2.220446e-16
32 Water transport services                                  1.0  2.220446e-16
33 Air transport services                                    1.0 -4.440892e-16
35 Postal and courier services                               1.0  2.220446e-16
37 Publishing services                                       1.0  2.220446e-16
41 Financial services, except insurance and pensio...        1.0 -1.110223e-16
42 Insurance, reinsurance and pension funding serv...        1.0  2.220446e-16
43 Services auxiliary to financial services and in...        1.0  2.220446e-16
45 Real estate services excluding imputed rents              1.0 -1.110223e-16
46 Legal and accounting services; services of head...        1.0 -1.110223e-16
47 Architectural and engineering services; technic...        1.0 -1.110223e-16
48 Scientific research and development services              1.0  2.220446e-16
49 Advertising and market research services                  1.0 -2.220446e-16
50 Other professional, scientific and technical se...        1.0 -1.110223e-16
52 Employment services                                       1.0  2.220446e-16
54 Security and investigation services; services t...        1.0 -2.220446e-16
62 Repair services of computers and personal and h...        1.0 -1.110223e-16

DataFrame 2

                                                       row_total   diff_from_1
ID IND_USE (Labels)
4  Mining and quarrying                                      1.0  2.220446e-16
5  Food, beverages and tobacco products                      1.0  2.220446e-16
6  Textiles, wearing apparel, leather and related ...        1.0  2.220446e-16
10 Coke and refined petroleum products                       1.0 -1.110223e-16
11 Chemicals and chemical products                           1.0  4.440892e-16
12 Basic pharmaceutical products and pharmaceutica...        1.0  2.220446e-16
13 Rubber and plastic products                               1.0  2.220446e-16
15 Basic metals                                              1.0  2.220446e-16
16 Fabricated metal products, except machinery and...        1.0 -1.110223e-16
17 Computer, electronic and optical products                 1.0  2.220446e-16
19 Machinery and equipment n.e.c.                            1.0 -1.110223e-16
21 Other transport equipment                                 1.0 -1.110223e-16
23 Repair and installation services of machinery a...        1.0  2.220446e-16
24 Electricity, gas, steam and air conditioning              1.0 -1.110223e-16
26 Sewerage services; sewage sludge; waste collect...        1.0  2.220446e-16
28 Wholesale and retail trade and repair services ...        1.0  2.220446e-16
29 Wholesale trade services, except of motor vehic...        1.0 -1.110223e-16
30 Retail trade services, except of motor vehicles...        1.0 -1.110223e-16
31 Land transport services and transport services ...        1.0  2.220446e-16
32 Water transport services                                  1.0  2.220446e-16
35 Postal and courier services                               1.0  2.220446e-16
36 Accommodation and food services                           1.0 -1.110223e-16
37 Publishing services                                       1.0 -1.110223e-16
38 Motion picture, video and television programme ...        1.0 -1.110223e-16
40 Computer programming, consultancy and related s...        1.0 -1.110223e-16
41 Financial services, except insurance and pensio...        1.0 -1.110223e-16
42 Insurance, reinsurance and pension funding serv...        1.0  2.220446e-16
43 Services auxiliary to financial services and in...        1.0 -1.110223e-16
45 Real estate services excluding imputed rents              1.0 -1.110223e-16
46 Legal and accounting services; services of head...        1.0 -2.220446e-16
47 Architectural and engineering services; technic...        1.0 -1.110223e-16
49 Advertising and market research services                  1.0 -2.220446e-16
50 Other professional, scientific and technical se...        1.0 -1.110223e-16
51 Rental and leasing services                               1.0 -1.110223e-16
52 Employment services                                       1.0  2.220446e-16
53 Travel agency, tour operator and other reservat...        1.0  2.220446e-16
58 Residential care services; social work services...        1.0 -1.110223e-16
59 Creative, arts, entertainment, library, archive...        1.0 -2.220446e-16
63 Other personal services                                   1.0 -2.220446e-16

DataFrame 3

                                                       row_total   diff_from_1
ID IND_USE (Labels)
5  Food, beverages and tobacco products                      1.0  2.220446e-16
6  Textiles, wearing apparel, leather and related ...        1.0 -1.110223e-16
7  Wood and of products of wood and cork, except f...        1.0 -1.110223e-16
8  Paper and paper products                                  1.0  2.220446e-16
10 Coke and refined petroleum products                       1.0 -1.110223e-16
13 Rubber and plastic products                               1.0  2.220446e-16
17 Computer, electronic and optical products                 1.0 -1.110223e-16
18 Electrical equipment                                      1.0 -1.110223e-16
19 Machinery and equipment n.e.c.                            1.0 -1.110223e-16
20 Motor vehicles, trailers and semi-trailers                1.0  2.220446e-16
21 Other transport equipment                                 1.0 -1.110223e-16
22 Furniture and other manufactured goods                    1.0 -1.110223e-16
23 Repair and installation services of machinery a...        1.0 -1.110223e-16
24 Electricity, gas, steam and air conditioning              1.0  4.440892e-16
27 Constructions and construction works                      1.0  2.220446e-16
29 Wholesale trade services, except of motor vehic...        1.0 -1.110223e-16
30 Retail trade services, except of motor vehicles...        1.0 -2.220446e-16
31 Land transport services and transport services ...        1.0 -1.110223e-16
32 Water transport services                                  1.0 -1.110223e-16
33 Air transport services                                    1.0 -1.110223e-16
35 Postal and courier services                               1.0 -2.220446e-16
36 Accommodation and food services                           1.0  2.220446e-16
38 Motion picture, video and television programme ...        1.0 -1.110223e-16
39 Telecommunications services                               1.0 -1.110223e-16
40 Computer programming, consultancy and related s...        1.0 -1.110223e-16
41 Financial services, except insurance and pensio...        1.0  2.220446e-16
45 Real estate services excluding imputed rents              1.0  2.220446e-16
46 Legal and accounting services; services of head...        1.0 -1.110223e-16
47 Architectural and engineering services; technic...        1.0 -2.220446e-16
50 Other professional, scientific and technical se...        1.0  2.220446e-16
51 Rental and leasing services                               1.0 -1.110223e-16
52 Employment services                                       1.0 -1.110223e-16
53 Travel agency, tour operator and other reservat...        1.0  2.220446e-16
57 Human health services                                     1.0 -1.110223e-16
58 Residential care services; social work services...        1.0 -2.220446e-16
59 Creative, arts, entertainment, library, archive...        1.0 -2.220446e-16
60 Sporting services and amusement and recreation ...        1.0  2.220446e-16
62 Repair services of computers and personal and h...        1.0 -2.220446e-16
63 Other personal services                                   1.0 -3.330669e-16

DataFrame 4

                                                       row_total   diff_from_1
ID IND_USE (Labels)
5  Food, beverages and tobacco products                      1.0 -2.220446e-16
6  Textiles, wearing apparel, leather and related ...        1.0 -1.110223e-16
7  Wood and of products of wood and cork, except f...        1.0  2.220446e-16
8  Paper and paper products                                  1.0 -3.330669e-16
12 Basic pharmaceutical products and pharmaceutica...        1.0  2.220446e-16
14 Other non-metallic mineral products                       1.0 -1.110223e-16
16 Fabricated metal products, except machinery and...        1.0 -2.220446e-16
18 Electrical equipment                                      1.0 -1.110223e-16
19 Machinery and equipment n.e.c.                            1.0 -2.220446e-16
23 Repair and installation services of machinery a...        1.0 -2.220446e-16
24 Electricity, gas, steam and air conditioning              1.0 -2.220446e-16
25 Natural water; water treatment and supply services        1.0 -1.110223e-16
28 Wholesale and retail trade and repair services ...        1.0 -2.220446e-16
29 Wholesale trade services, except of motor vehic...        1.0 -1.110223e-16
30 Retail trade services, except of motor vehicles...        1.0  2.220446e-16
32 Water transport services                                  1.0 -2.220446e-16
34 Warehousing and support services for transporta...        1.0 -2.220446e-16
35 Postal and courier services                               1.0 -2.220446e-16
38 Motion picture, video and television programme ...        1.0 -1.110223e-16
39 Telecommunications services                               1.0 -1.110223e-16
47 Architectural and engineering services; technic...        1.0 -1.110223e-16
48 Scientific research and development services              1.0  2.220446e-16
49 Advertising and market research services                  1.0  2.220446e-16
55 Public administration and defence services; com...        1.0  2.220446e-16
56 Education services                                        1.0 -2.220446e-16
59 Creative, arts, entertainment, library, archive...        1.0 -1.110223e-16

In [15]:
# errore in 0 / 61
print(eu_firms_by_employed_number[0].loc[61].to_string())

                                                Austria  Belgium  Bulgaria  Croatia  Cyprus  Czechia  Denmark  Estonia  Finland  France  Germany  Greece  Hungary  Ireland  Italy  Latvia  Lithuania  Luxembourg  Malta  Netherlands  Poland  Portugal  Romania  Slovakia  Slovenia  Spain  Sweden
IND_USE (Labels)
Services furnished by membership organisations      0.0      0.0       0.0      0.0     0.0      0.0      0.0      0.0      0.0     0.0      0.0     0.0      0.0      0.0    0.0     0.0        0.0         0.0    0.0          0.0     0.0       0.0      0.0       0.0       0.0    0.0     0.0