The NACE Rev. 2 classification (Statistical Classification of Economic Activities in the European Community) is a standardized system for categorizing economic activities. It consists of 21 broad sections (identified by letters A–U), further divided into divisions, groups, and classes.

Here are the 21 broad sections of NACE Rev. 2:


A. Agriculture, Forestry and Fishing

    Crop and animal production, hunting and related service activities
    Forestry and logging
    Fishing and aquaculture

B. Mining and Quarrying

    Mining of coal and lignite
    Extraction of crude petroleum and natural gas
    Mining of metal ores
    Other mining and quarrying
    Mining support service activities

C. Manufacturing

    Manufacture of food products, beverages, and tobacco products
    Manufacture of textiles, clothing, leather, and related products
    Manufacture of wood and paper products
    Manufacture of chemicals, pharmaceuticals, rubber, and plastic products
    Manufacture of basic metals and fabricated metal products
    Manufacture of machinery, equipment, and transport vehicles
    Other manufacturing activities

D. Electricity, Gas, Steam, and Air Conditioning Supply

    Production and distribution of electricity
    Distribution of gaseous fuels
    Steam and air conditioning supply

E. Water Supply; Sewerage, Waste Management, and Remediation Activities

    Water collection, treatment, and supply
    Sewerage
    Waste collection, treatment, and disposal activities
    Remediation activities and other waste management services

F. Construction

    Construction of buildings
    Civil engineering
    Specialized construction activities

G. Wholesale and Retail Trade; Repair of Motor Vehicles and Motorcycles

    Wholesale and retail trade and repair of motor vehicles
    Wholesale trade (except motor vehicles)
    Retail trade (except motor vehicles)

H. Transportation and Storage

    Land transport and transport via pipelines
    Water transport
    Air transport
    Warehousing and support activities for transportation
    Postal and courier activities

I. Accommodation and Food Service Activities

    Accommodation
    Food and beverage service activities

J. Information and Communication

    Publishing activities
    Motion picture, video, and television production, sound recording, and music publishing
    Telecommunications
    Computer programming, consultancy, and related activities
    Information service activities

K. Financial and Insurance Activities

    Financial service activities
    Insurance, reinsurance, and pension funding
    Activities auxiliary to financial services and insurance

L. Real Estate Activities

    Real estate activities

M. Professional, Scientific, and Technical Activities

    Legal and accounting activities
    Management consultancy
    Architectural and engineering activities
    Scientific research and development
    Advertising and market research
    Other professional, scientific, and technical activities
    Veterinary activities

N. Administrative and Support Service Activities

    Rental and leasing activities
    Employment activities
    Travel agency, tour operator, and reservation services
    Security and investigation activities
    Services to buildings and landscape activities
    Office administrative and support activities

O. Public Administration and Defence; Compulsory Social Security

    Administration of the state, economic and social policy
    Defence activities
    Provision of services for the community

P. Education

    Education

Q. Human Health and Social Work Activities

    Human health activities
    Residential care activities
    Social work activities without accommodation

R. Arts, Entertainment, and Recreation

    Creative, arts, and entertainment activities
    Libraries, archives, museums, and other cultural activities
    Sports, amusement, and recreation activities

S. Other Service Activities

    Activities of membership organizations
    Repair of computers and personal goods
    Other personal service activities

T. Activities of Households as Employers; Undifferentiated Goods- and Services-Producing Activities of Households for Own Use

    Activities of households as employers
    Undifferentiated goods- and services-producing activities of households for own use

U. Activities of Extraterritorial Organizations and Bodies

    Activities of international organizations (e.g., the United Nations, embassies)

These sections form the broadest categories of the NACE Rev. 2 classification. They are further broken down into more detailed divisions, groups, and classes. Let me know if you'd like the divisions or deeper breakdowns!

<span style="color: DodgerBlue;">
==============================================================================================  
    
### Libraries

==============================================================================================  
</span>

In [1]:
import pandas as pd
import numpy as np
import csv

In [2]:
pd.set_option('display.max_columns', 1000)
pd.set_option('display.max_rows', 1000)

<span style="color: DodgerBlue;">
==============================================================================================  
    
### **data_import.ipynb** starts from the naio dataset to prepare this reduced version.  
### source: https://ec.europa.eu/eurostat/databrowser/view/naio_10_cp1610__custom_13696232/default/table  

### year 2022, using the table at basic prices [naio_10_cp1610__custom_13696232], i.e., without VAT

### Columns "Added value, gross" and "Compensation of employees" are trasposed from the related rows

==============================================================================================  
</span>

In [3]:
mini_naio = pd.read_pickle('mini_naio.xp')
sbs = pd.read_pickle('sbs.xp')
lc = pd.read_pickle('lc.xp')
nama = pd.read_pickle('nama_assets.xp')

# Unit of measure:   Million euro
mini_naio

,IND_USE (Labels),Total intermediate goods,Final consumption expenditure by government,Final consumption expenditure by households,Exports of goods and services,Changes in inventories and acquisition less disposals of valuables,Gross fixed capital formation,"Added value, gross",Compensation of employees
0,Total,16939701.18,3375443.51,7283949.99,3291159.74,360243.46,3320258.70,14303899.14,7447036.79
1,"Products of agriculture, hunting and related s...",381871.38,1756.62,142619.06,30647.16,10474.61,7444.62,244253.17,54367.01
2,"Products of forestry, logging and related serv...",42864.37,878.87,7533.20,2148.11,11085.96,456.39,29364.21,9874.05
3,Fish and other fishing products; aquaculture p...,10980.08,10.07,10712.56,575.75,-45.88,56.16,6506.32,2826.59
4,Mining and quarrying,337295.56,333.07,12425.73,10117.36,2681.28,1268.44,61205.82,23611.51
5,"Food, beverages and tobacco products",508405.01,1203.30,694013.10,154747.91,36172.89,0.55,284672.03,147133.21
6,"Textiles, wearing apparel, leather and related...",121877.73,729.71,159969.25,61689.96,29565.80,1603.87,70250.23,39609.14
7,"Wood and of products of wood and cork, except ...",143899.99,0.47,10975.47,21934.64,6849.82,9296.21,53407.64,28282.11
8,Paper and paper products,160065.88,165.90,30814.85,33893.65,-1069.85,0.52,55568.55,29110.21
9,Printing and recording services,62412.30,7.16,5172.42,1151.64,-706.80,5.73,28104.73,16477.14
10,Coke and refined petroleum products,283569.56,523.49,135052.77,85593.18,2382.46,0.00,29899.21,17285.59
11,Chemicals and chemical products,534811.08,801.93,60878.33,196447.33,11874.38,40.98,191018.79,81359.69
12,Basic pharmaceutical products and pharmaceutic...,113966.11,79285.51,59576.68,175822.82,-7890.30,0.36,175249.77,41904.61
13,Rubber and plastic products,301315.74,121.55,30026.92,56273.47,2462.18,3960.68,111743.76,65874.31
14,Other non-metallic mineral products,215991.87,1.36,17849.72,28403.61,5532.65,7048.47,84887.81,46347.81
15,Basic metals,486510.43,0.00,553.42,78024.07,1442.06,3327.25,79412.54,54662.71
16,"Fabricated metal products, except machinery an...",509859.18,196.82,23002.90,60516.11,7846.52,70248.18,219050.93,140109.47
17,"Computer, electronic and optical products",165620.14,1540.29,66318.55,170286.01,31309.48,99794.45,183804.28,58942.70
18,Electrical equipment,223506.37,36.66,51399.80,97631.76,21467.55,48148.64,111970.00,70048.85
19,Machinery and equipment n.e.c.,280046.00,209.15,9267.80,264060.26,21347.77,237529.45,250544.27,160162.85
20,"Motor vehicles, trailers and semi-trailers",332536.61,64.90,219480.93,226641.19,47611.65,166506.40,236969.80,129438.06
21,Other transport equipment,87614.40,1178.74,24855.56,74294.48,2203.36,101785.37,52935.76,34803.27
22,Furniture and other manufactured goods,84434.67,8279.24,106309.34,75655.31,26230.03,47797.81,107188.65,59632.56
23,Repair and installation services of machinery ...,203693.79,77.98,2484.86,17726.03,7007.76,86048.80,84932.65,58847.52
24,"Electricity, gas, steam and air conditioning",814675.41,1810.37,268734.62,5749.54,1777.77,263.90,405732.74,99377.63
25,Natural water; water treatment and supply serv...,36097.20,2844.61,29980.71,17.15,95.58,10.92,32535.28,13088.27
26,Sewerage services; sewage sludge; waste collec...,250530.33,18458.39,53456.88,11719.11,712.04,55.88,106844.29,50858.73
27,Constructions and construction works,805321.29,7232.99,58221.30,17618.46,20523.87,1310617.30,774334.30,413291.84
28,Wholesale and retail trade and repair services...,204184.45,881.72,169640.43,19192.52,1148.55,32635.51,209617.48,111562.35
29,"Wholesale trade services, except of motor vehi...",1239382.04,20340.09,317491.67,194265.85,19311.66,106583.15,823153.41,421147.23
30,"Retail trade services, except of motor vehicle...",310517.05,35232.06,744066.38,29047.65,11532.85,32345.85,610924.50,340485.76
31,Land transport services and transport services...,638746.86,30222.68,148278.33,58452.50,2955.25,19378.02,314718.92,184838.99
32,Water transport services,68399.74,525.15,19049.52,153100.22,-3759.41,1652.60,49518.08,18008.12
33,Air transport services,56780.20,729.49,35637.65,43845.45,575.85,1640.49,25547.35,25788.34
34,Warehousing and support services for transport...,650934.12,55482.10,31325.63,52388.58,172.10,514.58,271507.74,143616.07
35,Postal and courier services,146259.05,27.15,10709.13,22455.74,17.66,0.00,59617.46,47943.76
36,Accommodation and food services,228827.55,4762.02,585974.21,10504.33,8278.15,418.81,359333.94,211610.68
37,Publishing services,93446.31,650.21,58550.58,80816.35,1060.97,42452.65,108838.22,34828.54
38,"Motion picture, video and television programme...",78189.71,23949.48,26163.96,9300.66,283.90,14855.89,58098.55,30393.49
39,Telecommunications services,206613.61,877.53,133890.33,15717.15,190.31,0.00,146298.29,43951.51
40,"Computer programming, consultancy and related ...",567915.92,1649.84,7423.42,168200.12,1525.93,295165.60,450679.00,269237.19
41,"Financial services, except insurance and pensi...",572095.55,1035.53,156614.98,74424.92,16.99,57.03,388614.49,180880.76
42,"Insurance, reinsurance and pension funding ser...",130659.44,1223.18,193309.20,26737.53,391.85,2611.90,103151.62,49165.15
43,Services auxiliary to financial services and i...,298724.73,650.28,25936.25,12866.30,244.42,1166.40,113141.05,60211.07
44,Imputed rents of owner-occupied dwellings,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
45,Real estate services excluding imputed rents,604139.40,25061.88,1384060.75,3297.31,97.62,38782.86,1477653.98,67044.55
46,Legal and accounting services; services of hea...,946696.11,1838.62,24659.45,95641.75,1782.68,39242.12,502761.77,297724.62
47,Architectural and engineering services; techni...,322830.04,2058.46,10594.16,31459.44,2205.26,92446.33,195768.16,121716.20
48,Scientific research and development services,35686.28,44959.62,43.57,43648.71,165.46,368159.24,136641.75,74168.22
49,Advertising and market research services,206350.10,39.55,136.25,18142.21,23.29,6.95,59147.56,35597.86
50,"Other professional, scientific and technical s...",149932.29,1645.29,26621.39,15828.34,928.87,84.08,72210.44,28555.94
51,Rental and leasing services,394930.26,1292.25,35508.16,91015.45,10.62,2569.35,178694.54,27442.16
52,Employment services,211384.30,2655.19,1729.38,3988.97,88.72,148.03,165922.73,150324.38
53,"Travel agency, tour operator and other reserva...",26812.97,1326.30,50709.22,6403.73,187.15,171.30,15576.77,12689.44
54,Security and investigation services; services ...,538895.83,3554.52,34440.62,27697.32,206.48,11822.25,292940.20,203139.04
55,Public administration and defence services; co...,103357.40,1125195.11,24422.76,10502.25,147.90,4105.41,903702.99,673050.23
56,Education services,107215.89,628476.00,95520.99,1008.61,142.34,153.41,680351.66,569962.28
57,Human health services,93110.47,849982.96,207951.08,1703.53,17.00,8.20,706719.72,495033.36
58,Residential care services; social work service...,12470.59,276796.15,106973.34,36.95,8.74,9.13,317070.06,296960.17
59,"Creative, arts, entertainment, library, archiv...",38484.29,56770.01,77353.78,5636.48,11794.79,4323.31,104132.23,51425.54
60,Sporting services and amusement and recreation...,54289.63,31997.03,46336.77,923.07,40.14,9.30,75069.94,52098.60
61,Services furnished by membership organisations,41007.75,13189.07,9455.62,218.30,8.56,8.44,91532.10,80847.76
62,Repair services of computers and personal and ...,22605.25,12.75,15672.30,1506.32,-574.30,3397.31,15961.52,8549.41
63,Other personal services,35389.07,493.25,136298.27,1798.10,63.75,7.41,104965.09,35311.70
64,Services of households as employers; undiffere...,2343.52,2102.19,39706.68,0.96,0.07,0.07,41928.30,44398.89
65,Services provided by extraterritorial organisa...,320.99,9.69,7.09,0.00,6.68,8.38,NaN,NaN

<span style="color: DodgerBlue;">
==============================================================================================  
    
### Calculating the shares of production of intermediate good, investment goods, 
### consumption goods

==============================================================================================  
</span>

In [4]:
mini_naio['Consumption good share'] = mini_naio['Final consumption expenditure by households']/\
    (mini_naio['Final consumption expenditure by households']+ mini_naio['Gross fixed capital formation']\
    +mini_naio['Total intermediate goods'])

mini_naio['Investment good share'] = mini_naio['Gross fixed capital formation']/\
    (mini_naio['Final consumption expenditure by households']+ mini_naio['Gross fixed capital formation']\
    +mini_naio['Total intermediate goods'])

mini_naio['Intermediate good share'] = mini_naio['Total intermediate goods']/\
    (mini_naio['Final consumption expenditure by households']+ mini_naio['Gross fixed capital formation']\
    +mini_naio['Total intermediate goods'])

pd.set_option('display.max_colwidth', 100)
mini_naio

,IND_USE (Labels),Total intermediate goods,Final consumption expenditure by government,Final consumption expenditure by households,Exports of goods and services,Changes in inventories and acquisition less disposals of valuables,Gross fixed capital formation,"Added value, gross",Compensation of employees,Consumption good share,Investment good share,Intermediate good share
0,Total,16939701.18,3375443.51,7283949.99,3291159.74,360243.46,3320258.70,14303899.14,7447036.79,0.264449,1.205442e-01,0.615007
1,"Products of agriculture, hunting and related services",381871.38,1756.62,142619.06,30647.16,10474.61,7444.62,244253.17,54367.01,0.268114,1.399535e-02,0.717891
2,"Products of forestry, logging and related services",42864.37,878.87,7533.20,2148.11,11085.96,456.39,29364.21,9874.05,0.148134,8.974522e-03,0.842891
3,Fish and other fishing products; aquaculture products; support services to fishing,10980.08,10.07,10712.56,575.75,-45.88,56.16,6506.32,2826.59,0.492559,2.582211e-03,0.504859
4,Mining and quarrying,337295.56,333.07,12425.73,10117.36,2681.28,1268.44,61205.82,23611.51,0.035402,3.613895e-03,0.960984
5,"Food, beverages and tobacco products",508405.01,1203.30,694013.10,154747.91,36172.89,0.55,284672.03,147133.21,0.577181,4.574114e-07,0.422819
6,"Textiles, wearing apparel, leather and related products",121877.73,729.71,159969.25,61689.96,29565.80,1603.87,70250.23,39609.14,0.564363,5.658371e-03,0.429978
7,"Wood and of products of wood and cork, except furniture; articles of straw and plaiting materials",143899.99,0.47,10975.47,21934.64,6849.82,9296.21,53407.64,28282.11,0.066854,5.662493e-02,0.876521
8,Paper and paper products,160065.88,165.90,30814.85,33893.65,-1069.85,0.52,55568.55,29110.21,0.161435,2.724207e-06,0.838563
9,Printing and recording services,62412.30,7.16,5172.42,1151.64,-706.80,5.73,28104.73,16477.14,0.076526,8.477529e-05,0.923389
10,Coke and refined petroleum products,283569.56,523.49,135052.77,85593.18,2382.46,0.00,29899.21,17285.59,0.322612,0.000000e+00,0.677388
11,Chemicals and chemical products,534811.08,801.93,60878.33,196447.33,11874.38,40.98,191018.79,81359.69,0.102191,6.878951e-05,0.897740
12,Basic pharmaceutical products and pharmaceutical preparations,113966.11,79285.51,59576.68,175822.82,-7890.30,0.36,175249.77,41904.61,0.343296,2.074412e-06,0.656702
13,Rubber and plastic products,301315.74,121.55,30026.92,56273.47,2462.18,3960.68,111743.76,65874.31,0.089552,1.181223e-02,0.898636
14,Other non-metallic mineral products,215991.87,1.36,17849.72,28403.61,5532.65,7048.47,84887.81,46347.81,0.074099,2.926011e-02,0.896641
15,Basic metals,486510.43,0.00,553.42,78024.07,1442.06,3327.25,79412.54,54662.71,0.001129,6.784891e-03,0.992087
16,"Fabricated metal products, except machinery and equipment",509859.18,196.82,23002.90,60516.11,7846.52,70248.18,219050.93,140109.47,0.038140,1.164765e-01,0.845383
17,"Computer, electronic and optical products",165620.14,1540.29,66318.55,170286.01,31309.48,99794.45,183804.28,58942.70,0.199915,3.008275e-01,0.499257
18,Electrical equipment,223506.37,36.66,51399.80,97631.76,21467.55,48148.64,111970.00,70048.85,0.159106,1.490417e-01,0.691853
19,Machinery and equipment n.e.c.,280046.00,209.15,9267.80,264060.26,21347.77,237529.45,250544.27,160162.85,0.017591,4.508541e-01,0.531555
20,"Motor vehicles, trailers and semi-trailers",332536.61,64.90,219480.93,226641.19,47611.65,166506.40,236969.80,129438.06,0.305461,2.317340e-01,0.462805
21,Other transport equipment,87614.40,1178.74,24855.56,74294.48,2203.36,101785.37,52935.76,34803.27,0.116009,4.750658e-01,0.408925
22,Furniture and other manufactured goods,84434.67,8279.24,106309.34,75655.31,26230.03,47797.81,107188.65,59632.56,0.445663,2.003750e-01,0.353962
23,Repair and installation services of machinery and equipment,203693.79,77.98,2484.86,17726.03,7007.76,86048.80,84932.65,58847.52,0.008503,2.944583e-01,0.697039
24,"Electricity, gas, steam and air conditioning",814675.41,1810.37,268734.62,5749.54,1777.77,263.90,405732.74,99377.63,0.247985,2.435234e-04,0.751772
25,Natural water; water treatment and supply services,36097.20,2844.61,29980.71,17.15,95.58,10.92,32535.28,13088.27,0.453643,1.652322e-04,0.546192
26,"Sewerage services; sewage sludge; waste collection, treatment and disposal services; materials r...",250530.33,18458.39,53456.88,11719.11,712.04,55.88,106844.29,50858.73,0.175820,1.837897e-04,0.823996
27,Constructions and construction works,805321.29,7232.99,58221.30,17618.46,20523.87,1310617.30,774334.30,413291.84,0.026779,6.028155e-01,0.370406
28,Wholesale and retail trade and repair services of motor vehicles and motorcycles,204184.45,881.72,169640.43,19192.52,1148.55,32635.51,209617.48,111562.35,0.417360,8.029198e-02,0.502348
29,"Wholesale trade services, except of motor vehicles and motorcycles",1239382.04,20340.09,317491.67,194265.85,19311.66,106583.15,823153.41,421147.23,0.190863,6.407329e-02,0.745064
30,"Retail trade services, except of motor vehicles and motorcycles",310517.05,35232.06,744066.38,29047.65,11532.85,32345.85,610924.50,340485.76,0.684558,2.975893e-02,0.285683
31,Land transport services and transport services via pipelines,638746.86,30222.68,148278.33,58452.50,2955.25,19378.02,314718.92,184838.99,0.183876,2.403019e-02,0.792094
32,Water transport services,68399.74,525.15,19049.52,153100.22,-3759.41,1652.60,49518.08,18008.12,0.213795,1.854731e-02,0.767658
33,Air transport services,56780.20,729.49,35637.65,43845.45,575.85,1640.49,25547.35,25788.34,0.378889,1.744120e-02,0.603670
34,Warehousing and support services for transportation,650934.12,55482.10,31325.63,52388.58,172.10,514.58,271507.74,143616.07,0.045880,7.536604e-04,0.953366
35,Postal and courier services,146259.05,27.15,10709.13,22455.74,17.66,0.00,59617.46,47943.76,0.068225,0.000000e+00,0.931775
36,Accommodation and food services,228827.55,4762.02,585974.21,10504.33,8278.15,418.81,359333.94,211610.68,0.718792,5.137383e-04,0.280694
37,Publishing services,93446.31,650.21,58550.58,80816.35,1060.97,42452.65,108838.22,34828.54,0.301109,2.183222e-01,0.480568
38,"Motion picture, video and television programme production services, sound recording and music pu...",78189.71,23949.48,26163.96,9300.66,283.90,14855.89,58098.55,30393.49,0.219479,1.246200e-01,0.655901
39,Telecommunications services,206613.61,877.53,133890.33,15717.15,190.31,0.00,146298.29,43951.51,0.393212,0.000000e+00,0.606788
40,"Computer programming, consultancy and related services; Information services",567915.92,1649.84,7423.42,168200.12,1525.93,295165.60,450679.00,269237.19,0.008528,3.390740e-01,0.652398
41,"Financial services, except insurance and pension funding",572095.55,1035.53,156614.98,74424.92,16.99,57.03,388614.49,180880.76,0.214904,7.825540e-05,0.785018
42,"Insurance, reinsurance and pension funding services, except compulsory social security",130659.44,1223.18,193309.20,26737.53,391.85,2611.90,103151.62,49165.15,0.591919,7.997721e-03,0.400083
43,Services auxiliary to financial services and insurance services,298724.73,650.28,25936.25,12866.30,244.42,1166.40,113141.05,60211.07,0.079601,3.579810e-03,0.916819
44,Imputed rents of owner-occupied dwellings,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN
45,Real estate services excluding imputed rents,604139.40,25061.88,1384060.75,3297.31,97.62,38782.86,1477653.98,67044.55,0.682818,1.913329e-02,0.298049
46,Legal and accounting services; services of head offices; management consultancy services,946696.11,1838.62,24659.45,95641.75,1782.68,39242.12,502761.77,297724.62,0.024401,3.883061e-02,0.936769
47,Architectural and engineering services; technical testing and analysis services,322830.04,2058.46,10594.16,31459.44,2205.26,92446.33,195768.16,121716.20,0.024876,2.170761e-01,0.758047
48,Scientific research and development services,35686.28,44959.62,43.57,43648.71,165.46,368159.24,136641.75,74168.22,0.000108,9.115355e-01,0.088357
49,Advertising and market research services,206350.10,39.55,136.25,18142.21,23.29,6.95,59147.56,35597.86,0.000660,3.365727e-05,0.999307
50,"Other professional, scientific and technical services and veterinary services",149932.29,1645.29,26621.39,15828.34,928.87,84.08,72210.44,28555.94,0.150712,4.760024e-04,0.848812
51,Rental and leasing services,394930.26,1292.25,35508.16,91015.45,10.62,2569.35,178694.54,27442.16,0.082004,5.933727e-03,0.912063
52,Employment services,211384.30,2655.19,1729.38,3988.97,88.72,148.03,165922.73,150324.38,0.008109,6.941237e-04,0.991197
53,"Travel agency, tour operator and other reservation services and related services",26812.97,1326.30,50709.22,6403.73,187.15,171.30,15576.77,12689.44,0.652683,2.204818e-03,0.345112
54,"Security and investigation services; services to buildings and landscape; office administrative,...",538895.83,3554.52,34440.62,27697.32,206.48,11822.25,292940.20,203139.04,0.058857,2.020349e-02,0.920940
55,Public administration and defence services; compulsory social security services,103357.40,1125195.11,24422.76,10502.25,147.90,4105.41,903702.99,673050.23,0.185181,3.112858e-02,0.783690
56,Education services,107215.89,628476.00,95520.99,1008.61,142.34,153.41,680351.66,569962.28,0.470801,7.561229e-04,0.528443
57,Human health services,93110.47,849982.96,207951.08,1703.53,17.00,8.20,706719.72,495033.36,0.690707,2.723621e-05,0.309265
58,Residential care services; social work services without accommodation,12470.59,276796.15,106973.34,36.95,8.74,9.13,317070.06,296960.17,0.895526,7.643170e-05,0.104397
59,"Creative, arts, entertainment, library, archive, museum, other cultural services; gambling and b...",38484.29,56770.01,77353.78,5636.48,11794.79,4323.31,104132.23,51425.54,0.643749,3.597920e-02,0.320272
60,Sporting services and amusement and recreation services,54289.63,31997.03,46336.77,923.07,40.14,9.30,75069.94,52098.60,0.460441,9.241253e-05,0.539467
61,Services furnished by membership organisations,41007.75,13189.07,9455.62,218.30,8.56,8.44,91532.10,80847.76,0.187345,1.672221e-04,0.812488
62,Repair services of computers and personal and household goods,22605.25,12.75,15672.30,1506.32,-574.30,3397.31,15961.52,8549.41,0.376061,8.151941e-02,0.542419
63,Other personal services,35389.07,493.25,136298.27,1798.10,63.75,7.41,104965.09,35311.70,0.793841,4.315799e-05,0.206116
64,Services of households as employers; undifferentiated goods and services produced by households ...,2343.52,2102.19,39706.68,0.96,0.07,0.07,41928.30,44398.89,0.944267,1.664674e-06,0.055731
65,Services provided by extraterritorial organisations and bodies,320.99,9.69,7.09,0.00,6.68,8.38,NaN,NaN,0.021072,2.490638e-02,0.954021

<span style="color: DodgerBlue;">
==============================================================================================  
    
### **sbs** reports the number of employees by sectors and dimensional classes of the firms
### Sectors are less detailed than in naio

### The total number of employees, from sbs['Total'].sum(), is 
## 156,946,662 (157 millions) not consistent with the sum of the classes so we will use the sum of the classes, see below
==============================================================================================  
</span>

In [5]:
pd.set_option('display.max_colwidth', 100)
sbs

,SIZE_EMP (Labels),Total,From 0 to 1 person employed,From 0 to 9 persons employed,From 2 to 9 persons employed,From 10 to 19 persons employed,From 20 to 49 persons employed,From 50 to 249 persons employed,250 persons employed or more
0,Mining and quarrying,371000,NaN,30000,NaN,24400,38600,63848,213000
1,Manufacturing,30007527,NaN,3720000,NaN,2130000,3137995,6501120,14514113
2,"Electricity, gas, steam and air conditioning supply",1380000,NaN,192263,NaN,26554,48700,137668,977247
3,"Water supply; sewerage, waste management and remediation activities",1585225,NaN,134000,NaN,80000,150000,370000,NaN
4,Construction,13814274,2292700,6463861,4171161,1989977,1869881,1756785,1733772
5,Wholesale and retail trade; repair of motor vehicles and motorcycles,29779934,2869697,10159638,7289941,2867238,3099214,4100000,9600000
6,Transportation and storage,10368577,795843,2132860,1337017,778285,1090577,1605824,4761030
7,Accommodation and food service activities,10888928,670000,4500000,3800000,1850000,1570000,1421984,1570000
8,Information and communication,7169884,839595,1694054,854459,458755,648890,1252840,3115346
9,Financial and insurance activities,4950777,NaN,912551,NaN,NaN,177248,494777,NaN
10,Real estate activities,2674967,732689,1703331,970642,204985,198000,271677,NaN
11,"Professional, scientific and technical activities",12013424,3268760,6306152,3037392,1085161,1100000,1360181,2200000
12,Administrative and support service activities,13987371,1054559,2443205,1388646,730461,1093974,2313468,7406264
13,Education,2453280,572741,1074485,501744,221804,290962,417229,448801
14,Human health and social work activities,13308561,1528116,3417453,1889337,944000,994469,1780000,6169122
15,"Arts, entertainment and recreation",2192933,532163,1018050,485887,203295,247350,314087,410147

In [6]:
pd.set_option('future.no_silent_downcasting', True)
sbs=sbs.fillna(0, inplace=False)

In [7]:
#sbs

In [8]:
# We add a row to sbs to manage sectors 61-64 of naio
# to fix Total e Total2 we use the same wage of sectors 59-60, with a naio value of compensantion of employees of 
# 51425.54 + 52098.60, with 2192933	workers from sbs row 15, giving 0.0472080725 millions per capita, so 47208.0725 €
# the sum of compensations of employees 61-64 interval is 80847.76+8549.41+35311.70+44398.89 => 169107.76 => 169107
# columns 3 and 5 are ignored, the distribution is quite arbitrary, anyway on Eu27 scale these are tiny values

sbs.loc[16]=['Artificial row related to naio 61-64 sectors',169107,0,89107,0,20000,20000,20000,20000]
sbs

,SIZE_EMP (Labels),Total,From 0 to 1 person employed,From 0 to 9 persons employed,From 2 to 9 persons employed,From 10 to 19 persons employed,From 20 to 49 persons employed,From 50 to 249 persons employed,250 persons employed or more
0,Mining and quarrying,371000,0,30000,0,24400,38600,63848,213000
1,Manufacturing,30007527,0,3720000,0,2130000,3137995,6501120,14514113
2,"Electricity, gas, steam and air conditioning supply",1380000,0,192263,0,26554,48700,137668,977247
3,"Water supply; sewerage, waste management and remediation activities",1585225,0,134000,0,80000,150000,370000,0
4,Construction,13814274,2292700,6463861,4171161,1989977,1869881,1756785,1733772
5,Wholesale and retail trade; repair of motor vehicles and motorcycles,29779934,2869697,10159638,7289941,2867238,3099214,4100000,9600000
6,Transportation and storage,10368577,795843,2132860,1337017,778285,1090577,1605824,4761030
7,Accommodation and food service activities,10888928,670000,4500000,3800000,1850000,1570000,1421984,1570000
8,Information and communication,7169884,839595,1694054,854459,458755,648890,1252840,3115346
9,Financial and insurance activities,4950777,0,912551,0,0,177248,494777,0
10,Real estate activities,2674967,732689,1703331,970642,204985,198000,271677,0
11,"Professional, scientific and technical activities",12013424,3268760,6306152,3037392,1085161,1100000,1360181,2200000
12,Administrative and support service activities,13987371,1054559,2443205,1388646,730461,1093974,2313468,7406264
13,Education,2453280,572741,1074485,501744,221804,290962,417229,448801
14,Human health and social work activities,13308561,1528116,3417453,1889337,944000,994469,1780000,6169122
15,"Arts, entertainment and recreation",2192933,532163,1018050,485887,203295,247350,314087,410147
16,Artificial row related to naio 61-64 sectors,169107,0,89107,0,20000,20000,20000,20000

In [9]:
sbs.sum(axis=0)  # this cell has been added wrt previous versions (remember that it changes the numeration of the following)

0
SIZE_EMP (Labels)                  Mining and quarryingManufacturingElectricity, gas, steam and air conditioning supplyWater supply...
Total                                                                                                                        157115769
From 0 to 1 person employed                                                                                                   15156863
From 0 to 9 persons employed                                                                                                  45991010
From 2 to 9 persons employed                                                                                                  25726226
From 10 to 19 persons employed                                                                                                13614915
From 20 to 49 persons employed                                                                                                15775860
From 50 to 249 persons employed                                                                                               24181488
250 persons employed or more                                                                                                  53138842
dtype: object

<span style="color: DodgerBlue;">
==============================================================================================  
    
### The Labor Cost table, 2023, from https://ec.europa.eu/eurostat/databrowser/product/page/lc_lci_lev__custom_13900260, is used uniquely for rows 864-923 of ff, to set the wage, employing row 26 of lc (Other service activities)
### We do that because the sbs table does not provide employees data for these sectors

ff.iloc[864:879, ff.columns.get_loc('Wage')] = lc['lc'].loc[26] * 1e3 #mini_naio['Compensation of employees'].loc[61]  
ff.iloc[879:894, ff.columns.get_loc('Wage')] = lc['lc'].loc[26] * 1e3 #mini_naio['Compensation of employees'].loc[62]  
ff.iloc[894:909, ff.columns.get_loc('Wage')] = lc['lc'].loc[26] * 1e3 #mini_naio['Compensation of employees'].loc[63]  
ff.iloc[909:924, ff.columns.get_loc('Wage')] = lc['lc'].loc[26] * 1e3 #mini_naio['Compensation of employees'].loc[64]  

==============================================================================================  
</span>

In [10]:
#data 2023
pd.set_option('display.max_colwidth', 100)
lc

,NACE_R2,lc
0,"Industry, construction and services (except activities of households as employers and extra-terr...",NaN
1,"Industry, construction and services (except public administration, defense, compulsory social se...",31.8
2,Business economy,31.6
3,Industry and construction,NaN
4,Industry (except construction),32.2
5,Mining and quarrying,31.8
6,Manufacturing,32.0
7,"Electricity, gas, steam and air conditioning supply",45.0
8,"Water supply; sewerage, waste management and remediation activities",26.2
9,Construction,28.5
10,Services of the business economy,31.8
11,Wholesale and retail trade; transport; accommodation and food service activities; information an...,NaN
12,Wholesale and retail trade; repair of motor vehicles and motorcycles,27.1
13,Transportation and storage,27.8
14,Accommodation and food service activities,19.2
15,Information and communication,NaN
16,"Financial and insurance activities; real estate activities; professional, scientific and technic...",NaN
17,Financial and insurance activities,54.2
18,Real estate activities,NaN
19,"Professional, scientific and technical activities",42.9
20,Administrative and support service activities,24.1
21,Public administration and defence; compulsory social security; education; human health and socia...,NaN
22,"Education; human health and social work activities; arts, entertainment and recreation; other se...",32.4
23,Education,33.4
24,Human health and social work activities,32.4
25,"Arts, entertainment and recreation",26.5
26,Other service activities,29.9

## computing labor quantity for ff

<span style="color: DodgerBlue;">
==============================================================================================  
    
### The number of firm is obtained using the classes of **sbs**, dividing the number of employees by the center of the class

### The upper value of the open last class is set to 1850 by choice, anyway using a different upper values changes in a limited way the total number of firms

### (at https://www.statista.com/statistics/1248775/number-of-businesses-eu/, year 2022, 25 millions of non financial business activities, certainly including independent workers non included in the IOT)

### Agriculture values are set in a consistent way to this [source](https://ec.europa.eu/eurostat/statistics-explained/index.php?title=Farmers_and_the_agricultural_labour_force_-_statistics#:~:text=Agriculture%20remains%20a%20big%20employer%20in%20the%20EU%3B%20about%208.7,an%20estimated%208.7%20million%20persons) rounding 8.7 millions to 9; the owners of the farms have their conmpensation in (Added value, gross - Compensation of employees) large amount for agricultural sectors

==============================================================================================  
</span>

In [11]:
### providing Eurostat totals (2025) with weigths -- sbs.xlsx for a recognition (gray row: Industry, etc)
### nb: gray values are used to build unit dimensional classes

eurostatAdj =[1.057, 1.025, 1.006, 0.992, 1.129]


sbs['From 0 to 9 persons employed'] *= eurostatAdj[0] 
sbs['From 10 to 19 persons employed'] *= eurostatAdj[1] 
sbs['From 20 to 49 persons employed'] *= eurostatAdj[2] 
sbs['From 50 to 249 persons employed'] *= eurostatAdj[3] 
sbs['250 persons employed or more'] *= eurostatAdj[4] 

sbs.sum(axis=0)  # this cell has been added wrt previous versions (remember that it changes the numeration of the following)

0
SIZE_EMP (Labels)                  Mining and quarryingManufacturingElectricity, gas, steam and air conditioning supplyWater supply...
Total                                                                                                                        157115769
From 0 to 1 person employed                                                                                                   15156863
From 0 to 9 persons employed                                                                                               48612497.57
From 2 to 9 persons employed                                                                                                  25726226
From 10 to 19 persons employed                                                                                            13955287.875
From 20 to 49 persons employed                                                                                             15870515.16
From 50 to 249 persons employed                                                                                           23988036.096
250 persons employed or more                                                                                              59993752.618
dtype: object

In [12]:
column_names = ['#','NACE definition', 'type', 'dimensional class', 'Share of firms',\
                'Share of firms per sbs sector', 'sbs reference row'] 

# type = consumption / investment / intermediate good

# dimensional class gives the range of number of workers per class

# share of firms is computed by considering the weight of each subsector and each type (C-I-Int) on the total

# share of firms per sbs is computed by considering the weigth of each subsector in the sbs sector 
# considering compensation of employees and not considering type (agriculture is calculated aside)

ff = pd.DataFrame(columns=column_names)



workforce = sbs['From 0 to 9 persons employed'].sum()+\
            sbs['From 10 to 19 persons employed'].sum()+\
            sbs['From 20 to 49 persons employed'].sum()+\
            sbs['From 50 to 249 persons employed'].sum()+\
            sbs['250 persons employed or more'].sum()

agriculture = 9000000
workforce +=  agriculture
agricultureFirms = 10000000



# 0-9 in test-ff starts from 0, accepting firms with 0 employees, 1.6 is the calculated mean of the class
numberOfFirms = sbs['From 0 to 9 persons employed'].sum() /1.6\
              + sbs['From 10 to 19 persons employed'].sum() / 13.45\
              + sbs['From 20 to 49 persons employed'].sum() / 30.2\
              + sbs['From 50 to 249 persons employed'].sum() / 98.8\
              + sbs['250 persons employed or more'].sum() / 1144.3\
              + agricultureFirms 

numberOfFirms = int(numberOfFirms)
(workforce-agriculture, agriculture,numberOfFirms)

(162420089.319, 9000000, 42241114)

<span style="color: DodgerBlue;">
==============================================================================================  
    
### Share calculation for agriculture, using compensation of employees, but in this case it would be also possible to use the whole added value
==============================================================================================  
</span>

In [13]:
agric_tot = (mini_naio['Compensation of employees'].loc[1] \
               + mini_naio['Compensation of employees'].loc[2]\
               + mini_naio['Compensation of employees'].loc[3])

agricultureSectorWeight = mini_naio['Compensation of employees'].loc[1]/ agric_tot 
silvicultureSectorWeight = mini_naio['Compensation of employees'].loc[2]/ agric_tot
fishingSectorWeight = mini_naio['Compensation of employees'].loc[3]/ agric_tot

# agriculture
share = (agricultureFirms/numberOfFirms) * mini_naio['Compensation of employees'].loc[1]/ agric_tot \
                                    * mini_naio['Consumption good share'].loc[1]
ff.loc[0] = [1, "Agriculture", "C", "From 0 to 9 persons employed", share, agricultureSectorWeight, np.nan]

share = (agricultureFirms/numberOfFirms) * mini_naio['Compensation of employees'].loc[1]/ agric_tot \
                                    * mini_naio['Investment good share'].loc[1]
ff.loc[1] = [1,"Agriculture", "I", "From 0 to 9 persons employed", share, agricultureSectorWeight, np.nan]

share = (agricultureFirms/numberOfFirms) * mini_naio['Compensation of employees'].loc[1]/ agric_tot \
                                    * mini_naio['Intermediate good share'].loc[1]
ff.loc[2] = [1, "Agriculture", "Int", "From 0 to 9 persons employed", share, agricultureSectorWeight, np.nan]

# silviculture
share = (agricultureFirms/numberOfFirms) * mini_naio['Compensation of employees'].loc[2]/ agric_tot \
                                    * mini_naio['Consumption good share'].loc[2]
ff.loc[3] = [2, "Silviculture", "C", "From 0 to 9 persons employed", share, silvicultureSectorWeight, np.nan]

share = (agricultureFirms/numberOfFirms) * mini_naio['Compensation of employees'].loc[2]/ agric_tot \
                                    * mini_naio['Investment good share'].loc[2]
ff.loc[4] = [2, "Silviculture", "I", "From 0 to 9 persons employed", share, silvicultureSectorWeight, np.nan]

share = (agricultureFirms/numberOfFirms) * mini_naio['Compensation of employees'].loc[2]/ agric_tot \
                                    * mini_naio['Intermediate good share'].loc[2]
ff.loc[5] = [2, "Silviculture", "Int", "From 0 to 9 persons employed", share, silvicultureSectorWeight, np.nan]

# fishing (no investments, but with the row anyway)
share = (agricultureFirms/numberOfFirms) * mini_naio['Compensation of employees'].loc[3]/ agric_tot\
                                    * mini_naio['Consumption good share'].loc[3]              
ff.loc[6] = [3, "Fishing", "C", "From 0 to 9 persons employed", share, fishingSectorWeight, np.nan]

share = (agricultureFirms/numberOfFirms) * mini_naio['Compensation of employees'].loc[3]/ agric_tot\
                                    * mini_naio['Investment good share'].loc[3]              
ff.loc[7] = [3, "Fishing", "I", "From 0 to 9 persons employed", share, fishingSectorWeight, np.nan]

share = (agricultureFirms/numberOfFirms) * mini_naio['Compensation of employees'].loc[3]/ agric_tot\
                                    * mini_naio['Intermediate good share'].loc[3]               
ff.loc[8] = [3, "Fishing", "Int", "From 0 to 9 persons employed", share, fishingSectorWeight, np.nan]

print("****************", numberOfFirms)

**************** 42241114

In the following cell, we compute  the share of firms per each row of the firm-feature file that we are generating (each row describes the specification of the NACE sector, the type of good it produces &mdash; consumption, investment, intermediate &mdash; and its dimensional class in terms of number of employees).
We calculate the share as the ratio between number of firms of the sector (estimated through the number of workers per dimensional class in standard cases, with some exception, e.g. agriculture) and the total number of firms; whereas we decompose consumptions, investments, and intermediate goods by using the Compensations of employees.

<span style="color: DodgerBlue;">
==============================================================================================  
    
### Share calculation by sectors and dimensions
### The function shareCalculation() uses the Compensation of employees as wheights

### Problem: the case of Real estate services with a super high capital intensity with Compensation of employees reprensenting only the 5% of the Added value, gross (ff rows 609-639)

### Also in this case, employees compensations give a reasonable dimension of the firms' number; the recipe, very huge, states the correct amount of capital

==============================================================================================  
</span>

In [14]:
def shareCalculation(ffRow,miniNaioRow, miniNaioRange, naceDef,sbsRow):
    global numberOfFirms
    
    totalCompensationPerSector = sum(list(mini_naio['Compensation of employees'].loc[i] for i in miniNaioRange))
    sectorWeight = mini_naio['Compensation of employees'].loc[miniNaioRow] / totalCompensationPerSector
    
    

    share = sectorWeight * (sbs['From 0 to 9 persons employed'][sbsRow] / 1.6) / numberOfFirms * mini_naio['Consumption good share'].loc[miniNaioRow]
    ff.loc[ffRow] = [miniNaioRow, naceDef, "C", "From 0 to 9 persons employed", share, sectorWeight, sbsRow]

    share = sectorWeight * (sbs['From 10 to 19 persons employed'][sbsRow] / 13.45) / numberOfFirms * mini_naio['Consumption good share'].loc[miniNaioRow]
    ff.loc[ffRow+1] = [miniNaioRow, naceDef, "C", "From 10 to 19 persons employed", share, sectorWeight, sbsRow]

    share = sectorWeight * (sbs['From 20 to 49 persons employed'][sbsRow] / 30.2) / numberOfFirms * mini_naio['Consumption good share'].loc[miniNaioRow]
    ff.loc[ffRow+2] = [miniNaioRow, naceDef, "C", "From 20 to 49 persons employed", share, sectorWeight, sbsRow]

    share = sectorWeight * (sbs['From 50 to 249 persons employed'][sbsRow] / 98.8) / numberOfFirms * mini_naio['Consumption good share'].loc[miniNaioRow]
    ff.loc[ffRow+3] = [miniNaioRow, naceDef, "C", "From 50 to 249 persons employed", share, sectorWeight, sbsRow]

    share = sectorWeight * (sbs['250 persons employed or more'][sbsRow] / 1144.3) / numberOfFirms * mini_naio['Consumption good share'].loc[miniNaioRow]
    ff.loc[ffRow+4] = [miniNaioRow, naceDef, "C", "250 persons employed or more", share, sectorWeight, sbsRow]

    share = sectorWeight * (sbs['From 0 to 9 persons employed'][sbsRow] / 1.6) / numberOfFirms * mini_naio['Investment good share'].loc[miniNaioRow]
    ff.loc[ffRow+5] = [miniNaioRow, naceDef, "I", "From 0 to 9 persons employed", share, sectorWeight, sbsRow]
    
    share = sectorWeight * (sbs['From 10 to 19 persons employed'][sbsRow] / 13.45) / numberOfFirms * mini_naio['Investment good share'].loc[miniNaioRow]
    ff.loc[ffRow+6] = [miniNaioRow, naceDef, "I", "From 10 to 19 persons employed", share, sectorWeight, sbsRow]

    share = sectorWeight * (sbs['From 20 to 49 persons employed'][sbsRow] / 30.2) / numberOfFirms * mini_naio['Investment good share'].loc[miniNaioRow]
    ff.loc[ffRow+7] = [miniNaioRow, naceDef, "I", "From 20 to 49 persons employed", share, sectorWeight, sbsRow]

    share = sectorWeight * (sbs['From 50 to 249 persons employed'][sbsRow] / 98.8) / numberOfFirms * mini_naio['Investment good share'].loc[miniNaioRow]
    ff.loc[ffRow+8] = [miniNaioRow, naceDef, "I", "From 50 to 249 persons employed", share, sectorWeight, sbsRow]

    share = sectorWeight * (sbs['250 persons employed or more'][sbsRow] / 1144.3) / numberOfFirms * mini_naio['Investment good share'].loc[miniNaioRow]
    ff.loc[ffRow+9] = [miniNaioRow, naceDef, "I", "250 persons employed or more", share, sectorWeight, sbsRow]

    share = sectorWeight * (sbs['From 0 to 9 persons employed'][sbsRow] / 1.6) / numberOfFirms * mini_naio['Intermediate good share'].loc[miniNaioRow]
    ff.loc[ffRow+10] = [miniNaioRow, naceDef, "Int", "From 0 to 9 persons employed", share, sectorWeight, sbsRow]
    
    share = sectorWeight * (sbs['From 10 to 19 persons employed'][sbsRow] / 13.45) / numberOfFirms * mini_naio['Intermediate good share'].loc[miniNaioRow]
    ff.loc[ffRow+11] = [miniNaioRow, naceDef, "Int", "From 10 to 19 persons employed", share, sectorWeight, sbsRow]

    share = sectorWeight * (sbs['From 20 to 49 persons employed'][sbsRow] / 30.2) / numberOfFirms * mini_naio['Intermediate good share'].loc[miniNaioRow]
    ff.loc[ffRow+12] = [miniNaioRow, naceDef, "Int", "From 20 to 49 persons employed", share, sectorWeight, sbsRow]

    share = sectorWeight * (sbs['From 50 to 249 persons employed'][sbsRow] / 98.8) / numberOfFirms * mini_naio['Intermediate good share'].loc[miniNaioRow]
    ff.loc[ffRow+13] = [miniNaioRow, naceDef, "Int", "From 50 to 249 persons employed", share, sectorWeight, sbsRow]

    share = sectorWeight * (sbs['250 persons employed or more'][sbsRow] / 1144.3) / numberOfFirms * mini_naio['Intermediate good share'].loc[miniNaioRow]
    ff.loc[ffRow+14] = [miniNaioRow, naceDef, "Int", "250 persons employed or more", share, sectorWeight, sbsRow]

In [15]:
r=9

shareCalculation(r, 4, [4], mini_naio.iloc[4,0],0)
r=r+15

for i in range(5,24):
     shareCalculation(r + (i-5) * 15, i, range(5,24), mini_naio.iloc[i,0],1)
r=r+15*(24-5)

shareCalculation(r,24, [24],mini_naio.iloc[24,0],2)
r=r+15

for i in range(25,27):
     shareCalculation(r + (i-25) * 15, i, range(25,27), mini_naio.iloc[i,0],3)
r=r+15*(27-25)

shareCalculation(r,27, [27], mini_naio.iloc[27,0],4)
r=r+15

for i in range(28,31):
     shareCalculation(r + (i-28) * 15, i,range(28,31),mini_naio.iloc[i,0],5)
r=r+15*(31-28)

for i in range(31,36):
     shareCalculation(r + (i-31) * 15, i, range(31,36),mini_naio.iloc[i,0],6)
r=r+15*(36-31)

shareCalculation(r,36, [36], mini_naio.iloc[36,0],7)
r=r+15

for i in range(37,41):
     shareCalculation(r + (i-37) * 15, i, range(37,41),mini_naio.iloc[i,0],8)
r=r+15*(41-37)

for i in range(41,44):
     shareCalculation(r + (i-41) * 15, i, range(41,44),mini_naio.iloc[i,0],9)
r=r+15*(44-41)

for i in range(44,46):
     shareCalculation(r + (i-44) * 15, i, range(44,46),mini_naio.iloc[i,0],10)
r=r+15*(46-44)

for i in range(46,51):
     shareCalculation(r + (i-46) * 15, i, range(46,51),mini_naio.iloc[i,0],11)
r=r+15*(51-46)

for i in range(51,56):
     shareCalculation(r + (i-51) * 15, i, range(51,56),mini_naio.iloc[i,0],12)
r=r+15*(56-51)

shareCalculation(r,56, [56], mini_naio.iloc[56,0],13)
r=r+15

for i in range(57,59):
     shareCalculation(r + (i-57) * 15, i, range(57,59),mini_naio.iloc[i,0],14)
r=r+15*(59-57)

for i in range(59,61):
     shareCalculation(r + (i-59) * 15, i, range(59,61),mini_naio.iloc[i,0],15)
r=r+15*(61-59)


# using here range(61,65) instead of range(61,66) to exclude the last row sector 65 whose NaN produces 
# a NaN result also for the weight of the other sectors of the same group, being NaN the sum of the 
# Compensations of employees
for i in range(61,65):
     shareCalculation(r + (i-61) * 15, i, range(61,65),mini_naio.iloc[i,0],16) # using 16, the artificial row

print("****************", numberOfFirms)

**************** 42241114

In [16]:
pd.set_option('display.float_format', '{:.10f}'.format)
pd.set_option("display.max_rows", None)
#pd.set_option("display.max_rows", 100)

In [17]:

ff["Share of firms"].sum()

np.float64(1.0000000196582512)

old firmFeatures
"share of firms of that class, L min, L max, K min, K max, order duration min, order duration max, recipe, L prod, max order production, assets' useful life, planned markup, order observation frequency min, order observation frequency max, production type"

<span style="color: DodgerBlue;">
==============================================================================================  
    
### Dimensional class limits from sbs, plus the option for the open class, see above

==============================================================================================  
</span>

In [18]:
#L min & L max

#the interval will generate a random uniform number r to be corrected with math.ceil(r)
#in this way, e.g., the interval [0;1[ will produce 1, ..., that [8;9[ will produce 9

ff["L min"]=0
ff["L min"]=np.where(ff["dimensional class"]=="From 0 to 9 persons employed",0,ff["L min"])
ff["L min"]=np.where(ff["dimensional class"]=="From 10 to 19 persons employed",10,ff["L min"])
ff["L min"]=np.where(ff["dimensional class"]=="From 20 to 49 persons employed",20,ff["L min"])
ff["L min"]=np.where(ff["dimensional class"]=="From 50 to 249 persons employed",50,ff["L min"])
ff["L min"]=np.where(ff["dimensional class"]=="250 persons employed or more",250,ff["L min"])

ff["L max"]=0
ff["L max"]=np.where(ff["dimensional class"]=="From 0 to 9 persons employed",9,ff["L max"])
ff["L max"]=np.where(ff["dimensional class"]=="From 10 to 19 persons employed",19,ff["L max"])
ff["L max"]=np.where(ff["dimensional class"]=="From 20 to 49 persons employed",49,ff["L max"])
ff["L max"]=np.where(ff["dimensional class"]=="From 50 to 249 persons employed",249,ff["L max"])
ff["L max"]=np.where(ff["dimensional class"]=="250 persons employed or more",1850,ff["L max"])

# when considering agriculture we must achieve the total number of 19 mln of workers 
# i.e. 10 mln of agricultural firms on 20 mln of firms - eurostat
# assumption of agricultural firms on istat and eurostat data, this justifies L max = 3
# while for the other sectors we consider the avg values of each dimensional class

ff.loc[:8, "L max"] = 2

#reading ff into the simulation code, the case "L max" == 3 will be elaborated in the following special way

<span style="color: DodgerBlue;">
==============================================================================================  
    
### Agriculture case

==============================================================================================  
</span>

we have 10,000,000 firms and 9,000,000 workers,
being $x_1$ the # of firms with 0 worker, $x_2$ that of firms with 1 workers, $x_3$ that of firms with 2 workers

$0 x_1 + 1 x_2 + 2 x_3 = 9,000,000$

$x_1 + x_2 + x_3  = 10,000,000$

if $x_3 = 1,000,000$

$0 x_1 + 1 x_2 = 7,000,000$

$  x_1 +   x_2 = 9,000,000$


giving

$x_2 = 7,000,000$

$x_1 = 2,000,000$

<span style="color: DodgerBlue;">
==============================================================================================  
    
### Firms in absolute numbers and new column of correct row totals, named 'Total2'

==============================================================================================  
</span>

In [19]:
ff['Firms in absolute numbers'] = ff['Share of firms'] * numberOfFirms 
# European data in real world -> CAVEAT: != number of firms in the model

In [20]:
# eliminating nan
ff["Share of firms per sbs sector"]         = np.where(pd.isna(ff["Share of firms per sbs sector"]),
                                               0,
                                               ff["Share of firms per sbs sector"])
ff["Firms in absolute numbers"]             = np.where(pd.isna(ff["Firms in absolute numbers"]),
                                               0,
                                               ff["Firms in absolute numbers"])

### now onwards drafts and controls

In [21]:
#Eliminating NaN in sbs
sbs.loc[ 3,"250 persons employed or more"]=0
sbs.loc[ 9,"250 persons employed or more"]=0
sbs.loc[10,"250 persons employed or more"]=0

sbs['Total'].sum()

157115769

In [22]:
sbs['Total2']=sbs['From 0 to 9 persons employed']+\
sbs['From 10 to 19 persons employed']+\
sbs['From 20 to 49 persons employed']+\
sbs['From 50 to 249 persons employed']+\
sbs['250 persons employed or more']

In [23]:
sbs['Total2'].sum()

162420089.31900004

In [24]:
# check number of firm in agriculture


# how to filter one single sector or group of sectors
#ff[ff['#'].isin([1,2,3])]
#ff[ff['#'].isin([4])]

ff[ff['#'].isin([1,2,3])]["Firms in absolute numbers"].sum()
#rememember ff[ ~ ff['#'].isin([1,2,3])]["Firms in absolute numbers"].sum()

np.float64(10000000.0)

<span style="color: DodgerBlue;">
==============================================================================================  
    
### Capital stocks 

==============================================================================================  
</span>

## computing capital quantity for ff

To assess the quantity of capital our starting point is the Appendix B of Priori, Terna _et al._ (2025). There, we roughly state the following relation.

To set a proportion, e.g., of $\frac{1}{2}$ and $\frac{1}{2}$ for the global compensations of labor and productive capital, we need a recipe $\frac{K}{L}$ with, in a time unit:

$\frac{Kr}{n}=Lw$

$K=\frac{Lwn}{r}$

with $w=1$, $L=1$, $n=12$, $r=0.10$, we obtain $K=120$. 

In real life a proportion of $120$ to $1$ between the productive capital per worker and the monthly compensation of a worker is not unrealistic.



We looked for some confirmation of this intuition in real data. Unfortunately, Eurostat data does not provide data on non-financial capital stocks, so we had to look for this information in Istat data:
- http://dati.istat.it/Index.aspx?QueryId=37156 here there are data on gross and net non-fin capital stocks and depreciations for NACE sectors
- http://dati.istat.it/Index.aspx?QueryId=12581 here there are data on occupation by sector in Italy
- we update occupational data with the LC table, to incorporate information on labor cost (even if this reflects values fo EU and not only for Italy - data not available).

In particular we look for some confirmation of this intuition by observing two examples (Manifacturing, which is a labor-intensive sector, and Coke, petrol, chemistry and farmaceutical, which is a capital-intensive one). 
- non-fin capital stock for manifacturing is 485.357.000.000 whereas the occupational data is 3.972.000. So its ratio is about 120.000.
- non-fin capital stock for chemistry and others is about 60.000.000.000 (28.859.300.000 + 30.830.800.000 because they are classified as separate sectors, i.e., coke and petrol vs. chemistry and farmaceutical) and its occupational data (here classified as an aggregate sector) is 195.000. So the furthcoming ratio is about 300.000.

Since we are considering a monthly compensation of one unit of labor at the labor cost of $1$ to a value of capital equal to $120$, we need to account for annual compensation of workers per sector (reported in LC table).

Then, the value of 120 is about ten times the annual compensation of workers, in the same way in that the ratio 300.000 is ten times the LC annual compensation of workers of 32.000 for coke, petrol, chemistry and farmaceutical (being considered as a sub-sector of manifacturing in the LC table). As far as concerns the whole manifacturing sector the value are close but not perfect beacuse we need to consider a higher capital compensation $r$. 

This makes perfectly sense as manifacture can be considered as a "light" sector where capital can obtain higher compensation per unit rather than coke, petrol, chemistry and farmaceutical, being a heavy sector with lower capital compensation per unit.

<span style="color: DodgerBlue;">
==============================================================================================  
    
### Capital stocks from Italian data

==============================================================================================  
</span>

In [25]:
cap_stocks = pd.read_excel("capital_stocks_istat_net.xlsx", sheet_name=0) #we use only year 2016 (the last with full entries)
# keeep in mind that these units are to be intended as MLN (ie x1.000.000) :)

cap_stocks = cap_stocks.drop(cap_stocks.index[0:9])
cap_stocks = pd.DataFrame([cap_stocks.iloc[:,0],cap_stocks['Unnamed: 7']])
cap_stocks = cap_stocks.T
cap_stocks.columns = ['NACE sector', 'Net cap stock' ]
cap_stocks = cap_stocks.drop(cap_stocks.index[-1])

pd.set_option('display.max_colwidth', None)
pd.options.display.float_format = '{:.1f}'.format

cap_stocks = cap_stocks.reset_index(drop=True)
cap_stocks = cap_stocks.drop(cap_stocks.index[[0,2,3,5,22,23,27,33,34,39,42,45]]) 
cap_stocks = cap_stocks.reset_index(drop=True)


cap_stocks

,NACE sector,Net cap stock
0,"agricoltura, silvicoltura e pesca",195224.8
1,industria estrattiva,25443.0
2,"industrie alimentari, delle bevande e del tabacco",52385.8
3,"industrie tessili, confezione di articoli di abbigliamento e di articoli in pelle e simili",28422.4
4,"industria del legno, della carta, editoria",26381.0
5,fabbricazione di coke e prodotti derivanti dalla raffinazione del petrolio,28859.3
6,fabbricazione di prodotti chimici,30830.8
7,fabbricazione di prodotti farmaceutici di base e di preparati farmaceutici,16492.1
8,fabbricazione di articoli in gomma e materie plastiche e altri prodotti della lavorazione di minerali non metalliferi,49167.6
9,"attività metallurgiche e fabbricazione di prodotti in metallo, esclusi macchinari e attrezzature",72391.5
10,fabbricazione di computer e prodotti di elettronica e ottica,18982.7
11,fabbricazione di apparecchiature elettriche,18650.5
12,fabbricazione di macchinari e apparecchiature n.c.a.,47207.2
13,fabbricazione di mezzi di trasporto,50360.4
14,"fabbricazione di mobili, altre industrie manifatturiere, riparazione e installazione di macchine e apparecchiature",30972.9
15,"fornitura di energia elettrica, gas, vapore e aria condizionata",211853.1
16,"fornitura di acqua, reti fognarie, attività di trattamento dei rifiuti e risanamento",53701.3
17,costruzioni,66883.9
18,"commercio all'ingrosso e al dettaglio, riparazione di autoveicoli e motocicli",174198.2
19,trasporti e magazzinaggio,377986.2
20,servizi di alloggio e di ristorazione,98590.2
21,"attività editoriali, audiovisivi, attività di trasmissione",17932.6
22,telecomunicazioni,49301.4
23,"programmazione, consulenza informatica e attività connesse, attività dei servizi d'informazione",27683.5
24,attività finanziarie e assicurative,87154.9
25,attività immobiliari,3026702.9
26,"attività legali e contabilità, attività di sedi centrali, consulenza gestionale, attività degli studi di architettura e d'ingegneria, collaudi e analisi tecniche",29129.7
27,ricerca scientifica e sviluppo,13759.3
28,"pubblicità e ricerche di mercato, altre attività professionali, scientifiche e tecniche, servizi veterinari",12081.6
29,attività amministrative e di servizi di supporto,66265.7
30,"amministrazione pubblica e difesa, assicurazione sociale obbligatoria",586775.5
31,istruzione,37761.3
32,attività dei servizi sanitari,74718.7
33,assistenza sociale,12546.3
34,"attività artistiche, di intrattenimento e divertimento",36495.9
35,altre attività di servizi,23344.6
36,"attività di famiglie e convivenze come datori di lavoro per personale domestico, produzione di beni e servizi indifferenziati per uso proprio da parte di famiglie e convivenze",0.0

<span style="color: DodgerBlue;">
==============================================================================================  
    
### Consistent employees number from Italian data

==============================================================================================  
</span>

In [26]:
employed = pd.read_excel("occupati_istat.xlsx", sheet_name=0)
# here units represent THOUSANDS (x1.000)

employed = employed.drop(employed.index[0:8])
employed = pd.DataFrame([employed.iloc[:,0],employed['Unnamed: 5']])
employed = employed.T
employed.columns = ['NACE sector', 'employed' ]

employed = employed.drop(employed.index[-1])
employed = employed.drop(employed.index[-1])
employed = employed.drop(employed.index[-1])

pd.set_option('display.max_colwidth', None)
pd.options.display.float_format = '{:.1f}'.format

employed = employed.reset_index(drop=True)
employed = employed.drop(employed.index[[0,2,3,5,15]]) 
# some rows contain aggr values of successive observations, we drop them
employed = employed.reset_index(drop=True) 

employed_num = employed['employed']

employed

,NACE sector,employed
0,"agricoltura, silvicoltura e pesca",922.8
1,industria estrattiva,18.6
2,"industrie alimentari, delle bevande e del tabacco",491.3
3,"industrie tessili, abbigliamento, cuoio, calzature, industria del legno, della carta, editoria",706.7
4,"fabbricazione di coke e prodotti derivanti dalla raffinazione del petrolio, fabbricazione di prodotti chimici e farmaceutici",196.1
5,"fabbricazione di articoli in gomma e materie plastiche e altri prodotti di minerali non metalliferi, attività metallurgiche e fabbricazione di prodotti in metallo, esclusi macchinari",1078.3
6,"fabbricazione di computer e prodotti di elettronica e ottica, fabbricazione di apparecchiature elettriche, fabbricazione di macchinari e apparecchiature n.c.a",758.7
7,fabbricazione di mezzi di trasporto,270.4
8,"fabbricazione di mobili, altre industrie manifatturiere, riparazione e installazione di macchine e apparecchiature",449.1
9,"fornitura di energia elettrica, gas, vapore e aria condizionata, fornitura di acqua, reti fognarie, attività di trattamento dei rifiuti e risanamento",326.3
10,costruzioni,1780.3
11,"commercio all'ingrosso e al dettaglio, riparazione di autoveicoli e motocicli, trasporto e magazzinaggio, servizi di alloggio e di ristorazione",6733.7
12,servizi di informazione e comunicazione,704.9
13,attività finanziarie e assicurative,628.4
14,attività immobiliari,187.2
15,"attività professionali, scientifiche e tecniche, amministrazione e servizi di supporto",3494.5
16,"amministrazione pubblica e difesa, assicurazione sociale obbligatoria, istruzione, sanità e assistenza sociale",5030.7
17,"attività artistiche, di intrattenimento e divertimento, riparazione di beni per la casa e altri servizi",2400.5

<span style="color: DodgerBlue;">
==============================================================================================  
    
### millions of euros divided by thousands of employees => the recipes are in thousands of euros 
### and the same the capital

==============================================================================================  
</span>

In [27]:
ff['Recipe'] = 0
ff['Recipe']=ff['Recipe'].astype(float) # to avoid a 64bit warning that will raise an error in 
                                        # future versions of pandas

ff.iloc[0:9, ff.columns.get_loc('Recipe')] = cap_stocks.iloc[0,1] / employed_num.iloc[0]
ff.iloc[9:24, ff.columns.get_loc('Recipe')] = cap_stocks.iloc[1,1] / employed_num.iloc[1]
ff.iloc[24:39, ff.columns.get_loc('Recipe')] = cap_stocks.iloc[2,1] / employed_num.iloc[2]

ff.iloc[39:54, ff.columns.get_loc('Recipe')] = (cap_stocks.iloc[3,1] + cap_stocks.iloc[4,1]) / employed_num.iloc[3]
ff.iloc[54:69, ff.columns.get_loc('Recipe')] = (cap_stocks.iloc[3,1] + cap_stocks.iloc[4,1]) / employed_num.iloc[3]
ff.iloc[69:84, ff.columns.get_loc('Recipe')] = (cap_stocks.iloc[3,1] + cap_stocks.iloc[4,1]) / employed_num.iloc[3]
ff.iloc[84:99, ff.columns.get_loc('Recipe')] = (cap_stocks.iloc[3,1] + cap_stocks.iloc[4,1]) / employed_num.iloc[3]

ff.iloc[99:114, ff.columns.get_loc('Recipe')] = \
                (cap_stocks.iloc[5,1] + cap_stocks.iloc[6,1] + cap_stocks.iloc[7,1]) / employed_num.iloc[4]
ff.iloc[114:129, ff.columns.get_loc('Recipe')] =\
                (cap_stocks.iloc[5,1] + cap_stocks.iloc[6,1] + cap_stocks.iloc[7,1]) / employed_num.iloc[4]
ff.iloc[129:144, ff.columns.get_loc('Recipe')] = \
                (cap_stocks.iloc[5,1] + cap_stocks.iloc[6,1] + cap_stocks.iloc[7,1]) / employed_num.iloc[4]

ff.iloc[144:159, ff.columns.get_loc('Recipe')] = (cap_stocks.iloc[8,1] + cap_stocks.iloc[9,1]) / employed_num.iloc[5]
ff.iloc[159:174, ff.columns.get_loc('Recipe')] = (cap_stocks.iloc[8,1] + cap_stocks.iloc[9,1]) / employed_num.iloc[5]
ff.iloc[174:189, ff.columns.get_loc('Recipe')] = (cap_stocks.iloc[8,1] + cap_stocks.iloc[9,1]) / employed_num.iloc[5]
ff.iloc[189:204, ff.columns.get_loc('Recipe')] = (cap_stocks.iloc[8,1] + cap_stocks.iloc[9,1]) / employed_num.iloc[5]

ff.iloc[204:219, ff.columns.get_loc('Recipe')] = \
                (cap_stocks.iloc[10,1] + cap_stocks.iloc[11,1] + cap_stocks.iloc[12,1]) / employed_num.iloc[6]
ff.iloc[219:234, ff.columns.get_loc('Recipe')] = \
                (cap_stocks.iloc[10,1] + cap_stocks.iloc[11,1] + cap_stocks.iloc[12,1]) / employed_num.iloc[6]
ff.iloc[234:249, ff.columns.get_loc('Recipe')] = \
                (cap_stocks.iloc[10,1] + cap_stocks.iloc[11,1] + cap_stocks.iloc[12,1]) / employed_num.iloc[6]

ff.iloc[249:264, ff.columns.get_loc('Recipe')] = cap_stocks.iloc[13,1] / employed_num.iloc[7]
ff.iloc[264:279, ff.columns.get_loc('Recipe')] = cap_stocks.iloc[13,1] / employed_num.iloc[7]

ff.iloc[279:294, ff.columns.get_loc('Recipe')] = cap_stocks.iloc[14,1] / employed_num.iloc[8]
ff.iloc[294:309, ff.columns.get_loc('Recipe')] = cap_stocks.iloc[14,1] / employed_num.iloc[8]

ff.iloc[309:324, ff.columns.get_loc('Recipe')] = (cap_stocks.iloc[15,1] + cap_stocks.iloc[16,1]) / employed_num.iloc[9]
ff.iloc[324:339, ff.columns.get_loc('Recipe')] = (cap_stocks.iloc[15,1] + cap_stocks.iloc[16,1]) / employed_num.iloc[9]
ff.iloc[339:354, ff.columns.get_loc('Recipe')] = (cap_stocks.iloc[15,1] + cap_stocks.iloc[16,1]) / employed_num.iloc[9]

ff.iloc[354:369, ff.columns.get_loc('Recipe')] = cap_stocks.iloc[17,1] / employed_num.iloc[10]

ff.iloc[369:504, ff.columns.get_loc('Recipe')] = \
                (cap_stocks.iloc[18,1] + cap_stocks.iloc[19,1] + cap_stocks.iloc[20,1]) / employed_num.iloc[11]


ff.iloc[504:564, ff.columns.get_loc('Recipe')] = \
                (cap_stocks.iloc[21,1] + cap_stocks.iloc[22,1] + cap_stocks.iloc[23,1]) / employed_num.iloc[12]

ff.iloc[564:609, ff.columns.get_loc('Recipe')] = cap_stocks.iloc[24,1] / employed_num.iloc[13]

ff.iloc[609:639, ff.columns.get_loc('Recipe')] = cap_stocks.iloc[25,1] / employed_num.iloc[14]

ff.iloc[639:774, ff.columns.get_loc('Recipe')] = (cap_stocks.iloc[28,1] + cap_stocks.iloc[29,1]) / employed_num.iloc[15]

ff.iloc[774:834, ff.columns.get_loc('Recipe')] = (cap_stocks.iloc[30,1] + \
                cap_stocks.iloc[31,1] + cap_stocks.iloc[32,1] + cap_stocks.iloc[33,1]) / employed_num.iloc[16]

ff.iloc[834:909, ff.columns.get_loc('Recipe')] =\
                (cap_stocks.iloc[34,1] + cap_stocks.iloc[35,1] + cap_stocks.iloc[36,1]) / employed_num.iloc[17]

# 909 -939 have no capital stocks and then have recipe 0

In [28]:
ff['K min'] = ff['L min'] * ff['Recipe']
ff['K min'] = np.where(ff['L min'] == 0, ff['Recipe'] * 1, ff['L min'] * ff['Recipe']) # to consider at least Lmin=1
ff['K max'] = ff['L max'] * ff['Recipe']

<span style="color: DodgerBlue;">
==============================================================================================  
    
### Cost of Capital, considering a risk free rent value 
### Drastically reduced for the sector of Real estate services with a super high capital intensity 
### with Compensation of employees reprensenting the 5% of the Added value, gross

==============================================================================================  
</span>

In [29]:
ff['Cost of capital'] = 0.15
ff.iloc[609:624, ff.columns.get_loc('Cost of capital')] = 0.0 #imputer rents in naio has VA 0
ff.iloc[624:639, ff.columns.get_loc('Cost of capital')] = 0.03 #real estate need to compensate out of scale recipes
ff['Cost of capital'] = ff['Cost of capital'].apply(lambda x: format(x, '.2f'))

<span style="color: DodgerBlue;">
==============================================================================================  
    
### Wages
###  
### using Compensations of employees and sbs number of Employees

==============================================================================================  
</span>

In [30]:
ff['Wage'] = 0
ff['Wage']=ff['Wage'].astype(float) # to avoid a 64bit warning that will raise an error in 
                                        # future versions of pandas


ff.iloc[0:9, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[1:3].sum() * 1e6 / agriculture
ff.iloc[9:24, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[4]*1e6 / sbs['Total2'].loc[0]
ff.iloc[24:39, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[5:23].sum() * 1e6 /sbs['Total2'].loc[1]
ff.iloc[39:54, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[5:23].sum() * 1e6 /sbs['Total2'].loc[1]                                      
ff.iloc[54:69, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[5:23].sum() * 1e6 /sbs['Total2'].loc[1]    
ff.iloc[69:84, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[5:23].sum() * 1e6 /sbs['Total2'].loc[1]
ff.iloc[84:99, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[5:23].sum() * 1e6 /sbs['Total2'].loc[1]
ff.iloc[99:114, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[5:23].sum() * 1e6 /sbs['Total2'].loc[1]
ff.iloc[114:129, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[5:23].sum() * 1e6 / sbs['Total2'].loc[1]
ff.iloc[129:144, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[5:23].sum() * 1e6 / sbs['Total2'].loc[1]
ff.iloc[144:159, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[5:23].sum() * 1e6 / sbs['Total2'].loc[1]
ff.iloc[159:174, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[5:23].sum() * 1e6 / sbs['Total2'].loc[1]
ff.iloc[174:189, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[5:23].sum() * 1e6 / sbs['Total2'].loc[1]
ff.iloc[189:204, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[5:23].sum() * 1e6 / sbs['Total2'].loc[1]
ff.iloc[204:219, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[5:23].sum() * 1e6 / sbs['Total2'].loc[1]
ff.iloc[219:234, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[5:23].sum() * 1e6 / sbs['Total2'].loc[1]
ff.iloc[234:249, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[5:23].sum() * 1e6 / sbs['Total2'].loc[1]
ff.iloc[249:264, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[5:23].sum() * 1e6 / sbs['Total2'].loc[1]
ff.iloc[264:279, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[5:23].sum() * 1e6 / sbs['Total2'].loc[1]
ff.iloc[279:294, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[5:23].sum() * 1e6 / sbs['Total2'].loc[1]
ff.iloc[294:309, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[5:23].sum() * 1e6 / sbs['Total2'].loc[1]
ff.iloc[309:324, ff.columns.get_loc('Wage')] =  mini_naio['Compensation of employees'].loc[24] * 1e6 / sbs['Total2'].loc[2]                                  
ff.iloc[324:339, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[25:26].sum() * 1e6 /sbs['Total2'].loc[3]
ff.iloc[339:354, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[25:26].sum() * 1e6 /sbs['Total2'].loc[3]
ff.iloc[354:369, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[27] * 1e6 /sbs['Total2'].loc[4]
ff.iloc[369:384, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[28:30].sum() * 1e6 /sbs['Total2'].loc[5]
ff.iloc[384:399, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[28:30].sum() * 1e6 /sbs['Total2'].loc[5]
ff.iloc[399:414, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[28:30].sum() * 1e6 /sbs['Total2'].loc[5]
ff.iloc[414:429, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[31:35].sum() * 1e6 /sbs['Total2'].loc[6]
ff.iloc[429:444, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[31:35].sum() * 1e6 /sbs['Total2'].loc[6]
ff.iloc[444:459, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[31:35].sum() * 1e6 /sbs['Total2'].loc[6]
ff.iloc[459:474, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[31:35].sum() * 1e6 /sbs['Total2'].loc[6]
ff.iloc[474:489, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[31:35].sum() * 1e6 /sbs['Total2'].loc[6]
ff.iloc[489:504, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[36] * 1e6 /sbs['Total2'].loc[7]
ff.iloc[504:519, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[37:40].sum() * 1e6 /sbs['Total2'].loc[8]
ff.iloc[519:534, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[37:40].sum() * 1e6 /sbs['Total2'].loc[8]
ff.iloc[534:549, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[37:40].sum() * 1e6 /sbs['Total2'].loc[8]
ff.iloc[549:564, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[37:40].sum() * 1e6 /sbs['Total2'].loc[8]
ff.iloc[564:579, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[41:43].sum() * 1e6 /sbs['Total2'].loc[9]
ff.iloc[579:594, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[41:43].sum() * 1e6 /sbs['Total2'].loc[9]
ff.iloc[594:609, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[41:43].sum() * 1e6 /sbs['Total2'].loc[9]
ff.iloc[609:624, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[44:45].sum() * 1e6 /sbs['Total2'].loc[10]
ff.iloc[624:639, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[44:45].sum() * 1e6 /sbs['Total2'].loc[10]
ff.iloc[639:654, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[46:50].sum() * 1e6 /sbs['Total2'].loc[11]
ff.iloc[654:669, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[46:50].sum() * 1e6 /sbs['Total2'].loc[11]
ff.iloc[669:684, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[46:50].sum() * 1e6 /sbs['Total2'].loc[11]
ff.iloc[684:699, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[46:50].sum() * 1e6 /sbs['Total2'].loc[11]
ff.iloc[699:714, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[46:50].sum() * 1e6 /sbs['Total2'].loc[11]
ff.iloc[714:729, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[51:55].sum() * 1e6 /sbs['Total2'].loc[12]
ff.iloc[729:744, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[51:55].sum() * 1e6 /sbs['Total2'].loc[12]
ff.iloc[744:759, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[51:55].sum() * 1e6 /sbs['Total2'].loc[12]
ff.iloc[759:774, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[51:55].sum() * 1e6 /sbs['Total2'].loc[12]
ff.iloc[774:789, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[51:55].sum() * 1e6 /sbs['Total2'].loc[12]
ff.iloc[789:804, ff.columns.get_loc('Wage')]= mini_naio['Compensation of employees'].loc[56] * 1e6 /sbs['Total2'].loc[13]
ff.iloc[804:819, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[57:58].sum() * 1e6 /sbs['Total2'].loc[14]
ff.iloc[819:834, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[57:58].sum() * 1e6 /sbs['Total2'].loc[14]
ff.iloc[834:849, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[59:60].sum() * 1e6 /sbs['Total2'].loc[15]
ff.iloc[849:864, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[59:60].sum() * 1e6 /sbs['Total2'].loc[15]
ff.iloc[864:879, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[61:64].sum() * 1e6 /sbs['Total2'].loc[16]
ff.iloc[879:894, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[61:64].sum() * 1e6 /sbs['Total2'].loc[16] 
ff.iloc[894:909, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[61:64].sum() * 1e6 /sbs['Total2'].loc[16] 
ff.iloc[909:924, ff.columns.get_loc('Wage')] = mini_naio['Compensation of employees'].loc[61:64].sum() * 1e6 /sbs['Total2'].loc[16] 
ff.iloc[924:939, ff.columns.get_loc('Wage')] = 0 #mini_naio['Compensation of employees'].loc[65]  is nan


#ff

In [31]:
mini_naio['Compensation of employees'].loc[1:65].sum()

np.float64(7447036.8)

<span style="color: DodgerBlue;">
==============================================================================================  
    
### display a few rows of the ff table, for control purposes

==============================================================================================  
</span>

In [32]:
#pd.set_option('display.float_format', '{:.5f}'.format)
ff[ff['#'].isin([65])]

Empty DataFrame
Columns: [#, NACE definition, type, dimensional class, Share of firms, Share of firms per sbs sector, sbs reference row, L min, L max, Firms in absolute numbers, Recipe, K min, K max, Cost of capital, Wage]
Index: []

<span style="color: DodgerBlue;">
==============================================================================================  
    
### intermediate inputs (calculations made by intermediate65x65.ipynb)

==============================================================================================  
</span>

In [160]:
pd.set_option('display.precision', 20)
naio_io = pd.read_pickle('naio_io.xp') #shares

In [161]:
naio_io

,Sectors,"1_Crop and animal production, hunting and related service activities",2_Forestry and logging,3_Fishing and aquaculture,4_Mining and quarrying,5_Manufacture of food products; beverages and tobacco products,"6_Manufacture of textiles, wearing apparel, leather and related products","7_Manufacture of wood and of products of wood and cork, except furniture; manufacture of articles of straw and plaiting materials",8_Manufacture of paper and paper products,9_Printing and reproduction of recorded media,10_Manufacture of coke and refined petroleum products,11_Manufacture of chemicals and chemical products,12_Manufacture of basic pharmaceutical products and pharmaceutical preparations,13_Manufacture of rubber and plastic products,14_Manufacture of other non-metallic mineral products,15_Manufacture of basic metals,"16_Manufacture of fabricated metal products, except machinery and equipment","17_Manufacture of computer, electronic and optical products",18_Manufacture of electrical equipment,19_Manufacture of machinery and equipment n.e.c.,"20_Manufacture of motor vehicles, trailers and semi-trailers",21_Manufacture of other transport equipment,22_Manufacture of furniture; other manufacturing,23_Repair and installation of machinery and equipment,"24_Electricity, gas, steam and air conditioning supply","25_Water collection, treatment and supply","26_Sewerage, waste management, remediation activities",27_Construction,28_Wholesale and retail trade and repair of motor vehicles and motorcycles,"29_Wholesale trade, except of motor vehicles and motorcycles","30_Retail trade, except of motor vehicles and motorcycles",31_Land transport and transport via pipelines,32_Water transport,33_Air transport,34_Warehousing and support activities for transportation,35_Postal and courier activities,36_Accommodation and food service activities,37_Publishing activities,"38_Motion picture, video, television programme production; programming and broadcasting activities",39_Telecommunications,"40_Computer programming, consultancy, and information service activities","41_Financial service activities, except insurance and pension funding","42_Insurance, reinsurance and pension funding, except compulsory social security",43_Activities auxiliary to financial services and insurance activities,44_Imputed rents of owner-occupied dwellings,45_Real estate activities excluding imputed rents,46_Legal and accounting activities; activities of head offices; management consultancy activities,47_Architectural and engineering activities; technical testing and analysis,48_Scientific research and development,49_Advertising and market research,"50_Other professional, scientific and technical activities; veterinary activities",51_Rental and leasing activities,52_Employment activities,"53_Travel agency, tour operator reservation service and related activities","54_Security and investigation, service and landscape, office administrative and support activities",55_Public administration and defence; compulsory social security,56_Education,57_Human health activities,58_Residential care activities and social work activities without accommodation,"59_Creative, arts and entertainment activities; libraries, archives, museums and other cultural activities; gambling and betting activities",60_Sports activities and amusement and recreation activities,61_Activities of membership organisations,62_Repair of computers and personal and household goods,63_Other personal service activities,64_Activities of households as employers; undifferentiated goods- and services-producing activities of households for own use,65_Activities of extraterritorial organisations and bodies
1,"Products of agriculture, hunting and related services",0.2867,0.0260,0.0081,0.0004,0.9398,0.0553,0.0010,0.0017,0.0001,0.0003,0.0177,0.0064,0.0176,0.0008,0.0002,0.0003,0.0006,0.0003,0.0002,0.0001,0.0001,0.0012,0.0001,0.0017,0.0007,0.0006,0.0005,0.0001,0.0095,0.0037,0.0003,0.0014,0.0001,0.0002,0.0001,0.0337,0.0000,0.0005,0.0000,0.0000,0.0000,0.0003,0.0000,NaN,0.0000,0.0001,0.0008,0.0016,0.0001,0.0024,0.0001,0.0000,0.0003,0.0129,0.0015,0.0006,0.0013,0.0024,0.0017,0.0050,0.0009,0.0002,0.0014,0.0000,NaN
2,"Products of forestry, logging and related services",0.0028,0.4927,0.0039,0.0011,0.0011,0.0002,0.3215,0.1074,0.0005,0.0002,0.0012,0.0001,0.0010,0.0003,0.0004,0.0001,0.0000,0.0000,0.0000,0.0000,0.0001,0.0086,0.0000,0.0030,0.0002,0.0001,0.0007,0.0001,0.0003,0.0001,0.0001,0.0000,0.0000,0.0000,0.0000,0.0001,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,0.0000,0.0000,0.0002,0.0001,0.0001,0.0001,0.0000,0.0000,0.0000,0.0005,0.0002,0.0000,0.0000,0.0000,0.0002,0.0005,0.0002,0.0003,0.0001,0.0000,NaN
3,Fish and other fishing products; aquaculture products; support services to fishing,0.0001,0.0002,0.0859,0.0000,0.0233,0.0001,0.0000,0.0000,0.0000,0.0000,0.0002,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0001,0.0000,0.0001,0.0000,0.0000,0.0001,0.0000,0.0001,0.0000,0.0000,0.0017,0.0000,0.0000,0.0000,0.0086,0.0000,0.0001,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0001,0.0002,0.0001,0.0001,0.0002,0.0000,0.0000,0.0000,NaN
4,Mining and quarrying,0.0049,0.0038,0.0079,0.1619,0.0093,0.0028,0.0009,0.0215,0.0014,6.3757,0.0629,0.0016,0.0042,0.1643,0.3507,0.0032,0.0004,0.0065,0.0030,0.0010,0.0024,0.0063,0.0013,0.1216,0.0046,0.0044,0.0208,0.0003,0.0016,0.0006,0.0016,0.0004,0.0004,0.0019,0.0004,0.0014,0.0001,0.0003,0.0002,0.0001,0.0001,0.0001,0.0002,NaN,0.0002,0.0005,0.0009,0.0004,0.0001,0.0003,0.0002,0.0001,0.0005,0.0018,0.0014,0.0002,0.0007,0.0007,0.0003,0.0011,0.0006,0.0007,0.0006,0.0000,NaN
5,"Food, beverages and tobacco products",0.2282,0.0034,0.1289,0.0048,0.8513,0.0307,0.0015,0.0140,0.0007,0.0611,0.0523,0.0191,0.0027,0.0033,0.0092,0.0008,0.0009,0.0011,0.0010,0.0007,0.0005,0.0057,0.0027,0.0033,0.0035,0.0086,0.0016,0.0027,0.0132,0.0097,0.0028,0.0246,0.0199,0.0031,0.0016,0.3225,0.0012,0.0087,0.0026,0.0019,0.0005,0.0013,0.0008,NaN,0.0003,0.0029,0.0029,0.0083,0.0065,0.0066,0.0040,0.0012,0.0039,0.0049,0.0077,0.0080,0.0188,0.0254,0.0057,0.0305,0.0130,0.0050,0.0033,0.0000,NaN
6,"Textiles, wearing apparel, leather and related products",0.0034,0.0035,0.0242,0.0021,0.0043,0.8109,0.0107,0.0397,0.0178,0.0089,0.0086,0.0034,0.0327,0.0075,0.0057,0.0042,0.0025,0.0044,0.0042,0.0281,0.0141,0.0513,0.0079,0.0010,0.0019,0.0052,0.0043,0.0037,0.0054,0.0040,0.0018,0.0070,0.0029,0.0021,0.0033,0.0064,0.0007,0.0181,0.0026,0.0007,0.0003,0.0005,0.0004,NaN,0.0005,0.0015,0.0022,0.0014,0.0025,0.0098,0.0021,0.0007,0.0018,0.0053,0.0025,0.0010,0.0079,0.0040,0.0044,0.0081,0.0026,0.0198,0.0068,0.0000,NaN
7,"Wood and of products of wood and cork, except furniture; articles of straw and plaiting materials",0.0071,0.0123,0.0123,0.0058,0.0104,0.0036,0.7610,0.0769,0.0046,0.0033,0.0062,0.0015,0.0079,0.0203,0.0108,0.0091,0.0018,0.0061,0.0056,0.0075,0.0223,0.1779,0.0057,0.0085,0.0009,0.0028,0.0549,0.0011,0.0029,0.0017,0.0023,0.0013,0.0006,0.0028,0.0006,0.0020,0.0012,0.0056,0.0018,0.0003,0.0001,0.0003,0.0003,NaN,0.0018,0.0005,0.0012,0.0005,0.0022,0.0025,0.0014,0.0002,0.0005,0.0058,0.0003,0.0005,0.0002,0.0004,0.0021,0.0022,0.0015,0.0108,0.0083,0.0000,NaN
8,Paper and paper products,0.0026,0.0019,0.0056,0.0036,0.0652,0.0168,0.0427,0.9432,0.3863,0.0068,0.0264,0.0186,0.0285,0.0223,0.0115,0.0077,0.0060,0.0169,0.0064,0.0044,0.0042,0.0250,0.0050,0.0028,0.0021,0.0078,0.0024,0.0030,0.0079,0.0066,0.0023,0.0028,0.0013,0.0046,0.0045,0.0060,0.0378,0.0184,0.0029,0.0025,0.0031,0.0046,0.0083,NaN,0.0006,0.0059,0.0072,0.0028,0.0151,0.0136,0.0028,0.0006,0.0131,0.0143,0.0023,0.0016,0.0023,0.0030,0.0045,0.0045,0.0045,0.0061,0.0023,0.0000,NaN
9,Printing and recording services,0.0004,0.0005,0.0017,0.0005,0.0053,0.0033,0.0020,0.0178,0.1610,0.0033,0.0037,0.0033,0.0046,0.0020,0.0028,0.0021,0.0013,0.0029,0.0030,0.0030,0.0018,0.0039,0.0035,0.0011,0.0015,0.0018,0.0007,0.0039,0.0038,0.0061,0.0015,0.0010,0.0018,0.0022,0.0095,0.0024,0.0636,0.0295,0.0085,0.0030,0.0046,0.0100,0.0127,NaN,0.0005,0.0051,0.0073,0.0068,0.0272,0.0165,0.0027,0.0014,0.0577,0.0114,0.0029,0.0022,0.0008,0.0028,0.0113,0.0119,0.0097,0.0036,0.0026,0.0000,NaN
10,Coke and refined petroleum products,0.0499,0.0304,0.1071,0.0301,0.0114,0.0054,0.0131,0.0134,0.0054,1.8408,0.1531,0.0032,0.0071,0.0518,0.0973,0.0060,0.0013,0.0067,0.0059,0.0056,0.0044,0.0088,0.0074,0.0360,0.0092,0.0256,0.0226,0.0107,0.0113,0.0061,0.1291,0.3460,0.5995,0.0220,0.0226,0.0045,0.0010,0.0067,0.0033,0.0021,0.0014,0.0060,0.0092,NaN,0.0007,0.0038,0.0045,0.0037,0.0065,0.0065,0.0095,0.0012,0.0080,0.0078,0.0061,0.0022,0.0026,0.0030,0.0049,0.0083,0.0060,0.0079,0.0055,0.0000,NaN
11,Chemicals and chemical products,0.1120,0.0108,0.0338,0.0260,0.0453,0.1402,0.1123,0.1722,0.0950,0.8258,0.9531,0.1545,0.6283,0.1013,0.1123,0.0415,0.0299,0.0674,0.0228,0.0507,0.0434,0.0610,0.0376,0.0281,0.0448,0.0195,0.0246,0.0123,0.0087,0.0037,0.0055,0.0044,0.0064,0.0031,0.0017,0.0056,0.0242,0.0108,0.0012,0.0013,0.0003,0.0007,0.0005,NaN,0.0019,0.0019,0.0048,0.0169,0.0048,0.0130,0.0027,0.0006,0.0018,0.0161,0.0021,0.0013,0.0200,0.0042,0.0036,0.0050,0.0038,0.0093,0.0230,0.0000,NaN
12,Basic pharmaceutical products and pharmaceutical preparations,0.0064,0.0000,0.0030,0.0000,0.0085,0.0002,0.0002,0.0002,0.0000,0.0004,0.0132,0.2165,0.0026,0.0009,0.0001,0.0000,0.0000,0.0000,0.0000,0.0001,0.0000,0.0015,0.0000,0.0000,0.0001,0.0003,0.0000,0.0000,0.0144,0.0002,0.0000,0.0001,0.0001,0.0001,0.0000,0.0003,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,0.0000,0.0003,0.0005,0.0059,0.0005,0.0170,0.0002,0.0000,0.0001,0.0011,0.0009,0.0008,0.0700,0.0094,0.0001,0.0003,0.0008,0.0000,0.0004,0.0000,NaN
13,Rubber and plastic products,0.0108,0.0031,0.0122,0.0074,0.0688,0.0432,0.0292,0.0575,0.0365,0.0876,0.0509,0.0319,0.4335,0.0409,0.0314,0.0364,0.0254,0.0961,0.0574,0.1626,0.0466,0.0654,0.0416,0.0043,0.0050,0.0154,0.0690,0.0282,0.0094,0.0090,0.0161,0.0055,0.0084,0.0056,0.0045,0.0056,0.0036,0.0054,0.0080,0.0019,0.0010,0.0024,0.0017,NaN,0.0012,0.0026,0.0091,0.0045,0.0126,0.0084,0.0044,0.0005,0.0049,0.0135,0.0012,0.0004,0.0046,0.0029,0.0032,0.0047,0.0024,0.0213,0.0050,0.0000,NaN
14,Other non-metallic mineral products,0.0075,0.0022,0.0097,0.0192,0.0239,0.0061,0.0388,0.0035,0.0023,0.0078,0.0162,0.0078,0.0204,0.3677,0.0515,0.0164,0.0096,0.0270,0.0089,0.0243,0.0224,0.0200,0.0116,0.0074,0.0092,0.0092,0.1505,0.0056,0.0031,0.0016,0.0024,0.0017,0.0013,0.0019,0.0003,0.0048,0.0002,0.0003,0.0019,0.0003,0.0001,0.0000,0.0002,NaN,0.0023,0.0007,0.0027,0.0036,0.0022,0.0029,0.0012,0.0003,0.0006,0.0064,0.0010,0.0006,0.0018,0.0006,0.0020,0.0024,0.0026,0.0067,0.0037,0.0000,NaN
15,Basic metals,0.0008,0.0011,0.0006,0.0093,0.0060,0.0039,0.0112,0.0104,0.0096,0.0322,0.0374,0.0053,0.0331,0.0434,2.1149,0.4392,0.0342,0.2701,0.1715,0.1784,0.1121,0.1071,0.1000,0.0053,0.0089,0.0334,0.0425,0.0043,0.0037,0.0010,0.0045,0.0008,0.0007,0.0035,0.0002,0.0001,0.0008,0.0014,0.0022,0.0007,0.0001,0.0000,0.0001,NaN,0.0007,0.0003,0.0082,0.0023,0.0032,0.0035,0.0017,0.0001,0.0000,0.0023,0.0003,0.0001,0.0024,0.0000,0.0006,0.0003,0.0002,0.0178,0.0011,0.0000,NaN
16,"Fabricated metal products, except machinery and equipment",0.0144,0.0068,0.0115,0.0206,0.0366,0.0203,0.0470,0.0206,0.0107,0.1069,0.0286,0.0073,0.0566,0.0347,0.2118,0.5315,0.0386,0.1409,0.2830,0.2548,0.2546,0.0820,0.1858,0.0151,0.0227,0.0322,0.1222,0.0160,0.0057,0.0025,0.0073,0.0104,0.0034,0.0084,0.0019,0.0048,0.0013,0.0026,0.0064,0.0020,0.0005,0.0009,0.0007,NaN,0.0019,0.0017,0.0110,0.0031,0.0121,0.0056,0.0089,0.0007,0.0030,0.0122,0.0047,0.0005,0.0011,0.0011,0.0039,0.0045,0.0020,0.0333,0.0032,0.0000,NaN
17,"Computer, electronic and optical products",0.0003,0.0006,0.0035,0.0012,0.0011,0.0007,0.0010,0.0020,0.0105,0.0121,0.0025,0.0051,0.0035,0.0048,0.0069,0.0081,0.3170,0.0945,0.0292,0.0406,0.1050,0.0246,0.0573,0.0090,0.0046,0.0022,0.0089,0.0032,0.0039,0.0021,0.0019,0.0024,0.0043,0.0026,0.0048,0.0020,0.0087,0.0352,0.0504,0.0214,0.0013,0.0026,0.0030,NaN,0.0004,0.0025,0.0129,0.0139,0.0065,0.0116,0.0031,0.0008,0.0017,0.0074,0.0028,0.0010,0.0058,0.0023,0.0071,0.0038,0.0030,0.0814,0.0015,0.0000,NaN
18,Electrical equipment,0.0019,0.0013,0.0052,0.0044,0.0028,0.0022,0.0031,0.0041,0.0028,0.0187,0.0050,0.0012,0.0079,0.0067,0.0292,0.0204,0.0723,0.5249,0.0795,0.1044,0.0875,0.0196,0.0680,0.0301,0.0089,0.0039,0.0526,0.0081,0.0041,0.0023,0.0044,0.0021,0.0033,0.0046,0.0027,0.0048,0.0008,0.0026,0.0210,0.0044,0.0002,0.0003,0.0007,NaN,0.0010,0.0023,0.0102,0.0046,0.0051,0.0034,0.0027,0.0003,0.0013,0.0053,0.0011,0.0004,0.0007,0.0007,0.0036,0.0031,0.0010,0.0409,0.0047,0.0000,NaN
19,Machinery and equipment n.e.c.,0.0121,0.0186,0.0118,0.0252,0.0137,0.0123,0.0117,0.0226,0.0179,0.0575,0.0106,0.0058,0.0230,0.0190,0.0551,0.0337,0.0235,0.0565,0.4657,0.1497,0.1706,0.0131,0.1587,0.0152,0.0253,0.0121,0.0314,0.0157,0.0031,0.0023,0.0036,0.0095,0.0041,0.0122,0.0030,0.0040,0.0012,0.0032,0.0076,0.0015,0.0007,0.0009,0.0004,NaN,0.0004,0.0018,0.0149,0.0054,0.0031,0.0044,0.0083,0.0004,0.0023,0.0042,0.0008,0.0002,0.0009,0.0010,0.0012,0.0020,0.0014,0.0189,0.0027,0.0000,NaN
20,"Motor vehicles, trailers and semi-trailers",0.0037,0.0034,0.0025,0.0014,0.0021,0.0008,0.0029,0.0005,0.0003,0.0090,0.0046,0.0000,0.0080,0.0114,0.0034,0.0080,0.0024,0.0223,0.0626,1.0414,0.0334,0.0031,0.0359,0.0012,0.0016,0.0136,0.0036,0.1290,0.0030,0.0020,0.0349,0.0030,0.0039,0.0092,0.0017,0.0005,0.0002,0.0020,0.0011,0.0003,0.0003,0.0002,0.0002,NaN,0.0001,0.0006,0.0013,0.0019,0.0015,0.0054,0.0052,0.0002,0.0023,0.0028,0.0007,0.0001,0.0003,0.0004,0.0007,0.0030,0.0014,0.0013,0.0005,0.0000,NaN
21,Other transport equipment,0.0002,0.0008,0.0099,0.0010,0.0001,0.0002,0.0003,0.0001,0.0002,0.0005,0.0001,0.0000,0.0017,0.0002,0.0006,0.0010,0.0034,0.0025,0.0009,0.0040,1.0608,0.0049,0.0787,0.0002,0.0000,0.0002,0.0005,0.0030,0.0007,0.0002,0.0100,0.0163,0.1545,0.0029,0.0001,0.0002,0.0000,0.0001,0.0001,0.0006,0.0000,0.0000,0.0000,NaN,0.0000,0.0000,0.0033,0.0007,0.0007,0.0023,0.0042,0.0000,0.0002,0.0009,0.0089,0.0000,0.0003,0.0001,0.0002,0.0017,0.0004,0.0012,0.0005,0.0000,NaN
22,Furniture and other manufactured goods,0.0013,0.0005,0.0037,0.0010,0.0026,0.0077,0.0103,0.0017,0.0021,0.0056,0.0033,0.0077,0.0027,0.0025,0.0056,0.0029,0.0110,0.0040,0.0032,0.0089,0.0078,0.1503,0.0127,0.0015,0.0014,0.0018,0.0079,0.0026,0.0023,0.0025,0.0016,0.0022,0.0023,0.0013,0.0009,0.0038,0.0009,0.0067,0.0017,0.0010,0.0009,0.0011,0.0013,NaN,0.0006,0.0014,0.0023,0.0028,0.0051,0.0089,0.0019,0.0004,0.0028,0.0032,0.0014,0.0013,0.0402,0.0059,0.0093,0.0133,0.0041,0.0118,0.0030,0.0000,NaN
23,Repair and installation services of machinery and equipment,0.0378,0.0132,0.0627,0.0547,0.0216,0.0168,0.0329,0.0456,0.0196,0.0986,0.0280,0.0070,0.0173,0.0344,0.0994,0.0271,0.0118,0.0280,0.0372,0.0412,0.1264,0.0168,0.1659,0.0254,0.0300,0.0199,0.0153,0.0100,0.0070,0.0049,0.0278,0.1051,0.2855,0.0150,0.0076,0.0055,0.0029,0.0063,0.0196,0.0036,0.0017,0.0024,0.0030,NaN,0.0047,0.0031,0.0054,0.0073,0.0041,0.0091,0.0127,0.0013,0.0085,0.0061,0.0080,0.0013,0.0068,0.0036,0.0052,0.0167,0.0028,0.0108,0.0048,0.0000,NaN
24,"Electricity, gas, steam and air conditioning",0.0507,0.0084,0.0388,0.1349,0.0818,0.0553,0.0907,0.1834,0.0546,0.4091,0.1314,0.0178,0.0882,0.1615,0.3950,0.0512,0.0164,0.0432,0.0231,0.0353,0.0255,0.0288,0.0146,0.9753,0.1477,0.0412,0.0112,0.0213,0.0175,0.0403,0.0489,0.0046,0.0185,0.0307,0.0234,0.0569,0.0078,0.0593,0.0482,0.0087,0.0072,0.0095,0.0062,NaN,0.0103,0.0112,0.0089,0.0179,0.0169,0.0175,0.0049,0.0025,0.0196,0.0122,0.0185,0.0139,0.0195,0.0216,0.0280,0.0534,0.0231,0.0169,0.0356,0.0001,NaN
25,Natural water; water treatment and supply services,0.0078,0.0010,0.0062,0.0032,0.0062,0.0027,0.0019,0.0060,0.0025,0.0143,0.0052,0.0012,0.0024,0.0037,0.0080,0.0025,0.0009,0.0017,0.0018,0.0016,0.0013,0.0014,0.0013,0.0027,0.1148,0.0165,0.0011,0.0012,0.0009,0.0018,0.0010,0.0007,0.0014,0.0015,0.0018,0.0072,0.0005,0.0057,0.0011,0.0004,0.0006,0.0010,0.0017,NaN,0.0016,0.0008,0.0008,0.0018,0.0008,0.0011,0.0005,0.0002,0.0031,0.0015,0.0025,0.0020,0.0027,0.0031,0.0028,0.0098,0.0034,0.0015,0.0041,0.0000,NaN
26,"Sewerage services; sewage sludge; waste collection, treatment and disposal services; materials recovery services; remediation services and other waste management services",0.0102,0.0024,0.0060,0.0419,0.0271,0.0278,0.0276,0.1292,0.0111,0.0935,0.0334,0.0066,0.0677,0.0416,0.4578,0.0416,0.0033,0.0098,0.0102,0.0100,0.0112,0.0108,0.0068,0.0137,0.1148,0.5666,0.0115,0.0060,0.0055,0.0075,0.0067,0.0090,0.0109,0.0058,0.0064,0.0115,0.0031,0.0074,0.0057,0.0036,0.0016,0.0029,0.0019,NaN,0.0057,0.0050,0.0048,0.0051,0.0085,0.0107,0.0037,0.0009,0.0072,0.0126,0.0224,0.0019,0.0056,0.0057,0.0054,0.0103,0.0051,0.0051,0.0077,0.0000,NaN
27,Constructions and construction works,0.0229,0.0237,0.0171,0.0295,0.0194,0.0153,0.0246,0.0228,0.0240,0.0902,0.0238,0.0245,0.0204,0.0296,0.0474,0.0186,0.0158,0.0203,0.0151,0.0143,0.0204,0.0137,0.0305,0.0720,0.0618,0.0841,0.5375,0.0118,0.0131,0.0146,0.0259,0.0119,0.0225,0.0629,0.0250,0.0213,0.0050,0.0261,0.0293,0.0070,0.0075,0.0186,0.0134,NaN,0.0782,0.0115,0.0433,0.0181,0.0153,0.0263,0.0094,0.0059,0.0157,0.0225,0.0390,0.0155,0.0160,0.0159,0.0260,0.0306,0.0281,0.0094,0.0098,0.0000,NaN
28,Wholesale and retail trade and repair services of motor vehicles and motorcycles,0.0121,0.0178,0.0355,0.0126,0.0093,0.0120,0.0171,0.0136,0.0181,0.0438,0.0086,0.0055,0.0129,0.0213,0.0172,0.0095,0.0066,0.0145,0.0219,0.2003,0.0472,0.0101,0.0209,0.0042,0.0171,0.0288,0.0100,0.0880,0.0106,0.0113,0.0639,0.0116,0.0300,0.0287,0.1217,0.0048,0.0052,0.0151,0.0100,0.0037,0.0023,0.0077,0.0068,NaN,0.0007,0.0047,0.0070,0.0065,0.0128,0.0136,0.0357,0.0029,0.0261,0.0078,0.0051,0.0017,0.0037,0.0040,0.0072,0.0105,0.0082,0.0207,0.0062,0.0000,NaN
29,"Wholesale trade services, except of motor vehicles and motorcycles",0.1177,0.0829,0.1038,0.0575,0.3788,0.2774,0.2722,0.2415,0.1307,0.7072,0.2192,0.1760,0.1952,0.2196,0.3524,0.1475,0.2581,0.2186,0.1958,0.1742,0.2159,0.2648,0.1652,0.0528,0.0497,0.0757,0.1335,0.0577,0.1784,0.0591,0.0332,0.0970,0.2190,0.0323,0.0196,0.1058,0.2804,0.0602,0.0543,0.1096,0.0056,0.0088,0.0459,NaN,0.0048,0.0217,0.0305,0.0282,0.0622,0.0514,0.0261,0.0046,0.1053,0.0463,0.0131,0.0082,0.0619,0.0238,0.0324,0.0365,0.0210,0.0882,0.0231,0.0000,NaN
30,"Retail trade services, except of motor vehicles and motorcycles",0.0420,0.0392,0.1217,0.0353,0.0975,0.0637,0.0731,0.0618,0.0754,0.1514,0.0432,0.0256,0.0518,0.0558,0.0650,0.0326,0.0461,0.0622,0.0330,0.0533,0.1154,0.0649,0.0460,0.0132,0.0353,0.0237,0.0265,0.0156,0.0069,0.0098,0.0161,0.0435,0.0711,0.0098,0.0293,0.0441,0.0161,0.0513,0.0215,0.0068,0.0046,0.0177,0.0124,NaN,0.0017,0.0056,0.0141,0.0187,0.0345,0.0347,0.0138,0.0068,0.0707,0.0133,0.0072,0.0051,0.0303,0.0228,0.0213,0.0228,0.0191,0.0753,0.0201,0.0001,NaN
31,Land transport services and transport services via pipelines,0.0250,0.0813,0.0231,0.0707,0.1248,0.0750,0.1238,0.1505,0.0384,1.2908,0.1048,0.0196,0.0902,0.1428,0.2425,0.0401,0.0256,0.0631,0.0435,0.0804,0.0480,0.0579,0.0260,0.0564,0.0090,0.0408,0.0320,0.0347,0.0987,0.0397,0.2793,0.0251,0.0238,0.2699,0.0815,0.0127,0.0174,0.0219,0.0096,0.0089,0.0027,0.0046,0.0084,NaN,0.0009,0.0059,0.0082,0.0113,0.0205,0.0121,0.0110,0.0017,0.2386,0.0085,0.0138,0.0160,0.0095,0.0076,0.0078,0.0126,0.0232,0.0214,0.0073,0.0000,NaN
32,Water transport services,0.0005,0.0054,0.0379,0.0079,0.0056,0.0029,0.0066,0.0084,0.0011,0.2264,0.0085,0.0019,0.0035,0.0075,0.0194,0.0029,0.0048,0.0046,0.0038,0.0043,0.0018,0.0020,0.0013,0.0035,0.0002,0.0015,0.0010,0.0026,0.0074,0.0008,0.0125,0.5463,0.0046,0.0184,0.0030,0.0005,0.0006,0.0004,0.0013,0.0004,0.0001,0.0001,0.0002,NaN,0.0000,0.0004,0.0004,0.0002,0.0010,0.0007,0.0011,0.0003,0.0490,0.0004,0.0003,0.0003,0.0004,0.0005,0.0003,0.0004,0.0004,0.0005,0.0002,0.0000,NaN

#### In test_ff and in model, load naio_io_N.xp which contains only the numerical part of the table, as a numpy array

<span style="color: DodgerBlue;">
==============================================================================================  
    
### corrections on AV

==============================================================================================  
</span>

We adjust ADDED VALUE items by using the ratio between simulated and actual values that we calculated in comparingActual&SimulatedData.ipynb.

In [35]:
compare = pd.read_pickle('./av_ratio_sim_act.xp')

"""
the structure of expanded_compare is:
row 1 => 3 rows 
row 2 => 3 rows
row 3 => 3 rows 
for Agricolture, Forestry, Phishing

then
row 4  => 15 rows
until 
row 64 => 15 rows
we dropped row 65, above

for globally 924 rows
"""

expanded1_compare = compare[0:3].repeat(3).reset_index(drop=True) # it multiplies by 3 each row of compare 
expanded2_compare = compare[3:64].repeat(15).reset_index(drop=True) # it multiplies by 15 each row of compare

In [36]:
#expanded1_compare

In [37]:
#expanded2_compare

In [38]:
expanded_compare = pd.concat([expanded1_compare.squeeze(), expanded2_compare.squeeze()], ignore_index=True)

In [39]:
#expanded_compare

In [40]:
ff['Wage'] = ff['Wage']/ expanded_compare

In [41]:
ff['K min'] =  ff['K min'] / expanded_compare

In [42]:
ff['K max']  = ff['K max'] / expanded_compare

In [43]:
ff['Recipe']  = ff['Recipe'] / expanded_compare

In [44]:
ff=ff.replace([np.inf,-np.inf],0)

## ff-output with labor and capital

In [45]:
ff.to_csv("ff_with_class_limits.csv",index=False)

In [46]:
ff[ff['#'].isin([44])]

,#,NACE definition,type,dimensional class,Share of firms,Share of firms per sbs sector,sbs reference row,L min,L max,Firms in absolute numbers,Recipe,K min,K max,Cost of capital,Wage
609,44,Imputed rents of owner-occupied dwellings,C,From 0 to 9 persons employed,NaN,0.0,10.0,0,9,0.0,0.0,0.0,0.0,0.00,0.0
610,44,Imputed rents of owner-occupied dwellings,C,From 10 to 19 persons employed,NaN,0.0,10.0,10,19,0.0,0.0,0.0,0.0,0.00,0.0
611,44,Imputed rents of owner-occupied dwellings,C,From 20 to 49 persons employed,NaN,0.0,10.0,20,49,0.0,0.0,0.0,0.0,0.00,0.0
612,44,Imputed rents of owner-occupied dwellings,C,From 50 to 249 persons employed,NaN,0.0,10.0,50,249,0.0,0.0,0.0,0.0,0.00,0.0
613,44,Imputed rents of owner-occupied dwellings,C,250 persons employed or more,NaN,0.0,10.0,250,1850,0.0,0.0,0.0,0.0,0.00,0.0
614,44,Imputed rents of owner-occupied dwellings,I,From 0 to 9 persons employed,NaN,0.0,10.0,0,9,0.0,0.0,0.0,0.0,0.00,0.0
615,44,Imputed rents of owner-occupied dwellings,I,From 10 to 19 persons employed,NaN,0.0,10.0,10,19,0.0,0.0,0.0,0.0,0.00,0.0
616,44,Imputed rents of owner-occupied dwellings,I,From 20 to 49 persons employed,NaN,0.0,10.0,20,49,0.0,0.0,0.0,0.0,0.00,0.0
617,44,Imputed rents of owner-occupied dwellings,I,From 50 to 249 persons employed,NaN,0.0,10.0,50,249,0.0,0.0,0.0,0.0,0.00,0.0
618,44,Imputed rents of owner-occupied dwellings,I,250 persons employed or more,NaN,0.0,10.0,250,1850,0.0,0.0,0.0,0.0,0.00,0.0
619,44,Imputed rents of owner-occupied dwellings,Int,From 0 to 9 persons employed,NaN,0.0,10.0,0,9,0.0,0.0,0.0,0.0,0.00,0.0
620,44,Imputed rents of owner-occupied dwellings,Int,From 10 to 19 persons employed,NaN,0.0,10.0,10,19,0.0,0.0,0.0,0.0,0.00,0.0
621,44,Imputed rents of owner-occupied dwellings,Int,From 20 to 49 persons employed,NaN,0.0,10.0,20,49,0.0,0.0,0.0,0.0,0.00,0.0
622,44,Imputed rents of owner-occupied dwellings,Int,From 50 to 249 persons employed,NaN,0.0,10.0,50,249,0.0,0.0,0.0,0.0,0.00,0.0
623,44,Imputed rents of owner-occupied dwellings,Int,250 persons employed or more,NaN,0.0,10.0,250,1850,0.0,0.0,0.0,0.0,0.00,0.0

<span style="color: DodgerBlue;">
==============================================================================================  
    
### Investments, start, a look to nama

==============================================================================================  
</span>

In [47]:
#pd.set_option('display.max_colwidth', None)

In [48]:
#nama

In [49]:
# swap rows and rows label# Positions to swap
i, j = 43, 44  # swap first and third row

# Swap row contents
temp = nama.iloc[i].copy()
nama.iloc[i] = nama.iloc[j]
nama.iloc[j] = temp

# Swap index labels
new_index = nama.index.tolist()
new_index[i], new_index[j] = new_index[j], new_index[i]
nama.index = new_index

In [50]:
#nama

In [51]:
#elimitaning negative values
nama[nama < 0] = 0

In [52]:
nama

,Row index,Dwellings,Other buildings,Transport equipment,Computer hardware,Telecommunications,Other machinery,Cultivated biological resources,R & D,Computer software and db
"Crop and animal production, hunting and related service activities",1,2.7,1404.1,964.8,53.1,16.2,3530.9,277.9,19.0,0.7
Forestry and logging,2,0.6,161.2,81.2,9.9,2.2,151.9,39.7,2.0,11.1
Fishing and aquaculture,3,0.0,33.3,240.3,0.2,0.1,136.3,0.0,6.9,0.5
Mining and quarrying,4,5.3,2792.9,228.4,83.6,623.6,1548.0,0.2,414.4,166.5
Manufacture of food products; beverages and tobacco products,5,7.3,5290.2,1908.7,319.6,333.1,12078.4,3.5,1003.6,1500.7
"Manufacture of textiles, wearing apparel, leather and related products",6,2.7,678.4,266.4,143.9,46.0,2794.8,0.0,991.6,702.7
"Manufacture of wood and of products of wood and cork, except furniture; manufacture of articles of straw and plaiting materials",7,1.5,203.1,63.0,17.9,5.2,440.1,7.4,3.8,9.3
Manufacture of paper and paper products,8,0.1,105.2,1.5,12.3,3.7,261.5,0.0,8.0,10.1
Printing and reproduction of recorded media,9,0.4,51.4,17.1,9.4,2.5,230.1,0.0,3.1,62.6
Manufacture of coke and refined petroleum products,10,0.0,397.8,97.9,28.9,19.2,1063.3,0.0,258.3,197.6
Manufacture of chemicals and chemical products,11,2.4,1888.3,858.5,230.6,183.8,6939.6,0.2,2067.0,786.5
Manufacture of basic pharmaceutical products and pharmaceutical preparations,12,1.3,2450.6,282.2,95.7,65.7,3344.1,0.1,2937.0,651.7
Manufacture of rubber and plastic products,13,0.9,301.8,60.8,37.3,11.3,762.8,1.7,92.1,17.5
Manufacture of other non-metallic mineral products,14,0.0,286.2,248.5,29.7,8.5,569.0,0.0,47.6,32.3
Manufacture of basic metals,15,2.3,205.0,9.1,19.3,5.8,475.3,0.0,32.3,34.2
"Manufacture of fabricated metal products, except machinery and equipment",16,4.7,363.1,65.1,86.0,25.8,1129.2,0.5,79.6,58.2
"Manufacture of computer, electronic and optical products",17,0.2,1088.3,230.6,487.4,193.6,2429.7,0.0,4765.2,2907.5
Manufacture of electrical equipment,18,0.0,537.2,126.9,435.3,133.0,2216.3,0.0,1811.8,663.6
Manufacture of machinery and equipment n.e.c.,19,16.1,1685.8,516.0,257.5,125.3,4443.7,0.0,3222.0,1627.0
"Manufacture of motor vehicles, trailers and semi-trailers",20,0.6,199.4,0.0,106.4,32.1,1234.1,0.0,478.6,85.2
Manufacture of other transport equipment,21,0.0,63.4,129.1,25.2,7.4,96.8,0.0,150.1,18.3
Manufacture of furniture; other manufacturing,22,1.1,643.5,46.4,19.9,6.1,268.0,0.0,21.1,34.4
Repair and installation of machinery and equipment,23,2.2,186.1,101.2,36.8,11.1,188.9,0.0,47.7,87.6
"Electricity, gas, steam and air conditioning supply",24,0.0,2897.4,68.6,121.8,53.0,2502.0,0.1,35.2,248.6
"Water collection, treatment and supply",25,0.6,1125.0,85.7,4.0,1.2,134.5,0.0,2.4,54.0
"Sewerage, waste management, remediation activities",26,0.3,1543.8,280.8,21.4,4.9,305.5,0.0,9.6,13.0
Construction,27,3920.4,14363.1,8731.5,638.7,648.6,12817.3,0.4,459.4,2003.0
Wholesale and retail trade and repair of motor vehicles and motorcycles,28,10.2,185.9,1112.1,3.9,0.9,49.3,0.0,3.1,37.0
"Wholesale trade, except of motor vehicles and motorcycles",29,34.3,1060.9,630.0,164.5,46.6,1657.5,0.3,182.6,287.2
"Retail trade, except of motor vehicles and motorcycles",30,23.4,1556.2,403.1,91.1,24.2,993.8,0.1,6.6,400.4
Land transport and transport via pipelines,31,0.0,998.9,3258.1,16.3,3.3,324.6,0.2,16.7,146.7
Water transport,32,0.0,128.4,839.7,0.0,0.0,0.0,0.0,0.0,18.9
Air transport,33,0.0,105.2,884.1,1.7,3.6,200.1,0.0,7.2,7.3
Warehousing and support activities for transportation,34,11.4,4465.1,419.5,80.1,37.9,533.9,0.0,16.5,126.5
Postal and courier activities,35,5.3,33.9,33.0,32.5,1.9,94.9,0.0,3.7,18.0
Accommodation and food service activities,36,35.6,12610.8,2410.7,660.3,701.7,7211.0,2.5,18.4,857.8
Publishing activities,37,0.1,123.7,23.8,6.5,1.5,12.2,0.0,37.3,384.4
"Motion picture, video, television programme production; programming and broadcasting activities",38,2.4,16.7,24.5,8.7,4.4,125.2,0.0,3.9,150.9
Telecommunications,39,0.3,8425.6,2754.8,1079.4,4438.0,6749.2,0.0,780.2,9197.9
"Computer programming, consultancy, and information service activities",40,30.4,2315.3,989.0,1099.5,508.4,2178.5,0.0,3203.3,14830.6
"Financial service activities, except insurance and pension funding",41,44.6,1662.4,1809.3,70.6,21.2,261.6,0.0,114.2,1255.8
"Insurance, reinsurance and pension funding, except compulsory social security",42,8.2,21.4,0.0,13.7,3.8,14.9,0.0,12.1,137.0
Activities auxiliary to financial services and insurance activities,43,0.4,60.2,0.0,15.7,4.8,21.2,0.0,2.7,85.1
Imputed rents of owner-occupied dwellings,45,134269.9,20335.4,459.4,75.9,153.4,1705.0,15.1,23.1,229.6
Real estate activities,44,17805.0,51.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Legal and accounting activities; activities of head offices; management consultancy activities,46,19.7,176.6,68.8,20.0,5.0,441.0,0.3,39.0,181.0
Architectural and engineering activities; technical testing and analysis,47,21.1,285.7,88.3,19.4,6.9,252.7,0.0,98.4,142.0
Scientific research and development,48,0.9,1558.2,103.3,82.7,206.4,1639.9,0.0,27339.1,1585.8
Advertising and market research,49,6.3,46.3,22.1,4.3,0.9,108.5,0.0,13.7,95.2
"Other professional, scientific and technical activities; veterinary activities",50,15.5,189.2,0.0,23.1,6.0,153.0,0.0,8.7,94.0
Rental and leasing activities,51,9.8,90.4,12924.9,14.3,4.3,440.5,2.1,8.9,29.9
Employment activities,52,0.0,14.3,16.6,1.6,0.6,13.4,0.0,0.1,10.9
"Travel agency, tour operator and other reservation service and related activities",53,6.1,6.6,6.0,1.1,0.3,0.0,0.0,1.0,17.1
"Security and investigation, service and landscape, office administrative and support activities",54,1.9,213.4,190.0,20.1,6.1,159.1,0.1,7.0,116.4
Public administration and defence; compulsory social security,55,137.4,11297.9,576.2,82.8,24.2,2436.1,1.4,227.4,607.3
Education,56,27.6,1492.4,43.7,56.3,15.7,473.2,0.2,1822.3,117.9
Human health activities,57,7.2,9424.2,974.5,518.2,378.1,9903.1,0.0,1480.4,1208.0
Residential care activities and social work activities without accommodation,58,58.9,5066.5,660.6,257.4,27.1,2176.8,0.1,17.6,384.9
"Creative, arts and entertainment activities; libraries, archives, museums and other cultural activities; gambling and betting activities",59,5.2,519.8,22.6,12.6,4.1,216.8,0.2,58.7,56.8
Sports activities and amusement and recreation activities,60,1.0,455.7,45.6,6.8,6.0,144.1,0.0,1.3,7.2
Activities of membership organisations,61,9.6,292.1,22.6,2.0,0.5,51.9,0.2,11.0,24.8
Repair of computers and personal and household goods,62,0.0,18.6,48.8,11.5,3.4,26.1,0.0,1.0,14.0
Other personal service activities,63,0.9,54.1,44.5,3.8,1.2,76.2,0.0,0.0,1.2
Activities of households as employers; undifferentiated goods- and services-producing activities of households for own use,64,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Activities of extraterritorial organisations and bodies,65,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [53]:
# total inv. from naio 3320258.70
nama.iloc[:,1:].sum()

Dwellings                         156584.3
Other buildings                   126304.7
Transport equipment                47620.5
Computer hardware                   7890.2
Telecommunications                  9221.4
Other machinery                   102937.4
Cultivated biological resources      354.5
R & D                              54536.6
Computer software and db           44849.9
dtype: float64

In [54]:
nama.iloc[:,1:].sum().sum()

np.float64(550299.5)

<span style="color: DodgerBlue;">
==============================================================================================  
    
### create investment table, basic version with shares (no nama)

==============================================================================================  
</span>

In [55]:
subset_index = mini_naio.index[1:66]

invTable=pd.DataFrame(index=subset_index,dtype='float64')
invTable[mini_naio['IND_USE (Labels)']]=0.0
invTable.rename(columns={'Total': 'sectors'}, inplace=True)

In [56]:
invTable['sectors']=nama.index.tolist()

In [57]:
invTable

,sectors,"Products of agriculture, hunting and related services","Products of forestry, logging and related services",Fish and other fishing products; aquaculture products; support services to fishing,Mining and quarrying,"Food, beverages and tobacco products","Textiles, wearing apparel, leather and related products","Wood and of products of wood and cork, except furniture; articles of straw and plaiting materials",Paper and paper products,Printing and recording services,Coke and refined petroleum products,Chemicals and chemical products,Basic pharmaceutical products and pharmaceutical preparations,Rubber and plastic products,Other non-metallic mineral products,Basic metals,"Fabricated metal products, except machinery and equipment","Computer, electronic and optical products",Electrical equipment,Machinery and equipment n.e.c.,"Motor vehicles, trailers and semi-trailers",Other transport equipment,Furniture and other manufactured goods,Repair and installation services of machinery and equipment,"Electricity, gas, steam and air conditioning",Natural water; water treatment and supply services,"Sewerage services; sewage sludge; waste collection, treatment and disposal services; materials recovery services; remediation services and other waste management services",Constructions and construction works,Wholesale and retail trade and repair services of motor vehicles and motorcycles,"Wholesale trade services, except of motor vehicles and motorcycles","Retail trade services, except of motor vehicles and motorcycles",Land transport services and transport services via pipelines,Water transport services,Air transport services,Warehousing and support services for transportation,Postal and courier services,Accommodation and food services,Publishing services,"Motion picture, video and television programme production services, sound recording and music publishing; programming and broadcasting services",Telecommunications services,"Computer programming, consultancy and related services; Information services","Financial services, except insurance and pension funding","Insurance, reinsurance and pension funding services, except compulsory social security",Services auxiliary to financial services and insurance services,Imputed rents of owner-occupied dwellings,Real estate services excluding imputed rents,Legal and accounting services; services of head offices; management consultancy services,Architectural and engineering services; technical testing and analysis services,Scientific research and development services,Advertising and market research services,"Other professional, scientific and technical services and veterinary services",Rental and leasing services,Employment services,"Travel agency, tour operator and other reservation services and related services","Security and investigation services; services to buildings and landscape; office administrative, office support and other business support services",Public administration and defence services; compulsory social security services,Education services,Human health services,Residential care services; social work services without accommodation,"Creative, arts, entertainment, library, archive, museum, other cultural services; gambling and betting services",Sporting services and amusement and recreation services,Services furnished by membership organisations,Repair services of computers and personal and household goods,Other personal services,Services of households as employers; undifferentiated goods and services produced by households for own use,Services provided by extraterritorial organisations and bodies
1,"Crop and animal production, hunting and related service activities",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Forestry and logging,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Fishing and aquaculture,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Mining and quarrying,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,Manufacture of food products; beverages and tobacco products,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,"Manufacture of textiles, wearing apparel, leather and related products",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,"Manufacture of wood and of products of wood and cork, except furniture; manufacture of articles of straw and plaiting materials",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,Manufacture of paper and paper products,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,Printing and reproduction of recorded media,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,Manufacture of coke and refined petroleum products,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,Manufacture of chemicals and chemical products,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,Manufacture of basic pharmaceutical products and pharmaceutical preparations,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,Manufacture of rubber and plastic products,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,Manufacture of other non-metallic mineral products,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,Manufacture of basic metals,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,"Manufacture of fabricated metal products, except machinery and equipment",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,"Manufacture of computer, electronic and optical products",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,Manufacture of electrical equipment,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,Manufacture of machinery and equipment n.e.c.,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,"Manufacture of motor vehicles, trailers and semi-trailers",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,Manufacture of other transport equipment,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,Manufacture of furniture; other manufacturing,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,Repair and installation of machinery and equipment,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,"Electricity, gas, steam and air conditioning supply",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,"Water collection, treatment and supply",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,"Sewerage, waste management, remediation activities",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,Construction,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,Wholesale and retail trade and repair of motor vehicles and motorcycles,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,"Wholesale trade, except of motor vehicles and motorcycles",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30,"Retail trade, except of motor vehicles and motorcycles",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31,Land transport and transport via pipelines,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32,Water transport,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
33,Air transport,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34,Warehousing and support activities for transportation,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35,Postal and courier activities,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36,Accommodation and food service activities,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37,Publishing activities,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38,"Motion picture, video, television programme production; programming and broadcasting activities",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39,Telecommunications,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
40,"Computer programming, consultancy, and information service activities",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41,"Financial service activities, except insurance and pension funding",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
42,"Insurance, reinsurance and pension funding, except compulsory social security",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
43,Activities auxiliary to financial services and insurance activities,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44,Imputed rents of owner-occupied dwellings,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45,Real estate activities,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
46,Legal and accounting activities; activities of head offices; management consultancy activities,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
47,Architectural and engineering activities; technical testing and analysis,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
48,Scientific research and development,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49,Advertising and market research,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
50,"Other professional, scientific and technical activities; veterinary activities",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
51,Rental and leasing activities,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
52,Employment activities,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [58]:
GrossFixedCapitalFormation = mini_naio['Gross fixed capital formation'][1:67].to_list()

In [59]:
GrossFixedCapitalFormation

[7444.62,
 456.39,
 56.16,
 1268.44,
 0.55,
 1603.87,
 9296.21,
 0.52,
 5.73,
 0.0,
 40.98,
 0.36,
 3960.68,
 7048.47,
 3327.25,
 70248.18,
 99794.45,
 48148.64,
 237529.45,
 166506.4,
 101785.37,
 47797.81,
 86048.8,
 263.9,
 10.92,
 55.88,
 1310617.3,
 32635.51,
 106583.15,
 32345.85,
 19378.02,
 1652.6,
 1640.49,
 514.58,
 0.0,
 418.81,
 42452.65,
 14855.89,
 0.0,
 295165.6,
 57.03,
 2611.9,
 1166.4,
 0.0,
 38782.86,
 39242.12,
 92446.33,
 368159.24,
 6.95,
 84.08,
 2569.35,
 148.03,
 171.3,
 11822.25,
 4105.41,
 153.41,
 8.2,
 9.13,
 4323.31,
 9.3,
 8.44,
 3397.31,
 7.41,
 0.07,
 8.38]

In [60]:
tot = sum(GrossFixedCapitalFormation)
tot

3320258.6900000004

In [61]:
shares = [sect / tot for sect in GrossFixedCapitalFormation]

In [62]:
tot2 = sum(shares) 
tot2

0.9999999999999999

In [63]:
invTable.iloc[:,1:66] = shares[0:65]

In [64]:
pd.options.display.float_format = '{:.4f}'.format
invTable

,sectors,"Products of agriculture, hunting and related services","Products of forestry, logging and related services",Fish and other fishing products; aquaculture products; support services to fishing,Mining and quarrying,"Food, beverages and tobacco products","Textiles, wearing apparel, leather and related products","Wood and of products of wood and cork, except furniture; articles of straw and plaiting materials",Paper and paper products,Printing and recording services,Coke and refined petroleum products,Chemicals and chemical products,Basic pharmaceutical products and pharmaceutical preparations,Rubber and plastic products,Other non-metallic mineral products,Basic metals,"Fabricated metal products, except machinery and equipment","Computer, electronic and optical products",Electrical equipment,Machinery and equipment n.e.c.,"Motor vehicles, trailers and semi-trailers",Other transport equipment,Furniture and other manufactured goods,Repair and installation services of machinery and equipment,"Electricity, gas, steam and air conditioning",Natural water; water treatment and supply services,"Sewerage services; sewage sludge; waste collection, treatment and disposal services; materials recovery services; remediation services and other waste management services",Constructions and construction works,Wholesale and retail trade and repair services of motor vehicles and motorcycles,"Wholesale trade services, except of motor vehicles and motorcycles","Retail trade services, except of motor vehicles and motorcycles",Land transport services and transport services via pipelines,Water transport services,Air transport services,Warehousing and support services for transportation,Postal and courier services,Accommodation and food services,Publishing services,"Motion picture, video and television programme production services, sound recording and music publishing; programming and broadcasting services",Telecommunications services,"Computer programming, consultancy and related services; Information services","Financial services, except insurance and pension funding","Insurance, reinsurance and pension funding services, except compulsory social security",Services auxiliary to financial services and insurance services,Imputed rents of owner-occupied dwellings,Real estate services excluding imputed rents,Legal and accounting services; services of head offices; management consultancy services,Architectural and engineering services; technical testing and analysis services,Scientific research and development services,Advertising and market research services,"Other professional, scientific and technical services and veterinary services",Rental and leasing services,Employment services,"Travel agency, tour operator and other reservation services and related services","Security and investigation services; services to buildings and landscape; office administrative, office support and other business support services",Public administration and defence services; compulsory social security services,Education services,Human health services,Residential care services; social work services without accommodation,"Creative, arts, entertainment, library, archive, museum, other cultural services; gambling and betting services",Sporting services and amusement and recreation services,Services furnished by membership organisations,Repair services of computers and personal and household goods,Other personal services,Services of households as employers; undifferentiated goods and services produced by households for own use,Services provided by extraterritorial organisations and bodies
1,"Crop and animal production, hunting and related service activities",0.0022,0.0001,0.0000,0.0004,0.0000,0.0005,0.0028,0.0000,0.0000,0.0000,0.0000,0.0000,0.0012,0.0021,0.0010,0.0212,0.0301,0.0145,0.0715,0.0501,0.0307,0.0144,0.0259,0.0001,0.0000,0.0000,0.3947,0.0098,0.0321,0.0097,0.0058,0.0005,0.0005,0.0002,0.0000,0.0001,0.0128,0.0045,0.0000,0.0889,0.0000,0.0008,0.0004,0.0000,0.0117,0.0118,0.0278,0.1109,0.0000,0.0000,0.0008,0.0000,0.0001,0.0036,0.0012,0.0000,0.0000,0.0000,0.0013,0.0000,0.0000,0.0010,0.0000,0.0000,0.0000
2,Forestry and logging,0.0022,0.0001,0.0000,0.0004,0.0000,0.0005,0.0028,0.0000,0.0000,0.0000,0.0000,0.0000,0.0012,0.0021,0.0010,0.0212,0.0301,0.0145,0.0715,0.0501,0.0307,0.0144,0.0259,0.0001,0.0000,0.0000,0.3947,0.0098,0.0321,0.0097,0.0058,0.0005,0.0005,0.0002,0.0000,0.0001,0.0128,0.0045,0.0000,0.0889,0.0000,0.0008,0.0004,0.0000,0.0117,0.0118,0.0278,0.1109,0.0000,0.0000,0.0008,0.0000,0.0001,0.0036,0.0012,0.0000,0.0000,0.0000,0.0013,0.0000,0.0000,0.0010,0.0000,0.0000,0.0000
3,Fishing and aquaculture,0.0022,0.0001,0.0000,0.0004,0.0000,0.0005,0.0028,0.0000,0.0000,0.0000,0.0000,0.0000,0.0012,0.0021,0.0010,0.0212,0.0301,0.0145,0.0715,0.0501,0.0307,0.0144,0.0259,0.0001,0.0000,0.0000,0.3947,0.0098,0.0321,0.0097,0.0058,0.0005,0.0005,0.0002,0.0000,0.0001,0.0128,0.0045,0.0000,0.0889,0.0000,0.0008,0.0004,0.0000,0.0117,0.0118,0.0278,0.1109,0.0000,0.0000,0.0008,0.0000,0.0001,0.0036,0.0012,0.0000,0.0000,0.0000,0.0013,0.0000,0.0000,0.0010,0.0000,0.0000,0.0000
4,Mining and quarrying,0.0022,0.0001,0.0000,0.0004,0.0000,0.0005,0.0028,0.0000,0.0000,0.0000,0.0000,0.0000,0.0012,0.0021,0.0010,0.0212,0.0301,0.0145,0.0715,0.0501,0.0307,0.0144,0.0259,0.0001,0.0000,0.0000,0.3947,0.0098,0.0321,0.0097,0.0058,0.0005,0.0005,0.0002,0.0000,0.0001,0.0128,0.0045,0.0000,0.0889,0.0000,0.0008,0.0004,0.0000,0.0117,0.0118,0.0278,0.1109,0.0000,0.0000,0.0008,0.0000,0.0001,0.0036,0.0012,0.0000,0.0000,0.0000,0.0013,0.0000,0.0000,0.0010,0.0000,0.0000,0.0000
5,Manufacture of food products; beverages and tobacco products,0.0022,0.0001,0.0000,0.0004,0.0000,0.0005,0.0028,0.0000,0.0000,0.0000,0.0000,0.0000,0.0012,0.0021,0.0010,0.0212,0.0301,0.0145,0.0715,0.0501,0.0307,0.0144,0.0259,0.0001,0.0000,0.0000,0.3947,0.0098,0.0321,0.0097,0.0058,0.0005,0.0005,0.0002,0.0000,0.0001,0.0128,0.0045,0.0000,0.0889,0.0000,0.0008,0.0004,0.0000,0.0117,0.0118,0.0278,0.1109,0.0000,0.0000,0.0008,0.0000,0.0001,0.0036,0.0012,0.0000,0.0000,0.0000,0.0013,0.0000,0.0000,0.0010,0.0000,0.0000,0.0000
6,"Manufacture of textiles, wearing apparel, leather and related products",0.0022,0.0001,0.0000,0.0004,0.0000,0.0005,0.0028,0.0000,0.0000,0.0000,0.0000,0.0000,0.0012,0.0021,0.0010,0.0212,0.0301,0.0145,0.0715,0.0501,0.0307,0.0144,0.0259,0.0001,0.0000,0.0000,0.3947,0.0098,0.0321,0.0097,0.0058,0.0005,0.0005,0.0002,0.0000,0.0001,0.0128,0.0045,0.0000,0.0889,0.0000,0.0008,0.0004,0.0000,0.0117,0.0118,0.0278,0.1109,0.0000,0.0000,0.0008,0.0000,0.0001,0.0036,0.0012,0.0000,0.0000,0.0000,0.0013,0.0000,0.0000,0.0010,0.0000,0.0000,0.0000
7,"Manufacture of wood and of products of wood and cork, except furniture; manufacture of articles of straw and plaiting materials",0.0022,0.0001,0.0000,0.0004,0.0000,0.0005,0.0028,0.0000,0.0000,0.0000,0.0000,0.0000,0.0012,0.0021,0.0010,0.0212,0.0301,0.0145,0.0715,0.0501,0.0307,0.0144,0.0259,0.0001,0.0000,0.0000,0.3947,0.0098,0.0321,0.0097,0.0058,0.0005,0.0005,0.0002,0.0000,0.0001,0.0128,0.0045,0.0000,0.0889,0.0000,0.0008,0.0004,0.0000,0.0117,0.0118,0.0278,0.1109,0.0000,0.0000,0.0008,0.0000,0.0001,0.0036,0.0012,0.0000,0.0000,0.0000,0.0013,0.0000,0.0000,0.0010,0.0000,0.0000,0.0000
8,Manufacture of paper and paper products,0.0022,0.0001,0.0000,0.0004,0.0000,0.0005,0.0028,0.0000,0.0000,0.0000,0.0000,0.0000,0.0012,0.0021,0.0010,0.0212,0.0301,0.0145,0.0715,0.0501,0.0307,0.0144,0.0259,0.0001,0.0000,0.0000,0.3947,0.0098,0.0321,0.0097,0.0058,0.0005,0.0005,0.0002,0.0000,0.0001,0.0128,0.0045,0.0000,0.0889,0.0000,0.0008,0.0004,0.0000,0.0117,0.0118,0.0278,0.1109,0.0000,0.0000,0.0008,0.0000,0.0001,0.0036,0.0012,0.0000,0.0000,0.0000,0.0013,0.0000,0.0000,0.0010,0.0000,0.0000,0.0000
9,Printing and reproduction of recorded media,0.0022,0.0001,0.0000,0.0004,0.0000,0.0005,0.0028,0.0000,0.0000,0.0000,0.0000,0.0000,0.0012,0.0021,0.0010,0.0212,0.0301,0.0145,0.0715,0.0501,0.0307,0.0144,0.0259,0.0001,0.0000,0.0000,0.3947,0.0098,0.0321,0.0097,0.0058,0.0005,0.0005,0.0002,0.0000,0.0001,0.0128,0.0045,0.0000,0.0889,0.0000,0.0008,0.0004,0.0000,0.0117,0.0118,0.0278,0.1109,0.0000,0.0000,0.0008,0.0000,0.0001,0.0036,0.0012,0.0000,0.0000,0.0000,0.0013,0.0000,0.0000,0.0010,0.0000,0.0000,0.0000
10,Manufacture of coke and refined petroleum products,0.0022,0.0001,0.0000,0.0004,0.0000,0.0005,0.0028,0.0000,0.0000,0.0000,0.0000,0.0000,0.0012,0.0021,0.0010,0.0212,0.0301,0.0145,0.0715,0.0501,0.0307,0.0144,0.0259,0.0001,0.0000,0.0000,0.3947,0.0098,0.0321,0.0097,0.0058,0.0005,0.0005,0.0002,0.0000,0.0001,0.0128,0.0045,0.0000,0.0889,0.0000,0.0008,0.0004,0.0000,0.0117,0.0118,0.0278,0.1109,0.0000,0.0000,0.0008,0.0000,0.0001,0.0036,0.0012,0.0000,0.0000,0.0000,0.0013,0.0000,0.0000,0.0010,0.0000,0.0000,0.0000
11,Manufacture of chemicals and chemical products,0.0022,0.0001,0.0000,0.0004,0.0000,0.0005,0.0028,0.0000,0.0000,0.0000,0.0000,0.0000,0.0012,0.0021,0.0010,0.0212,0.0301,0.0145,0.0715,0.0501,0.0307,0.0144,0.0259,0.0001,0.0000,0.0000,0.3947,0.0098,0.0321,0.0097,0.0058,0.0005,0.0005,0.0002,0.0000,0.0001,0.0128,0.0045,0.0000,0.0889,0.0000,0.0008,0.0004,0.0000,0.0117,0.0118,0.0278,0.1109,0.0000,0.0000,0.0008,0.0000,0.0001,0.0036,0.0012,0.0000,0.0000,0.0000,0.0013,0.0000,0.0000,0.0010,0.0000,0.0000,0.0000
12,Manufacture of basic pharmaceutical products and pharmaceutical preparations,0.0022,0.0001,0.0000,0.0004,0.0000,0.0005,0.0028,0.0000,0.0000,0.0000,0.0000,0.0000,0.0012,0.0021,0.0010,0.0212,0.0301,0.0145,0.0715,0.0501,0.0307,0.0144,0.0259,0.0001,0.0000,0.0000,0.3947,0.0098,0.0321,0.0097,0.0058,0.0005,0.0005,0.0002,0.0000,0.0001,0.0128,0.0045,0.0000,0.0889,0.0000,0.0008,0.0004,0.0000,0.0117,0.0118,0.0278,0.1109,0.0000,0.0000,0.0008,0.0000,0.0001,0.0036,0.0012,0.0000,0.0000,0.0000,0.0013,0.0000,0.0000,0.0010,0.0000,0.0000,0.0000
13,Manufacture of rubber and plastic products,0.0022,0.0001,0.0000,0.0004,0.0000,0.0005,0.0028,0.0000,0.0000,0.0000,0.0000,0.0000,0.0012,0.0021,0.0010,0.0212,0.0301,0.0145,0.0715,0.0501,0.0307,0.0144,0.0259,0.0001,0.0000,0.0000,0.3947,0.0098,0.0321,0.0097,0.0058,0.0005,0.0005,0.0002,0.0000,0.0001,0.0128,0.0045,0.0000,0.0889,0.0000,0.0008,0.0004,0.0000,0.0117,0.0118,0.0278,0.1109,0.0000,0.0000,0.0008,0.0000,0.0001,0.0036,0.0012,0.0000,0.0000,0.0000,0.0013,0.0000,0.0000,0.0010,0.0000,0.0000,0.0000
14,Manufacture of other non-metallic mineral products,0.0022,0.0001,0.0000,0.0004,0.0000,0.0005,0.0028,0.0000,0.0000,0.0000,0.0000,0.0000,0.0012,0.0021,0.0010,0.0212,0.0301,0.0145,0.0715,0.0501,0.0307,0.0144,0.0259,0.0001,0.0000,0.0000,0.3947,0.0098,0.0321,0.0097,0.0058,0.0005,0.0005,0.0002,0.0000,0.0001,0.0128,0.0045,0.0000,0.0889,0.0000,0.0008,0.0004,0.0000,0.0117,0.0118,0.0278,0.1109,0.0000,0.0000,0.0008,0.0000,0.0001,0.0036,0.0012,0.0000,0.0000,0.0000,0.0013,0.0000,0.0000,0.0010,0.0000,0.0000,0.0000
15,Manufacture of basic metals,0.0022,0.0001,0.0000,0.0004,0.0000,0.0005,0.0028,0.0000,0.0000,0.0000,0.0000,0.0000,0.0012,0.0021,0.0010,0.0212,0.0301,0.0145,0.0715,0.0501,0.0307,0.0144,0.0259,0.0001,0.0000,0.0000,0.3947,0.0098,0.0321,0.0097,0.0058,0.0005,0.0005,0.0002,0.0000,0.0001,0.0128,0.0045,0.0000,0.0889,0.0000,0.0008,0.0004,0.0000,0.0117,0.0118,0.0278,0.1109,0.0000,0.0000,0.0008,0.0000,0.0001,0.0036,0.0012,0.0000,0.0000,0.0000,0.0013,0.0000,0.0000,0.0010,0.0000,0.0000,0.0000
16,"Manufacture of fabricated metal products, except machinery and equipment",0.0022,0.0001,0.0000,0.0004,0.0000,0.0005,0.0028,0.0000,0.0000,0.0000,0.0000,0.0000,0.0012,0.0021,0.0010,0.0212,0.0301,0.0145,0.0715,0.0501,0.0307,0.0144,0.0259,0.0001,0.0000,0.0000,0.3947,0.0098,0.0321,0.0097,0.0058,0.0005,0.0005,0.0002,0.0000,0.0001,0.0128,0.0045,0.0000,0.0889,0.0000,0.0008,0.0004,0.0000,0.0117,0.0118,0.0278,0.1109,0.0000,0.0000,0.0008,0.0000,0.0001,0.0036,0.0012,0.0000,0.0000,0.0000,0.0013,0.0000,0.0000,0.0010,0.0000,0.0000,0.0000
17,"Manufacture of computer, electronic and optical products",0.0022,0.0001,0.0000,0.0004,0.0000,0.0005,0.0028,0.0000,0.0000,0.0000,0.0000,0.0000,0.0012,0.0021,0.0010,0.0212,0.0301,0.0145,0.0715,0.0501,0.0307,0.0144,0.0259,0.0001,0.0000,0.0000,0.3947,0.0098,0.0321,0.0097,0.0058,0.0005,0.0005,0.0002,0.0000,0.0001,0.0128,0.0045,0.0000,0.0889,0.0000,0.0008,0.0004,0.0000,0.0117,0.0118,0.0278,0.1109,0.0000,0.0000,0.0008,0.0000,0.0001,0.0036,0.0012,0.0000,0.0000,0.0000,0.0013,0.0000,0.0000,0.0010,0.0000,0.0000,0.0000
18,Manufacture of electrical equipment,0.0022,0.0001,0.0000,0.0004,0.0000,0.0005,0.0028,0.0000,0.0000,0.0000,0.0000,0.0000,0.0012,0.0021,0.0010,0.0212,0.0301,0.0145,0.0715,0.0501,0.0307,0.0144,0.0259,0.0001,0.0000,0.0000,0.3947,0.0098,0.0321,0.0097,0.0058,0.0005,0.0005,0.0002,0.0000,0.0001,0.0128,0.0045,0.0000,0.0889,0.0000,0.0008,0.0004,0.0000,0.0117,0.0118,0.0278,0.1109,0.0000,0.0000,0.0008,0.0000,0.0001,0.0036,0.0012,0.0000,0.0000,0.0000,0.0013,0.0000,0.0000,0.0010,0.0000,0.0000,0.0000
19,Manufacture of machinery and equipment n.e.c.,0.0022,0.0001,0.0000,0.0004,0.0000,0.0005,0.0028,0.0000,0.0000,0.0000,0.0000,0.0000,0.0012,0.0021,0.0010,0.0212,0.0301,0.0145,0.0715,0.0501,0.0307,0.0144,0.0259,0.0001,0.0000,0.0000,0.3947,0.0098,0.0321,0.0097,0.0058,0.0005,0.0005,0.0002,0.0000,0.0001,0.0128,0.0045,0.0000,0.0889,0.0000,0.0008,0.0004,0.0000,0.0117,0.0118,0.0278,0.1109,0.0000,0.0000,0.0008,0.0000,0.0001,0.0036,0.0012,0.0000,0.0000,0.0000,0.0013,0.0000,0.0000,0.0010,0.0000,0.0000,0.0000
20,"Manufacture of motor vehicles, trailers and semi-trailers",0.0022,0.0001,0.0000,0.0004,0.0000,0.0005,0.0028,0.0000,0.0000,0.0000,0.0000,0.0000,0.0012,0.0021,0.0010,0.0212,0.0301,0.0145,0.0715,0.0501,0.0307,0.0144,0.0259,0.0001,0.0000,0.0000,0.3947,0.0098,0.0321,0.0097,0.0058,0.0005,0.0005,0.0002,0.0000,0.0001,0.0128,0.0045,0.0000,0.0889,0.0000,0.0008,0.0004,0.0000,0.0117,0.0118,0.0278,0.1109,0.0000,0.0000,0.0008,0.0000,0.0001,0.0036,0.0012,0.0000,0.0000,0.0000,0.0013,0.0000,0.0000,0.0010,0.0000,0.0000,0.0000
21,Manufacture of other transport equipment,0.0022,0.0001,0.0000,0.0004,0.0000,0.0005,0.0028,0.0000,0.0000,0.0000,0.0000,0.0000,0.0012,0.0021,0.0010,0.0212,0.0301,0.0145,0.0715,0.0501,0.0307,0.0144,0.0259,0.0001,0.0000,0.0000,0.3947,0.0098,0.0321,0.0097,0.0058,0.0005,0.0005,0.0002,0.0000,0.0001,0.0128,0.0045,0.0000,0.0889,0.0000,0.0008,0.0004,0.0000,0.0117,0.0118,0.0278,0.1109,0.0000,0.0000,0.0008,0.0000,0.0001,0.0036,0.0012,0.0000,0.0000,0.0000,0.0013,0.0000,0.0000,0.0010,0.0000,0.0000,0.0000
22,Manufacture of furniture; other manufacturing,0.0022,0.0001,0.0000,0.0004,0.0000,0.0005,0.0028,0.0000,0.0000,0.0000,0.0000,0.0000,0.0012,0.0021,0.0010,0.0212,0.0301,0.0145,0.0715,0.0501,0.0307,0.0144,0.0259,0.0001,0.0000,0.0000,0.3947,0.0098,0.0321,0.0097,0.0058,0.0005,0.0005,0.0002,0.0000,0.0001,0.0128,0.0045,0.0000,0.0889,0.0000,0.0008,0.0004,0.0000,0.0117,0.0118,0.0278,0.1109,0.0000,0.0000,0.0008,0.0000,0.0001,0.0036,0.0012,0.0000,0.0000,0.0000,0.0013,0.0000,0.0000,0.0010,0.0000,0.0000,0.0000
23,Repair and installation of machinery and equipment,0.0022,0.0001,0.0000,0.0004,0.0000,0.0005,0.0028,0.0000,0.0000,0.0000,0.0000,0.0000,0.0012,0.0021,0.0010,0.0212,0.0301,0.0145,0.0715,0.0501,0.0307,0.0144,0.0259,0.0001,0.0000,0.0000,0.3947,0.0098,0.0321,0.0097,0.0058,0.0005,0.0005,0.0002,0.0000,0.0001,0.0128,0.0045,0.0000,0.0889,0.0000,0.0008,0.0004,0.0000,0.0117,0.0118,0.0278,0.1109,0.0000,0.0000,0.0008,0.0000,0.0001,0.0036,0.0012,0.0000,0.0000,0.0000,0.0013,0.0000,0.0000,0.0010,0.0000,0.0000,0.0000
24,"Electricity, gas, steam and air conditioning supply",0.0022,0.0001,0.0000,0.0004,0.0000,0.0005,0.0028,0.0000,0.0000,0.0000,0.0000,0.0000,0.0012,0.0021,0.0010,0.0212,0.0301,0.0145,0.0715,0.0501,0.0307,0.0144,0.0259,0.0001,0.0000,0.0000,0.3947,0.0098,0.0321,0.0097,0.0058,0.0005,0.0005,0.0002,0.0000,0.0001,0.0128,0.0045,0.0000,0.0889,0.0000,0.0008,0.0004,0.0000,0.0117,0.0118,0.0278,0.1109,0.0000,0.0000,0.0008,0.0000,0.0001,0.0036,0.0012,0.0000,0.0000,0.0000,0.0013,0.0000,0.0000,0.0010,0.0000,0.0000,0.0000
25,"Water collection, treatment and supply",0.0022,0.0001,0.0000,0.0004,0.0000,0.0005,0.0028,0.0000,0.0000,0.0000,0.0000,0.0000,0.0012,0.0021,0.0010,0.0212,0.0301,0.0145,0.0715,0.0501,0.0307,0.0144,0.0259,0.0001,0.0000,0.0000,0.3947,0.0098,0.0321,0.0097,0.0058,0.0005,0.0005,0.0002,0.0000,0.0001,0.0128,0.0045,0.0000,0.0889,0.0000,0.0008,0.0004,0.0000,0.0117,0.0118,0.0278,0.1109,0.0000,0.0000,0.0008,0.0000,0.0001,0.0036,0.0012,0.0000,0.0000,0.0000,0.0013,0.0000,0.0000,0.0010,0.0000,0.0000,0.0000
26,"Sewerage, waste management, remediation activities",0.0022,0.0001,0.0000,0.0004,0.0000,0.0005,0.0028,0.0000,0.0000,0.0000,0.0000,0.0000,0.0012,0.0021,0.0010,0.0212,0.0301,0.0145,0.0715,0.0501,0.0307,0.0144,0.0259,0.0001,0.0000,0.0000,0.3947,0.0098,0.0321,0.0097,0.0058,0.0005,0.0005,0.0002,0.0000,0.0001,0.0128,0.0045,0.0000,0.0889,0.0000,0.0008,0.0004,0.0000,0.0117,0.0118,0.0278,0.1109,0.0000,0.0000,0.0008,0.0000,0.0001,0.0036,0.0012,0.0000,0.0000,0.0000,0.0013,0.0000,0.0000,0.0010,0.0000,0.0000,0.0000
27,Construction,0.0022,0.0001,0.0000,0.0004,0.0000,0.0005,0.0028,0.0000,0.0000,0.0000,0.0000,0.0000,0.0012,0.0021,0.0010,0.0212,0.0301,0.0145,0.0715,0.0501,0.0307,0.0144,0.0259,0.0001,0.0000,0.0000,0.3947,0.0098,0.0321,0.0097,0.0058,0.0005,0.0005,0.0002,0.0000,0.0001,0.0128,0.0045,0.0000,0.0889,0.0000,0.0008,0.0004,0.0000,0.0117,0.0118,0.0278,0.1109,0.0000,0.0000,0.0008,0.0000,0.0001,0.0036,0.0012,0.0000,0.0000,0.0000,0.0013,0.0000,0.0000,0.0010,0.0000,0.0000,0.0000
28,Wholesale and retail trade and repair of motor vehicles and motorcycles,0.0022,0.0001,0.0000,0.0004,0.0000,0.0005,0.0028,0.0000,0.0000,0.0000,0.0000,0.0000,0.0012,0.0021,0.0010,0.0212,0.0301,0.0145,0.0715,0.0501,0.0307,0.0144,0.0259,0.0001,0.0000,0.0000,0.3947,0.0098,0.0321,0.0097,0.0058,0.0005,0.0005,0.0002,0.0000,0.0001,0.0128,0.0045,0.0000,0.0889,0.0000,0.0008,0.0004,0.0000,0.0117,0.0118,0.0278,0.1109,0.0000,0.0000,0.0008,0.0000,0.0001,0.0036,0.0012,0.0000,0.0000,0.0000,0.0013,0.0000,0.0000,0.0010,0.0000,0.0000,0.0000
29,"Wholesale trade, except of motor vehicles and motorcycles",0.0022,0.0001,0.0000,0.0004,0.0000,0.0005,0.0028,0.0000,0.0000,0.0000,0.0000,0.0000,0.0012,0.0021,0.0010,0.0212,0.0301,0.0145,0.0715,0.0501,0.0307,0.0144,0.0259,0.0001,0.0000,0.0000,0.3947,0.0098,0.0321,0.0097,0.0058,0.0005,0.0005,0.0002,0.0000,0.0001,0.0128,0.0045,0.0000,0.0889,0.0000,0.0008,0.0004,0.0000,0.0117,0.0118,0.0278,0.1109,0.0000,0.0000,0.0008,0.0000,0.0001,0.0036,0.0012,0.0000,0.0000,0.0000,0.0013,0.0000,0.0000,0.0010,0.0000,0.0000,0.0000
30,"Retail trade, except of motor vehicles and motorcycles",0.0022,0.0001,0.0000,0.0004,0.0000,0.0005,0.0028,0.0000,0.0000,0.0000,0.0000,0.0000,0.0012,0.0021,0.0010,0.0212,0.0301,0.0145,0.0715,0.0501,0.0307,0.0144,0.0259,0.0001,0.0000,0.0000,0.3947,0.0098,0.0321,0.0097,0.0058,0.0005,0.0005,0.0002,0.0000,0.0001,0.0128,0.0045,0.0000,0.0889,0.0000,0.0008,0.0004,0.0000,0.0117,0.0118,0.0278,0.1109,0.0000,0.0000,0.0008,0.0000,0.0001,0.0036,0.0012,0.0000,0.0000,0.0000,0.0013,0.0000,0.0000,0.0010,0.0000,0.0000,0.0000
31,Land transport and transport via pipelines,0.0022,0.0001,0.0000,0.0004,0.0000,0.0005,0.0028,0.0000,0.0000,0.0000,0.0000,0.0000,0.0012,0.0021,0.0010,0.0212,0.0301,0.0145,0.0715,0.0501,0.0307,0.0144,0.0259,0.0001,0.0000,0.0000,0.3947,0.0098,0.0321,0.0097,0.0058,0.0005,0.0005,0.0002,0.0000,0.0001,0.0128,0.0045,0.0000,0.0889,0.0000,0.0008,0.0004,0.0000,0.0117,0.0118,0.0278,0.1109,0.0000,0.0000,0.0008,0.0000,0.0001,0.0036,0.0012,0.0000,0.0000,0.0000,0.0013,0.0000,0.0000,0.0010,0.0000,0.0000,0.0000
32,Water transport,0.0022,0.0001,0.0000,0.0004,0.0000,0.0005,0.0028,0.0000,0.0000,0.0000,0.0000,0.0000,0.0012,0.0021,0.0010,0.0212,0.0301,0.0145,0.0715,0.0501,0.0307,0.0144,0.0259,0.0001,0.0000,0.0000,0.3947,0.0098,0.0321,0.0097,0.0058,0.0005,0.0005,0.0002,0.0000,0.0001,0.0128,0.0045,0.0000,0.0889,0.0000,0.0008,0.0004,0.0000,0.0117,0.0118,0.0278,0.1109,0.0000,0.0000,0.0008,0.0000,0.0001,0.0036,0.0012,0.0000,0.0000,0.0000,0.0013,0.0000,0.0000,0.0010,0.0000,0.0000,0.0000

In [65]:
#TEST 1
#anticipated for the control in TEST 1 and repeated below (from a run of test_ff with 1,000,000 firms, reported to EU scale)
with open('buyingSectorsPurchases.csv', 'r') as csvfile:
    reader = csv.reader(csvfile)
    buyingSectorsPurchases = [float(row[0]) for row in reader]

In [66]:
buyingSectorsPurchases

[87269.68016368477,
 10474.217260554517,
 3314.7286303589467,
 19702.419822338423,
 41624.609969521654,
 6579.484397176533,
 6417.294664186711,
 5143.063869708754,
 2635.225338895352,
 10611.886911777669,
 55700.46907269352,
 61026.52045931569,
 12496.056081260198,
 14430.798420140105,
 12989.482062754898,
 28780.038146130024,
 26187.355046425848,
 17167.494297225297,
 41000.31857398842,
 43801.110775484995,
 10025.739677648504,
 11558.74511088037,
 9777.760358037252,
 149979.61725286717,
 8557.206084553547,
 28485.519932858148,
 67715.20478862397,
 37530.00623902961,
 143282.1231107478,
 110609.72122426344,
 40704.25178946342,
 6705.260929085752,
 3394.0941117964194,
 40151.721698323825,
 9456.33015151278,
 80729.14479331418,
 17795.57154381381,
 11681.45929715438,
 19511.06385007167,
 67249.65022832574,
 26655.95066435996,
 6424.034785724611,
 6090.936885153171,
 500084.49738058116,
 629444.6811616754,
 19239.267160060546,
 7312.337497209594,
 4825.7536930995175,
 2172.1294635977797,
 2284.6739484082746,
 3504.4814368639773,
 3881.040875740288,
 313.31449882731613,
 6683.862751297045,
 107330.53274561175,
 29247.15139764891,
 112416.4675125133,
 56326.04085322122,
 4022.480729974563,
 3201.619887922663,
 175.7428200786476,
 19.308318539199735,
 194.63515968781306,
 0.0,
 0.0]

In [67]:
t=int(sum(buyingSectorsPurchases))

In [68]:
#! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! 
#if text_ff find that its internal value of the total (int part) of buying sectors purchases
#has changed, firm-feature-generation has to be rerun
with open("control4text_ff.txt", "w") as f:
    f.write(str(t))

with open("../control4text_ff.txt", "w") as f:
    f.write(str(t))

In [69]:
#TEST 1
#anticipated for the control in TEST 1 and repeated below
correctionCoef = sum(buyingSectorsPurchases)/mini_naio.iloc[0,6]

In [70]:
#TEST 1
#control test to understand how to fix invTableNama below
v=[0]*3
for i in range(65):
    v[0]+=invTable.iloc[i,20]*buyingSectorsPurchases[i]
    v[1]+=invTable.iloc[i,21]*buyingSectorsPurchases[i]
    v[2]+=invTable.iloc[i,27]*buyingSectorsPurchases[i]
v

[np.float64(146138.27102862057),
 np.float64(89334.33182032903),
 np.float64(1150294.2001160253)]

In [71]:
invTable.to_pickle("./invTableNoNama.xp")

In [72]:
invTable.shape

(65, 66)

<span style="color: DodgerBlue;">
==============================================================================================  
    
### create investment table, nama version, with raw corrections

==============================================================================================  
</span>

In [73]:
pd.options.display.float_format = '{:.1f}'.format

In [74]:
subset_index = mini_naio.index[1:66]

invTableNama=pd.DataFrame(index=subset_index,dtype='float64')
invTableNama[mini_naio['IND_USE (Labels)']]= 0.0 #= mini_naio['Gross fixed capital formation'][1:67].to_list()
invTableNama.rename(columns={'Total': 'sectors'}, inplace=True)
invTableNama['sectors']=nama.index.tolist()
#result of the above operations: invTableNama filled with zeroes, col. 0 with sectors from nama, col. names with naio sectors

with open('buyingSectorsPurchases.csv', 'r') as csvfile:
    reader = csv.reader(csvfile)
    buyingSectorsPurchases = [float(row[0]) for row in reader]
invTableNama['Totals'] = buyingSectorsPurchases
#result of the above operations: the table is always filled with zeroes, but with one more col containing the buying values 
#coming from test_ff; NB, those values are independent from the distribution of purchases within test_ff
#invTableNama['Totals'].sum() gives np.float64(3085530.281151042) which is the sum of SIM. EU SCALE buying sectors (from a 1,000,000
#firm sample)

#invTableNama['Totals'].sum()
invTableNama

,sectors,"Products of agriculture, hunting and related services","Products of forestry, logging and related services",Fish and other fishing products; aquaculture products; support services to fishing,Mining and quarrying,"Food, beverages and tobacco products","Textiles, wearing apparel, leather and related products","Wood and of products of wood and cork, except furniture; articles of straw and plaiting materials",Paper and paper products,Printing and recording services,Coke and refined petroleum products,Chemicals and chemical products,Basic pharmaceutical products and pharmaceutical preparations,Rubber and plastic products,Other non-metallic mineral products,Basic metals,"Fabricated metal products, except machinery and equipment","Computer, electronic and optical products",Electrical equipment,Machinery and equipment n.e.c.,"Motor vehicles, trailers and semi-trailers",Other transport equipment,Furniture and other manufactured goods,Repair and installation services of machinery and equipment,"Electricity, gas, steam and air conditioning",Natural water; water treatment and supply services,"Sewerage services; sewage sludge; waste collection, treatment and disposal services; materials recovery services; remediation services and other waste management services",Constructions and construction works,Wholesale and retail trade and repair services of motor vehicles and motorcycles,"Wholesale trade services, except of motor vehicles and motorcycles","Retail trade services, except of motor vehicles and motorcycles",Land transport services and transport services via pipelines,Water transport services,Air transport services,Warehousing and support services for transportation,Postal and courier services,Accommodation and food services,Publishing services,"Motion picture, video and television programme production services, sound recording and music publishing; programming and broadcasting services",Telecommunications services,"Computer programming, consultancy and related services; Information services","Financial services, except insurance and pension funding","Insurance, reinsurance and pension funding services, except compulsory social security",Services auxiliary to financial services and insurance services,Imputed rents of owner-occupied dwellings,Real estate services excluding imputed rents,Legal and accounting services; services of head offices; management consultancy services,Architectural and engineering services; technical testing and analysis services,Scientific research and development services,Advertising and market research services,"Other professional, scientific and technical services and veterinary services",Rental and leasing services,Employment services,"Travel agency, tour operator and other reservation services and related services","Security and investigation services; services to buildings and landscape; office administrative, office support and other business support services",Public administration and defence services; compulsory social security services,Education services,Human health services,Residential care services; social work services without accommodation,"Creative, arts, entertainment, library, archive, museum, other cultural services; gambling and betting services",Sporting services and amusement and recreation services,Services furnished by membership organisations,Repair services of computers and personal and household goods,Other personal services,Services of households as employers; undifferentiated goods and services produced by households for own use,Services provided by extraterritorial organisations and bodies,Totals
1,"Crop and animal production, hunting and related service activities",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,87269.7
2,Forestry and logging,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10474.2
3,Fishing and aquaculture,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3314.7
4,Mining and quarrying,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,19702.4
5,Manufacture of food products; beverages and tobacco products,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,41624.6
6,"Manufacture of textiles, wearing apparel, leather and related products",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6579.5
7,"Manufacture of wood and of products of wood and cork, except furniture; manufacture of articles of straw and plaiting materials",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6417.3
8,Manufacture of paper and paper products,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5143.1
9,Printing and reproduction of recorded media,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2635.2
10,Manufacture of coke and refined petroleum products,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10611.9
11,Manufacture of chemicals and chemical products,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,55700.5
12,Manufacture of basic pharmaceutical products and pharmaceutical preparations,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,61026.5
13,Manufacture of rubber and plastic products,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12496.1
14,Manufacture of other non-metallic mineral products,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14430.8
15,Manufacture of basic metals,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12989.5
16,"Manufacture of fabricated metal products, except machinery and equipment",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,28780.0
17,"Manufacture of computer, electronic and optical products",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,26187.4
18,Manufacture of electrical equipment,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17167.5
19,Manufacture of machinery and equipment n.e.c.,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,41000.3
20,"Manufacture of motor vehicles, trailers and semi-trailers",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,43801.1
21,Manufacture of other transport equipment,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10025.7
22,Manufacture of furniture; other manufacturing,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11558.7
23,Repair and installation of machinery and equipment,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9777.8
24,"Electricity, gas, steam and air conditioning supply",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,149979.6
25,"Water collection, treatment and supply",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8557.2
26,"Sewerage, waste management, remediation activities",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,28485.5
27,Construction,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,67715.2
28,Wholesale and retail trade and repair of motor vehicles and motorcycles,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,37530.0
29,"Wholesale trade, except of motor vehicles and motorcycles",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,143282.1
30,"Retail trade, except of motor vehicles and motorcycles",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,110609.7
31,Land transport and transport via pipelines,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40704.3
32,Water transport,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6705.3
33,Air transport,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3394.1
34,Warehousing and support activities for transportation,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40151.7
35,Postal and courier activities,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9456.3
36,Accommodation and food service activities,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,80729.1
37,Publishing activities,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17795.6
38,"Motion picture, video, television programme production; programming and broadcasting activities",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11681.5
39,Telecommunications,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,19511.1
40,"Computer programming, consultancy, and information service activities",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,67249.7
41,"Financial service activities, except insurance and pension funding",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,26656.0
42,"Insurance, reinsurance and pension funding, except compulsory social security",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6424.0
43,Activities auxiliary to financial services and insurance activities,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6090.9
44,Imputed rents of owner-occupied dwellings,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,500084.5
45,Real estate activities,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,629444.7
46,Legal and accounting activities; activities of head offices; management consultancy activities,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,19239.3
47,Architectural and engineering activities; technical testing and analysis,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7312.3
48,Scientific research and development,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4825.8
49,Advertising and market research,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2172.1
50,"Other professional, scientific and technical activities; veterinary activities",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2284.7
51,Rental and leasing activities,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3504.5

# Imputed rents special case
(do not modify the title, as it is quoted in modelEU27)

Unit of measure:   Million euro  

**naio**, output to investment by Constructions 1310617.30

total sales in **nama** of

- Dwellings are 156584.3

- Other buildings 126304.7

and those to _Imputed rents_ are respectively 134269.9 and 20335.4


(156584.3 + 126304.7) / 1310617.30 =>  0.2158440912

at the **naio** scale, sales at _Imputed rents_ would be
(134269.9 + 20335.4)/0.2158440912 =>  716282.29  
that we round to 600,000 considering uniquely the substitutions; which gives an equivalent value of assets of 600,000 * 50 => 30,000,000 where 50 is the duration in years

A check: real estate assets of Italian households is estimated around 5,000,000 millions; considering a population ratio of 60/447 that value gives 37,250,000 which is consistent


NB
we create in **test_ff** a unique firm for sector _Imputed rents_ with K>0, L=0 e interest rate 0  
The firm does not generate VA, so we evaluate a K return of 0  
We set K = 30,000,000, but correcting it inversely proportional to the final correction introducing the multiplicaton by the rate EU/sample, so K = 30,000,000 * (sample dimension)/(EU firm number)

[a memo: **nama** sales are **550299.5** (only 9 sectors, or 8 considering _Dwellings_+_Other buildings_ as _Costruction_ and only a subset of the EU 27 countries

on the other hand, **naio** Gross capital formation is 3320258.70]

In [75]:
for i in range(len(buyingSectorsPurchases)):
    print(i,buyingSectorsPurchases[i])

0 87269.68016368477
1 10474.217260554517
2 3314.7286303589467
3 19702.419822338423
4 41624.609969521654
5 6579.484397176533
6 6417.294664186711
7 5143.063869708754
8 2635.225338895352
9 10611.886911777669
10 55700.46907269352
11 61026.52045931569
12 12496.056081260198
13 14430.798420140105
14 12989.482062754898
15 28780.038146130024
16 26187.355046425848
17 17167.494297225297
18 41000.31857398842
19 43801.110775484995
20 10025.739677648504
21 11558.74511088037
22 9777.760358037252
23 149979.61725286717
24 8557.206084553547
25 28485.519932858148
26 67715.20478862397
27 37530.00623902961
28 143282.1231107478
29 110609.72122426344
30 40704.25178946342
31 6705.260929085752
32 3394.0941117964194
33 40151.721698323825
34 9456.33015151278
35 80729.14479331418
36 17795.57154381381
37 11681.45929715438
38 19511.06385007167
39 67249.65022832574
40 26655.95066435996
41 6424.034785724611
42 6090.936885153171
43 500084.49738058116
44 629444.6811616754
45 19239.267160060546
46 7312.337497209594
47 4825.7536930995175
48 2172.1294635977797
49 2284.6739484082746
50 3504.4814368639773
51 3881.040875740288
52 313.31449882731613
53 6683.862751297045
54 107330.53274561175
55 29247.15139764891
56 112416.4675125133
57 56326.04085322122
58 4022.480729974563
59 3201.619887922663
60 175.7428200786476
61 19.308318539199735
62 194.63515968781306
63 0.0
64 0.0

In [76]:
sum(buyingSectorsPurchases)

2914103.387763791

In [77]:
rowStructure = []
for i in range(len(GrossFixedCapitalFormation)): 
    rowStructure.append(GrossFixedCapitalFormation[i]/sum(GrossFixedCapitalFormation))
rowStructure = np.array(rowStructure)
for i in range(65):  
    invTableNama.iloc[i, 1:66] = invTableNama.iloc[i, 66] * rowStructure

# summing cols
totals = invTableNama.iloc[:, 1:].sum(numeric_only=True)
# Insert a label for the new row
totals_row = pd.Series(['Totals'] + totals.tolist(), index=invTableNama.columns)
# Append the row to the DataFrame
invTableNama = pd.concat([invTableNama, totals_row.to_frame().T], ignore_index=True)

#the global total is 3085534.6, same value above
#now invTableNama contains absolute values, consistent with the buying values from test_ff and structure coming from naio
#the total value is less than the Gross Fixed Capital Formation of naio (3320258.70) but here we have uniquely the substitutions

#by construction, we have the same total for the marginal values of rows (purchases by sectors, broken down by the composition  
#of gross capital formation) and columns (each of them contains the result of applying the same share to a list of addenda summing up to 
#the total 3085534.6 and the sum of all the shares giving 1)

invTableNama

,sectors,"Products of agriculture, hunting and related services","Products of forestry, logging and related services",Fish and other fishing products; aquaculture products; support services to fishing,Mining and quarrying,"Food, beverages and tobacco products","Textiles, wearing apparel, leather and related products","Wood and of products of wood and cork, except furniture; articles of straw and plaiting materials",Paper and paper products,Printing and recording services,Coke and refined petroleum products,Chemicals and chemical products,Basic pharmaceutical products and pharmaceutical preparations,Rubber and plastic products,Other non-metallic mineral products,Basic metals,"Fabricated metal products, except machinery and equipment","Computer, electronic and optical products",Electrical equipment,Machinery and equipment n.e.c.,"Motor vehicles, trailers and semi-trailers",Other transport equipment,Furniture and other manufactured goods,Repair and installation services of machinery and equipment,"Electricity, gas, steam and air conditioning",Natural water; water treatment and supply services,"Sewerage services; sewage sludge; waste collection, treatment and disposal services; materials recovery services; remediation services and other waste management services",Constructions and construction works,Wholesale and retail trade and repair services of motor vehicles and motorcycles,"Wholesale trade services, except of motor vehicles and motorcycles","Retail trade services, except of motor vehicles and motorcycles",Land transport services and transport services via pipelines,Water transport services,Air transport services,Warehousing and support services for transportation,Postal and courier services,Accommodation and food services,Publishing services,"Motion picture, video and television programme production services, sound recording and music publishing; programming and broadcasting services",Telecommunications services,"Computer programming, consultancy and related services; Information services","Financial services, except insurance and pension funding","Insurance, reinsurance and pension funding services, except compulsory social security",Services auxiliary to financial services and insurance services,Imputed rents of owner-occupied dwellings,Real estate services excluding imputed rents,Legal and accounting services; services of head offices; management consultancy services,Architectural and engineering services; technical testing and analysis services,Scientific research and development services,Advertising and market research services,"Other professional, scientific and technical services and veterinary services",Rental and leasing services,Employment services,"Travel agency, tour operator and other reservation services and related services","Security and investigation services; services to buildings and landscape; office administrative, office support and other business support services",Public administration and defence services; compulsory social security services,Education services,Human health services,Residential care services; social work services without accommodation,"Creative, arts, entertainment, library, archive, museum, other cultural services; gambling and betting services",Sporting services and amusement and recreation services,Services furnished by membership organisations,Repair services of computers and personal and household goods,Other personal services,Services of households as employers; undifferentiated goods and services produced by households for own use,Services provided by extraterritorial organisations and bodies,Totals
0,"Crop and animal production, hunting and related service activities",195.7,12.0,1.5,33.3,0.0,42.2,244.3,0.0,0.2,0.0,1.1,0.0,104.1,185.3,87.5,1846.4,2623.0,1265.5,6243.2,4376.5,2675.3,1256.3,2261.7,6.9,0.3,1.5,34448.3,857.8,2801.4,850.2,509.3,43.4,43.1,13.5,0.0,11.0,1115.8,390.5,0.0,7758.1,1.5,68.7,30.7,0.0,1019.4,1031.4,2429.9,9676.7,0.2,2.2,67.5,3.9,4.5,310.7,107.9,4.0,0.2,0.2,113.6,0.2,0.2,89.3,0.2,0.0,0.2,87269.7
1,Forestry and logging,23.5,1.4,0.2,4.0,0.0,5.1,29.3,0.0,0.0,0.0,0.1,0.0,12.5,22.2,10.5,221.6,314.8,151.9,749.3,525.3,321.1,150.8,271.5,0.8,0.0,0.2,4134.5,103.0,336.2,102.0,61.1,5.2,5.2,1.6,0.0,1.3,133.9,46.9,0.0,931.1,0.2,8.2,3.7,0.0,122.3,123.8,291.6,1161.4,0.0,0.3,8.1,0.5,0.5,37.3,13.0,0.5,0.0,0.0,13.6,0.0,0.0,10.7,0.0,0.0,0.0,10474.2
2,Fishing and aquaculture,7.4,0.5,0.1,1.3,0.0,1.6,9.3,0.0,0.0,0.0,0.0,0.0,4.0,7.0,3.3,70.1,99.6,48.1,237.1,166.2,101.6,47.7,85.9,0.3,0.0,0.1,1308.4,32.6,106.4,32.3,19.3,1.6,1.6,0.5,0.0,0.4,42.4,14.8,0.0,294.7,0.1,2.6,1.2,0.0,38.7,39.2,92.3,367.5,0.0,0.1,2.6,0.1,0.2,11.8,4.1,0.2,0.0,0.0,4.3,0.0,0.0,3.4,0.0,0.0,0.0,3314.7
3,Mining and quarrying,44.2,2.7,0.3,7.5,0.0,9.5,55.2,0.0,0.0,0.0,0.2,0.0,23.5,41.8,19.7,416.9,592.2,285.7,1409.5,988.0,604.0,283.6,510.6,1.6,0.1,0.3,7777.2,193.7,632.5,191.9,115.0,9.8,9.7,3.1,0.0,2.5,251.9,88.2,0.0,1751.5,0.3,15.5,6.9,0.0,230.1,232.9,548.6,2184.7,0.0,0.5,15.2,0.9,1.0,70.2,24.4,0.9,0.0,0.1,25.7,0.1,0.1,20.2,0.0,0.0,0.0,19702.4
4,Manufacture of food products; beverages and tobacco products,93.3,5.7,0.7,15.9,0.0,20.1,116.5,0.0,0.1,0.0,0.5,0.0,49.7,88.4,41.7,880.7,1251.1,603.6,2977.8,2087.4,1276.0,599.2,1078.8,3.3,0.1,0.7,16430.6,409.1,1336.2,405.5,242.9,20.7,20.6,6.5,0.0,5.3,532.2,186.2,0.0,3700.4,0.7,32.7,14.6,0.0,486.2,492.0,1159.0,4615.4,0.1,1.1,32.2,1.9,2.1,148.2,51.5,1.9,0.1,0.1,54.2,0.1,0.1,42.6,0.1,0.0,0.1,41624.6
5,"Manufacture of textiles, wearing apparel, leather and related products",14.8,0.9,0.1,2.5,0.0,3.2,18.4,0.0,0.0,0.0,0.1,0.0,7.8,14.0,6.6,139.2,197.8,95.4,470.7,330.0,201.7,94.7,170.5,0.5,0.0,0.1,2597.1,64.7,211.2,64.1,38.4,3.3,3.3,1.0,0.0,0.8,84.1,29.4,0.0,584.9,0.1,5.2,2.3,0.0,76.9,77.8,183.2,729.6,0.0,0.2,5.1,0.3,0.3,23.4,8.1,0.3,0.0,0.0,8.6,0.0,0.0,6.7,0.0,0.0,0.0,6579.5
6,"Manufacture of wood and of products of wood and cork, except furniture; manufacture of articles of straw and plaiting materials",14.4,0.9,0.1,2.5,0.0,3.1,18.0,0.0,0.0,0.0,0.1,0.0,7.7,13.6,6.4,135.8,192.9,93.1,459.1,321.8,196.7,92.4,166.3,0.5,0.0,0.1,2533.1,63.1,206.0,62.5,37.5,3.2,3.2,1.0,0.0,0.8,82.1,28.7,0.0,570.5,0.1,5.0,2.3,0.0,75.0,75.8,178.7,711.6,0.0,0.2,5.0,0.3,0.3,22.8,7.9,0.3,0.0,0.0,8.4,0.0,0.0,6.6,0.0,0.0,0.0,6417.3
7,Manufacture of paper and paper products,11.5,0.7,0.1,2.0,0.0,2.5,14.4,0.0,0.0,0.0,0.1,0.0,6.1,10.9,5.2,108.8,154.6,74.6,367.9,257.9,157.7,74.0,133.3,0.4,0.0,0.1,2030.1,50.6,165.1,50.1,30.0,2.6,2.5,0.8,0.0,0.6,65.8,23.0,0.0,457.2,0.1,4.0,1.8,0.0,60.1,60.8,143.2,570.3,0.0,0.1,4.0,0.2,0.3,18.3,6.4,0.2,0.0,0.0,6.7,0.0,0.0,5.3,0.0,0.0,0.0,5143.1
8,Printing and reproduction of recorded media,5.9,0.4,0.0,1.0,0.0,1.3,7.4,0.0,0.0,0.0,0.0,0.0,3.1,5.6,2.6,55.8,79.2,38.2,188.5,132.2,80.8,37.9,68.3,0.2,0.0,0.0,1040.2,25.9,84.6,25.7,15.4,1.3,1.3,0.4,0.0,0.3,33.7,11.8,0.0,234.3,0.0,2.1,0.9,0.0,30.8,31.1,73.4,292.2,0.0,0.1,2.0,0.1,0.1,9.4,3.3,0.1,0.0,0.0,3.4,0.0,0.0,2.7,0.0,0.0,0.0,2635.2
9,Manufacture of coke and refined petroleum products,23.8,1.5,0.2,4.1,0.0,5.1,29.7,0.0,0.0,0.0,0.1,0.0,12.7,22.5,10.6,224.5,319.0,153.9,759.2,532.2,325.3,152.8,275.0,0.8,0.0,0.2,4188.9,104.3,340.7,103.4,61.9,5.3,5.2,1.6,0.0,1.3,135.7,47.5,0.0,943.4,0.2,8.3,3.7,0.0,124.0,125.4,295.5,1176.7,0.0,0.3,8.2,0.5,0.5,37.8,13.1,0.5,0.0,0.0,13.8,0.0,0.0,10.9,0.0,0.0,0.0,10611.9
10,Manufacture of chemicals and chemical products,124.9,7.7,0.9,21.3,0.0,26.9,156.0,0.0,0.1,0.0,0.7,0.0,66.4,118.2,55.8,1178.5,1674.1,807.7,3984.8,2793.3,1707.5,801.9,1443.5,4.4,0.2,0.9,21986.8,547.5,1788.0,542.6,325.1,27.7,27.5,8.6,0.0,7.0,712.2,249.2,0.0,4951.7,1.0,43.8,19.6,0.0,650.6,658.3,1550.9,6176.2,0.1,1.4,43.1,2.5,2.9,198.3,68.9,2.6,0.1,0.2,72.5,0.2,0.1,57.0,0.1,0.0,0.1,55700.5
11,Manufacture of basic pharmaceutical products and pharmaceutical preparations,136.8,8.4,1.0,23.3,0.0,29.5,170.9,0.0,0.1,0.0,0.8,0.0,72.8,129.6,61.2,1291.2,1834.2,885.0,4365.8,3060.4,1870.8,878.5,1581.6,4.9,0.2,1.0,24089.2,599.8,1959.0,594.5,356.2,30.4,30.2,9.5,0.0,7.7,780.3,273.1,0.0,5425.2,1.0,48.0,21.4,0.0,712.8,721.3,1699.2,6766.8,0.1,1.5,47.2,2.7,3.1,217.3,75.5,2.8,0.2,0.2,79.5,0.2,0.2,62.4,0.1,0.0,0.2,61026.5
12,Manufacture of rubber and plastic products,28.0,1.7,0.2,4.8,0.0,6.0,35.0,0.0,0.0,0.0,0.2,0.0,14.9,26.5,12.5,264.4,375.6,181.2,894.0,626.7,383.1,179.9,323.9,1.0,0.0,0.2,4932.6,122.8,401.1,121.7,72.9,6.2,6.2,1.9,0.0,1.6,159.8,55.9,0.0,1110.9,0.2,9.8,4.4,0.0,146.0,147.7,347.9,1385.6,0.0,0.3,9.7,0.6,0.6,44.5,15.5,0.6,0.0,0.0,16.3,0.0,0.0,12.8,0.0,0.0,0.0,12496.1
13,Manufacture of other non-metallic mineral products,32.4,2.0,0.2,5.5,0.0,7.0,40.4,0.0,0.0,0.0,0.2,0.0,17.2,30.6,14.5,305.3,433.7,209.3,1032.4,723.7,442.4,207.7,374.0,1.1,0.0,0.2,5696.3,141.8,463.2,140.6,84.2,7.2,7.1,2.2,0.0,1.8,184.5,64.6,0.0,1282.9,0.2,11.4,5.1,0.0,168.6,170.6,401.8,1600.1,0.0,0.4,11.2,0.6,0.7,51.4,17.8,0.7,0.0,0.0,18.8,0.0,0.0,14.8,0.0,0.0,0.0,14430.8
14,Manufacture of basic metals,29.1,1.8,0.2,5.0,0.0,6.3,36.4,0.0,0.0,0.0,0.2,0.0,15.5,27.6,13.0,274.8,390.4,188.4,929.3,651.4,398.2,187.0,336.6,1.0,0.0,0.2,5127.4,127.7,417.0,126.5,75.8,6.5,6.4,2.0,0.0,1.6,166.1,58.1,0.0,1154.7,0.2,10.2,4.6,0.0,151.7,153.5,361.7,1440.3,0.0,0.3,10.1,0.6,0.7,46.3,16.1,0.6,0.0,0.0,16.9,0.0,0.0,13.3,0.0,0.0,0.0,12989.5
15,"Manufacture of fabricated metal products, except machinery and equipment",64.5,4.0,0.5,11.0,0.0,13.9,80.6,0.0,0.0,0.0,0.4,0.0,34.3,61.1,28.8,608.9,865.0,417.4,2058.9,1443.3,882.3,414.3,745.9,2.3,0.1,0.5,11360.4,282.9,923.9,280.4,168.0,14.3,14.2,4.5,0.0,3.6,368.0,128.8,0.0,2558.5,0.5,22.6,10.1,0.0,336.2,340.2,801.3,3191.2,0.1,0.7,22.3,1.3,1.5,102.5,35.6,1.3,0.1,0.1,37.5,0.1,0.1,29.4,0.1,0.0,0.1,28780.0
16,"Manufacture of computer, electronic and optical products",58.7,3.6,0.4,10.0,0.0,12.6,73.3,0.0,0.0,0.0,0.3,0.0,31.2,55.6,26.2,554.1,787.1,379.8,1873.4,1313.3,802.8,377.0,678.7,2.1,0.1,0.4,10337.0,257.4,840.6,255.1,152.8,13.0,12.9,4.1,0.0,3.3,334.8,117.2,0.0,2328.0,0.4,20.6,9.2,0.0,305.9,309.5,729.1,2903.7,0.1,0.7,20.3,1.2,1.4,93.2,32.4,1.2,0.1,0.1,34.1,0.1,0.1,26.8,0.1,0.0,0.1,26187.4
17,Manufacture of electrical equipment,38.5,2.4,0.3,6.6,0.0,8.3,48.1,0.0,0.0,0.0,0.2,0.0,20.5,36.4,17.2,363.2,516.0,249.0,1228.2,860.9,526.3,247.1,444.9,1.4,0.1,0.3,6776.6,168.7,551.1,167.2,100.2,8.5,8.5,2.7,0.0,2.2,219.5,76.8,0.0,1526.2,0.3,13.5,6.0,0.0,200.5,202.9,478.0,1903.6,0.0,0.4,13.3,0.8,0.9,61.1,21.2,0.8,0.0,0.0,22.4,0.0,0.0,17.6,0.0,0.0,0.0,17167.5
18,Manufacture of machinery and equipment n.e.c.,91.9,5.6,0.7,15.7,0.0,19.8,114.8,0.0,0.1,0.0,0.5,0.0,48.9,87.0,41.1,867.5,1232.3,594.6,2933.1,2056.1,1256.9,590.2,1062.6,3.3,0.1,0.7,16184.2,403.0,1316.1,399.4,239.3,20.4,20.3,6.4,0.0,5.2,524.2,183.4,0.0,3644.9,0.7,32.3,14.4,0.0,478.9,484.6,1141.6,4546.2,0.1,1.0,31.7,1.8,2.1,146.0,50.7,1.9,0.1,0.1,53.4,0.1,0.1,42.0,0.1,0.0,0.1,41000.3
19,"Manufacture of motor vehicles, trailers and semi-trailers",98.2,6.0,0.7,16.7,0.0,21.2,122.6,0.0,0.1,0.0,0.5,0.0,52.2,93.0,43.9,926.7,1316.5,635.2,3133.5,2196.6,1342.8,630.6,1135.2,3.5,0.1,0.7,17289.8,430.5,1406.1,426.7,255.6,21.8,21.6,6.8,0.0,5.5,560.0,196.0,0.0,3893.8,0.8,34.5,15.4,0.0,511.6,517.7,1219.6,4856.8,0.1,1.1,33.9,2.0,2.3,156.0,54.2,2.0,0.1,0.1,57.0,0.1,0.1,44.8,0.1,0.0,0.1,43801.1
20,Manufacture of other transport equipment,22.5,1.4,0.2,3.8,0.0,4.8,28.1,0.0,0.0,0.0,0.1,0.0,12.0,21.3,10.0,212.1,301.3,145.4,717.2,502.8,307.3,144.3,259.8,0.8,0.0,0.2,3957.5,98.5,321.8,97.7,58.5,5.0,5.0,1.6,0.0,1.3,128.2,44.9,0.0,891.3,0.2,7.9,3.5,0.0,117.1,118.5,279.1,1111.7,0.0,0.3,7.8,0.4,0.5,35.7,12.4,0.5,0.0,0.0,13.1,0.0,0.0,10.3,0.0,0.0,0.0,10025.7
21,Manufacture of furniture; other manufacturing,25.9,1.6,0.2,4.4,0.0,5.6,32.4,0.0,0.0,0.0,0.1,0.0,13.8,24.5,11.6,244.6,347.4,167.6,826.9,579.7,354.3,166.4,299.6,0.9,0.0,0.2,4562.6,113.6,371.0,112.6,67.5,5.8,5.7,1.8,0.0,1.5,147.8,51.7,0.0,1027.6,0.2,9.1,4.1,0.0,135.0,136.6,321.8,1281.7,0.0,0.3,8.9,0.5,0.6,41.2,14.3,0.5,0.0,0.0,15.1,0.0,0.0,11.8,0.0,0.0,0.0,11558.7
22,Repair and installation of machinery and equipment,21.9,1.3,0.2,3.7,0.0,4.7,27.4,0.0,0.0,0.0,0.1,0.0,11.7,20.8,9.8,206.9,293.9,141.8,699.5,490.3,299.7,140.8,253.4,0.8,0.0,0.2,3859.6,96.1,313.9,95.3,57.1,4.9,4.8,1.5,0.0,1.2,125.0,43.7,0.0,869.2,0.2,7.7,3.4,0.0,114.2,115.6,272.2,1084.2,0.0,0.2,7.6,0.4,0.5,34.8,12.1,0.5,0.0,0.0,12.7,0.0,0.0,10.0,0.0,0.0,0.0,9777.8
23,"Electricity, gas, steam and air conditioning supply",336.3,20.6,2.5,57.3,0.0,72.4,419.9,0.0,0.3,0.0,1.9,0.0,178.9,318.4,150.3,3173.2,4507.8,2174.9,10729.5,7521.3,4597.8,2159.1,3886.9,11.9,0.5,2.5,59202.0,1474.2,4814.5,1461.1,875.3,74.6,74.1,23.2,0.0,18.9,1917.6,671.1,0.0,13332.9,2.6,118.0,52.7,0.0,1751.9,1772.6,4175.9,16630.1,0.3,3.8,116.1,6.7,7.7,534.0,185.4,6.9,0.4,0.4,195.3,0.4,0.4,153.5,0.3,0.0,0.4,149979.6
24,"Water collection, treatment and supply",19.2,1.2,0.1,3.3,0.0,4.1,24.0,0.0,0.0,0.0,0.1,0.0,10.2,18.2,8.6,181.0,257.2,124.1,612.2,429.1,262.3,123.2,221.8,0.7,0.0,0.1,3377.8,84.1,274.7,83.4,49.9,4.3,4.2,1.3,0.0,1.1,109.4,38.3,0.0,760.7,0.1,6.7,3.0,0.0,100.0,101.1,238.3,948.8,0.0,0.2,6.6,0.4,0.4,30.5,10.6,0.4,0.0,0.0,11.1,0.0,0.0,8.8,0.0,0.0,0.0,8557.2
25,"Sewerage, waste management, remediation activities",63.9,3.9,0.5,10.9,0.0,13.8,79.8,0.0,0.0,0.0,0.4,0.0,34.0,60.5,28.5,602.7,856.2,413.1,2037.8,1428.5,873.2,410.1,738.2,2.3,0.1,0.5,11244.2,280.0,914.4,277.5,166.2,14.2,14.1,4.4,0.0,3.6,364.2,127.5,0.0,2532.3,0.5,22.4,10.0,0.0,332.7,336.7,793.1,3158.6,0.1,0.7,22.0,1.3,1.5,101.4,35.2,1.3,0.1,0.1,37.1,0.1,0.1,29.1,0.1,0.0,0.1,28485.5
26,Construction,151.8,9.3,1.1,25.9,0.0,32.7,189.6,0.0,0.1,0.0,0.8,0.0,80.8,143.8,67.9,1432.7,2035.3,982.0,4844.3,3395.8,2075.9,974.8,1754.9,5.4,0.2,1.1,26729.5,665.6,2173.7,659.7,395.2,33.7,33.5,10.5,0.0,8.5,865.8,303.0,0.0,6019.8,1.2,53.3,23.8,0.0,791.0,800.3,1885.4,7508.4,0.1,1.7,52.4,3.0,3.5,241.1,83.7,3.1,0.2,0.2,88.2,0.2,0.2,69.3,0.2,0.0,0.2,67715.2
27,Wholesale and retail trade and repair of motor vehicles and motorcycles,84.1,5.2,0.6,14.3,0.0,18.1,105.1,0.0,0.1,0.0,0.5,0.0,44.8,79.7,37.6,794.0,1128.0,544.2,2684.9,1882.1,1150.5,540.3,972.6,3.0,0.1,0.6,14814.4,368.9,1204.7,365.6,219.0,18.7,18.5,5.8,0.0,4.7,479.9,167.9,0.0,3336.4,0.6,29.5,13.2,0.0,438.4,443.6,1045.0,4161.4,0.1,1.0,29.0,1.7,1.9,133.6,46.4,1.7,0.1,0.1,48.9,0.1,0.1,38.4,0.1,0.0,0.1,37530.0
28,"Wholesale trade, except of motor vehicles and motorcycles",321.3,19.7,2.4,54.7,0.0,69.2,401.2,0.0,0.2,0.0,1.8,0.0,170.9,304.2,143.6,3031.5,4306.5,2077.8,10250.3,7185.4,4392.4,2062.7,3713.3,11.4,0.5,2.4,56558.3,1408.3,4599.5,1395.8,836.2,71.3,70.8,22.2,0.0,18.1,1832.0,641.1,0.0,12737.5,2.5,112.7,50.3,0.0,1673.6,1693.5,3989.4,15887.5,0.3,3.6,110.9,6.4,7.4,510.2,177.2,6.6,0.4,0.4,186.6,0.4,0.4,146.6,0.3,0.0,0.4,143282.1
29,"Retail trade, except of motor vehicles and motorcycles",248.0,15.2,1.9,42.3,0.0,53.4,309.7,0.0,0.2,0.0,1.4,0.0,131.9,234.8,110.8,2340.2,3324.5,1604.0,7913.0,5546.9,3390.8,1592.3,2866.6,8.8,0.4,1.9,43661.4,1087.2,3550.7,1077.6,645.6,55.1,54.7,17.1,0.0,14.0,1414.2,494.9,0.0,9833.0,1.9,87.0,38.9,0.0,1292.0,1307.3,3079.7,12264.7,0.2,2.8,85.6,4.9,5.7,393.8,136.8,5.1,0.3,0.3,144.0,0.3,0.3,113.2,0.2,0.0,0.3,110609.7
30,Land transport and transport via pipelines,91.3,5.6,0.7,15.6,0.0,19.7,114.0,0.0,0.1,0.0,0.5,0.0,48.6,86.4,40.8,861.2,1223.4,590.3,2912.0,2041.3,1247.8,586.0,1054.9,3.2,0.1,0.7,16067.3,400.1,1306.6,396.5,237.6,20.3,20.1,6.3,0.0,5.1,520.4,182.1,0.0,3618.5,0.7,32.0,14.3,0.0,475.5,481.1,1133.3,4513.4,0.1,1.0,31.5,1.8,2.1,144.9,50.3,1.9,0.1,0.1,53.0,0.1,0.1,41.6,0.1,0.0,0.1,40704.3
31,Water transport,15.0,0.9,0.1,2.6,0.0,3.2,18.8,0.0,0.0,0.0,0.1,0.0,8.0,14.2,6.7,141.9,201.5,97.2,479.7,336.3,205.6,96.5,173.8,0.5,0.0,0.1,2646.8,65.9,215.2,65.3,39.1,3.3,3.3,1.0,0.0,0.8,85.7,30.0,0.0,596.1,0.1,5.3,2.4,0.0,78.3,79.2,186.7,743.5,0.0,0.2,5.2,0.3,0.3,23.9,8.3,0.3,0.0,0.0,8.7,0.0,0.0,6.9,0.0,0.0,0.0,6705.3
32,Air transport,7.6,0.5,0.1,1.3,0.0,1.6,9.5,0.0,0.0,0.0,0.0,0.0,4.0,7.2,3.4,71.8,102.0,49.2,242.8,170.2,104.0,48.9,88.0,0.3,0.0,0.1,1339.8,33.4,109.0,33.1,19.8,1.7,1.7,0.5,0.0,0.4,43.4,15.2,0.0,301.7,0.1,2.7,1.2,0.0,39.6,40.1,94.5,376.3,0.0,0.1,2.6,0.2,0.2,12.1,4.2,0.2,0.0,0.0,4.4,0.0,0.0,3.5,0.0,0.0,0.0,3394.1
33,Warehousing and support activities for transportation,90.0,5.5,0.7,15.3,0.0,19.4,112.4,0.0,0.1,0.0,0.5,0.0,47.9,85.2,40.2,849.5,1206.8,582.3,2872.4,2013.6,1230.9,578.0,1040.6,3.2,0.1,0.7,15849.2,394.7,1288.9,391.2,234.3,20.0,19.8,6.2,0.0,5.1,513.4,179.7,0.0,3569.4,0.7,31.6,14.1,0.0,469.0,474.6,1117.9,4452.1,0.1,1.0,31.1,1.8,2.1,143.0,49.6,1.9,0.1,0.1,52.3,0.1,0.1,41.1,0.1,0.0,0.1,40151.7
34,Postal and courier activities,21.2,1.3,0.2,3.6,0.0,4.6,26.5,0.0,0.0,0.0,0.1,0.0,11.3,20.1,9.5,200.1,284.2,137.1,676.5,474.2,289.9,136.1,245.1,0.8,0.0,0.2,3732.7,92.9,303.6,92.1,55.2,4.7,4.7,1.5,0.0,1.2,120.9,42.3,0.0,840.7,0.2,7.4,3.3,0.0,110.5,111.8,263.3,1048.5,0.0,0.2,7.3,0.4,0.5,33.7,11.7,0.4,0.0,0.0,12.3,0.0,0.0,9.7,0.0,0.0,0.0,9456.3
35,Accommodation and food service activities,181.0,11.1,1.4,30.8,0.0,39.0,226.0,0.0,0.1,0.0,1.0,0.0,96.3,171.4,80.9,1708.0,2426.4,1170.7,5775.3,4048.5,2474.8,1162.2,2092.2,6.4,0.3,1.4,31866.5,793.5,2591.5,786.5,471.2,40.2,39.9,12.5,0.0,10.2,1032.2,361.2,0.0,7176.7,1.4,63.5,28.4,0.0,943.0,954.1,2247.8,8951.5,0.2,2.0,62.5,3.6,4.2,287.4,99.8,3.7,0.2,0.2,105.1,0.2,0.2,82.6,0.2,0.0,0.2,80729.1
36,Publishing activities,39.9,2.4,0.3,6.8,0.0,8.6,49.8,0.0,0.0,0.0,0.2,0.0,21.2,37.8,17.8,376.5,534.9,258.1,1273.1,892.4,545.5,256.2,461.2,1.4,0.1,0.3,7024.5,174.9,571.3,173.4,103.9,8.9,8.8,2.8,0.0,2.2,227.5,79.6,0.0,1582.0,0.3,14.0,6.3,0.0,207.9,210.3,495.5,1973.2,0.0,0.5,13.8,0.8,0.9,63.4,22.0,0.8,0.0,0.0,23.2,0.0,0.0,18.2,0.0,0.0,0.0,17795.6
37,"Motion picture, video, television programme production; programming and broadcasting activities",26.2,1.6,0.2,4.5,0.0,5.6,32.7,0.0,0.0,0.0,0.1,0.0,13.9,24.8,11.7,247.1,351.1,169.4,835.7,585.8,358.1,168.2,302.7,0.9,0.0,0.2,4611.1,114.8,375.0,113.8,68.2,5.8,5.8,1.8,0.0,1.5,149.4,52.3,0.0,1038.5,0.2,9.2,4.1,0.0,136.4,138.1,325.2,1295.3,0.0,0.3,9.0,0.5,0.6,41.6,14.4,0.5,0.0,0.0,15.2,0.0,0.0,12.0,0.0,0.0,0.0,11681.5
38,Telecommunications,43.7,2.7,0.3,7.5,0.0,9.4,54.6,0.0,0.0,0.0,0.2,0.0,23.3,41.4,19.6,412.8,586.4,282.9,1395.8,978.5,598.1,280.9,505.7,1.6,0.1,0.3,7701.7,191.8,626.3,190.1,113.9,9.7,9.6,3.0,0.0,2.5,249.5,87.3,0.0,1734.5,0.3,15.3,6.9,0.0,227.9,230.6,543.2,2163.4,0.0,0.5,15.1,0.9,1.0,69.5,24.1,0.9,0.0,0.1,25.4,0.1,0.0,20.0,0.0,0.0,0.0,19511.1
39,"Computer programming, consultancy, and information service activities",150.8,9.2,1.1,25.7,0.0,32.5,188.3,0.0,0.1,0.0,0.8,0.0,80.2,142.8,67.4,1422.8,2021.3,975.2,4811.0,3372.5,2061.6,968.1,1742.9,5.3,0.2,1.1,26545.7,661.0,2158.8,655.1,392.5,33.5,33.2,10.4,0.0,8.5,859.9,300.9,0.0,5978.4,1.2,52.9,23.6,0.0,785.5,794.8,1872.4,7456.8,0.1,1.7,52.0,3.0,3.5,239.5,83.2,3.1,0.2,0.2,87.6,0.2,0.2,68.8,0.2,0.0,0.2,67249.7
40,"Financial service activities, except insurance and pension funding",59.8,3.7,0.5,10.2,0.0,12.9,74.6,0.0,0.0,0.0,0.3,0.0,31.8,56.6,26.7,564.0,801.2,386.6,1907.0,1336.8,817.2,383.7,690.8,2.1,0.1,0.4,10522.0,262.0,855.7,259.7,155.6,13.3,13.2,4.1,0.0,3.4,340.8,119.3,0.0,2369.7,0.5,21.0,9.4,0.0,311.4,315.0,742.2,2955.7,0.1,0.7,20.6,1.2,1.4,94.9,33.0,1.2,0.1,0.1,34.7,0.1,0.1,27.3,0.1,0.0,0.1,26656.0
41,"Insurance, reinsurance and pension funding, except compulsory social security",14.4,0.9,0.1,2.5,0.0,3.1,18.0,0.0,0.0,0.0,0.1,0.0,7.7,13.6,6.4,135.9,193.1,93.2,459.6,322.2,196.9,92.5,166.5,0.5,0.0,0.1,2535.8,63.1,206.2,62.6,37.5,3.2,3.2,1.0,0.0,0.8,82.1,28.7,0.0,571.1,0.1,5.1,2.3,0.0,75.0,75.9,178.9,712.3,0.0,0.2,5.0,0.3,0.3,22.9,7.9,0.3,0.0,0.0,8.4,0.0,0.0,6.6,0.0,0.0,0.0,6424.0
42,Activities auxiliary to financial services and insurance activities,13.7,0.8,0.1,2.3,0.0,2.9,17.1,0.0,0.0,0.0,0.1,0.0,7.3,12.9,6.1,128.9,183.1,88.3,435.7,305.5,186.7,87.7,157.9,0.5,0.0,0.1,2404.3,59.9,195.5,59.3,35.5,3.0,3.0,0.9,0.0,0.8,77.9,27.3,0.0,541.5,0.1,4.8,2.1,0.0,71.1,72.0,169.6,675.4,0.0,0.2,4.7,0.3,0.3,21.7,7.5,0.3,0.0,0.0,7.9,0.0,0.0,6.2,0.0,0.0,0.0,6090.9

In [78]:
#TEST

correctionCoef = sum(buyingSectorsPurchases)/mini_naio.iloc[0,6]

In [79]:
#TEST 
#control test to understand how to fix invTableNama below
v=[0]*3
for i in range(65):
    v[0]+=invTableNama.iloc[i,20] #*buyingSectorsPurchases[i]
    v[1]+=invTableNama.iloc[i,21] #*buyingSectorsPurchases[i]
    v[2]+=invTableNama.iloc[i,27] #*buyingSectorsPurchases[i]
v

[146138.27102862057, 89334.33182032903, 1150294.2001160253]

In [80]:
#TEST 
sum(buyingSectorsPurchases)

2914103.387763791

In [81]:
#TEST 
print(GrossFixedCapitalFormation[19]*correctionCoef,\
      GrossFixedCapitalFormation[20]*correctionCoef,\
      GrossFixedCapitalFormation[26]*correctionCoef)

146138.27058847938 89334.33155127066 1150294.196651554

Correct correspondence of the above results, calculated in two ways

**Gross capital formation** in mini_naio is related to substitutions & new investment; our analysis here, useful to build the investment
IO transaction table, has the buyer side coming, as volumes, from the simulation of the firms' subsitution.

The total of Gross capital formation, i.e., **3320258.70** (mini_naio.iloc[0,6]), has to be reproportionated to the amount of investment on buyer side of the simulation, sum(buyingSectorsPurchases) using a correctionCoef

In [82]:
sum(buyingSectorsPurchases)

2914103.387763791

In [83]:
correctionCoef = sum(buyingSectorsPurchases)/mini_naio.iloc[0,6]

In [84]:
correctionCoef

np.float64(0.8776735944593085)

In [85]:
#construction special case
constructions = (nama['Dwellings'] + nama['Other buildings']).squeeze()
totConstructions = constructions.sum()
#shares from nama
constructionShares = [x / totConstructions for x in constructions]
constructionShares.append(1.0)
constructionShares = pd.Series(constructionShares)


#setting constructions in invTableNama
salesFromMiniNaioConstructions = mini_naio.iloc[27,6]*correctionCoef
invTableNama['Constructions and construction works'] = constructionShares * salesFromMiniNaioConstructions

constructions

In [86]:
totConstructions

np.float64(282889.0)

In [87]:
nama['Dwellings'].sum()+nama['Other buildings'].sum()

np.float64(282889.0)

In [88]:
invTableNama['Constructions and construction works']

0       5720.4
1        657.9
2        135.4
3      11378.1
4      21540.9
5       2769.5
6        832.0
7        428.2
8        210.6
9       1617.5
10      7688.0
11      9970.0
12      1230.9
13      1163.8
14       842.9
15      1495.6
16      4426.1
17      2184.4
18      6920.3
19       813.2
20       257.8
21      2621.1
22       765.7
23     11781.5
24      4577.0
25      6278.7
26     74345.1
27       797.4
28      4453.3
29      6423.0
30      4061.8
31       522.1
32       427.8
33     18202.5
34       159.4
35     51423.3
36       503.4
37        77.7
38     34261.7
39      9538.2
40      6941.1
41       120.4
42       246.4
43    628662.1
44     72607.2
45       798.2
46      1247.5
47      6339.7
48       213.9
49       832.4
50       407.4
51        58.1
52        51.6
53       875.5
54     46498.7
55      6180.7
56     38350.3
57     20841.1
58      2134.8
59      1857.1
60      1226.8
61        75.6
62       223.6
63         0.0
64         0.0
65   1150294.2
Name: Constructions and construction works, dtype: float64

In [89]:
invTableNama

,sectors,"Products of agriculture, hunting and related services","Products of forestry, logging and related services",Fish and other fishing products; aquaculture products; support services to fishing,Mining and quarrying,"Food, beverages and tobacco products","Textiles, wearing apparel, leather and related products","Wood and of products of wood and cork, except furniture; articles of straw and plaiting materials",Paper and paper products,Printing and recording services,Coke and refined petroleum products,Chemicals and chemical products,Basic pharmaceutical products and pharmaceutical preparations,Rubber and plastic products,Other non-metallic mineral products,Basic metals,"Fabricated metal products, except machinery and equipment","Computer, electronic and optical products",Electrical equipment,Machinery and equipment n.e.c.,"Motor vehicles, trailers and semi-trailers",Other transport equipment,Furniture and other manufactured goods,Repair and installation services of machinery and equipment,"Electricity, gas, steam and air conditioning",Natural water; water treatment and supply services,"Sewerage services; sewage sludge; waste collection, treatment and disposal services; materials recovery services; remediation services and other waste management services",Constructions and construction works,Wholesale and retail trade and repair services of motor vehicles and motorcycles,"Wholesale trade services, except of motor vehicles and motorcycles","Retail trade services, except of motor vehicles and motorcycles",Land transport services and transport services via pipelines,Water transport services,Air transport services,Warehousing and support services for transportation,Postal and courier services,Accommodation and food services,Publishing services,"Motion picture, video and television programme production services, sound recording and music publishing; programming and broadcasting services",Telecommunications services,"Computer programming, consultancy and related services; Information services","Financial services, except insurance and pension funding","Insurance, reinsurance and pension funding services, except compulsory social security",Services auxiliary to financial services and insurance services,Imputed rents of owner-occupied dwellings,Real estate services excluding imputed rents,Legal and accounting services; services of head offices; management consultancy services,Architectural and engineering services; technical testing and analysis services,Scientific research and development services,Advertising and market research services,"Other professional, scientific and technical services and veterinary services",Rental and leasing services,Employment services,"Travel agency, tour operator and other reservation services and related services","Security and investigation services; services to buildings and landscape; office administrative, office support and other business support services",Public administration and defence services; compulsory social security services,Education services,Human health services,Residential care services; social work services without accommodation,"Creative, arts, entertainment, library, archive, museum, other cultural services; gambling and betting services",Sporting services and amusement and recreation services,Services furnished by membership organisations,Repair services of computers and personal and household goods,Other personal services,Services of households as employers; undifferentiated goods and services produced by households for own use,Services provided by extraterritorial organisations and bodies,Totals
0,"Crop and animal production, hunting and related service activities",195.7,12.0,1.5,33.3,0.0,42.2,244.3,0.0,0.2,0.0,1.1,0.0,104.1,185.3,87.5,1846.4,2623.0,1265.5,6243.2,4376.5,2675.3,1256.3,2261.7,6.9,0.3,1.5,5720.4,857.8,2801.4,850.2,509.3,43.4,43.1,13.5,0.0,11.0,1115.8,390.5,0.0,7758.1,1.5,68.7,30.7,0.0,1019.4,1031.4,2429.9,9676.7,0.2,2.2,67.5,3.9,4.5,310.7,107.9,4.0,0.2,0.2,113.6,0.2,0.2,89.3,0.2,0.0,0.2,87269.7
1,Forestry and logging,23.5,1.4,0.2,4.0,0.0,5.1,29.3,0.0,0.0,0.0,0.1,0.0,12.5,22.2,10.5,221.6,314.8,151.9,749.3,525.3,321.1,150.8,271.5,0.8,0.0,0.2,657.9,103.0,336.2,102.0,61.1,5.2,5.2,1.6,0.0,1.3,133.9,46.9,0.0,931.1,0.2,8.2,3.7,0.0,122.3,123.8,291.6,1161.4,0.0,0.3,8.1,0.5,0.5,37.3,13.0,0.5,0.0,0.0,13.6,0.0,0.0,10.7,0.0,0.0,0.0,10474.2
2,Fishing and aquaculture,7.4,0.5,0.1,1.3,0.0,1.6,9.3,0.0,0.0,0.0,0.0,0.0,4.0,7.0,3.3,70.1,99.6,48.1,237.1,166.2,101.6,47.7,85.9,0.3,0.0,0.1,135.4,32.6,106.4,32.3,19.3,1.6,1.6,0.5,0.0,0.4,42.4,14.8,0.0,294.7,0.1,2.6,1.2,0.0,38.7,39.2,92.3,367.5,0.0,0.1,2.6,0.1,0.2,11.8,4.1,0.2,0.0,0.0,4.3,0.0,0.0,3.4,0.0,0.0,0.0,3314.7
3,Mining and quarrying,44.2,2.7,0.3,7.5,0.0,9.5,55.2,0.0,0.0,0.0,0.2,0.0,23.5,41.8,19.7,416.9,592.2,285.7,1409.5,988.0,604.0,283.6,510.6,1.6,0.1,0.3,11378.1,193.7,632.5,191.9,115.0,9.8,9.7,3.1,0.0,2.5,251.9,88.2,0.0,1751.5,0.3,15.5,6.9,0.0,230.1,232.9,548.6,2184.7,0.0,0.5,15.2,0.9,1.0,70.2,24.4,0.9,0.0,0.1,25.7,0.1,0.1,20.2,0.0,0.0,0.0,19702.4
4,Manufacture of food products; beverages and tobacco products,93.3,5.7,0.7,15.9,0.0,20.1,116.5,0.0,0.1,0.0,0.5,0.0,49.7,88.4,41.7,880.7,1251.1,603.6,2977.8,2087.4,1276.0,599.2,1078.8,3.3,0.1,0.7,21540.9,409.1,1336.2,405.5,242.9,20.7,20.6,6.5,0.0,5.3,532.2,186.2,0.0,3700.4,0.7,32.7,14.6,0.0,486.2,492.0,1159.0,4615.4,0.1,1.1,32.2,1.9,2.1,148.2,51.5,1.9,0.1,0.1,54.2,0.1,0.1,42.6,0.1,0.0,0.1,41624.6
5,"Manufacture of textiles, wearing apparel, leather and related products",14.8,0.9,0.1,2.5,0.0,3.2,18.4,0.0,0.0,0.0,0.1,0.0,7.8,14.0,6.6,139.2,197.8,95.4,470.7,330.0,201.7,94.7,170.5,0.5,0.0,0.1,2769.5,64.7,211.2,64.1,38.4,3.3,3.3,1.0,0.0,0.8,84.1,29.4,0.0,584.9,0.1,5.2,2.3,0.0,76.9,77.8,183.2,729.6,0.0,0.2,5.1,0.3,0.3,23.4,8.1,0.3,0.0,0.0,8.6,0.0,0.0,6.7,0.0,0.0,0.0,6579.5
6,"Manufacture of wood and of products of wood and cork, except furniture; manufacture of articles of straw and plaiting materials",14.4,0.9,0.1,2.5,0.0,3.1,18.0,0.0,0.0,0.0,0.1,0.0,7.7,13.6,6.4,135.8,192.9,93.1,459.1,321.8,196.7,92.4,166.3,0.5,0.0,0.1,832.0,63.1,206.0,62.5,37.5,3.2,3.2,1.0,0.0,0.8,82.1,28.7,0.0,570.5,0.1,5.0,2.3,0.0,75.0,75.8,178.7,711.6,0.0,0.2,5.0,0.3,0.3,22.8,7.9,0.3,0.0,0.0,8.4,0.0,0.0,6.6,0.0,0.0,0.0,6417.3
7,Manufacture of paper and paper products,11.5,0.7,0.1,2.0,0.0,2.5,14.4,0.0,0.0,0.0,0.1,0.0,6.1,10.9,5.2,108.8,154.6,74.6,367.9,257.9,157.7,74.0,133.3,0.4,0.0,0.1,428.2,50.6,165.1,50.1,30.0,2.6,2.5,0.8,0.0,0.6,65.8,23.0,0.0,457.2,0.1,4.0,1.8,0.0,60.1,60.8,143.2,570.3,0.0,0.1,4.0,0.2,0.3,18.3,6.4,0.2,0.0,0.0,6.7,0.0,0.0,5.3,0.0,0.0,0.0,5143.1
8,Printing and reproduction of recorded media,5.9,0.4,0.0,1.0,0.0,1.3,7.4,0.0,0.0,0.0,0.0,0.0,3.1,5.6,2.6,55.8,79.2,38.2,188.5,132.2,80.8,37.9,68.3,0.2,0.0,0.0,210.6,25.9,84.6,25.7,15.4,1.3,1.3,0.4,0.0,0.3,33.7,11.8,0.0,234.3,0.0,2.1,0.9,0.0,30.8,31.1,73.4,292.2,0.0,0.1,2.0,0.1,0.1,9.4,3.3,0.1,0.0,0.0,3.4,0.0,0.0,2.7,0.0,0.0,0.0,2635.2
9,Manufacture of coke and refined petroleum products,23.8,1.5,0.2,4.1,0.0,5.1,29.7,0.0,0.0,0.0,0.1,0.0,12.7,22.5,10.6,224.5,319.0,153.9,759.2,532.2,325.3,152.8,275.0,0.8,0.0,0.2,1617.5,104.3,340.7,103.4,61.9,5.3,5.2,1.6,0.0,1.3,135.7,47.5,0.0,943.4,0.2,8.3,3.7,0.0,124.0,125.4,295.5,1176.7,0.0,0.3,8.2,0.5,0.5,37.8,13.1,0.5,0.0,0.0,13.8,0.0,0.0,10.9,0.0,0.0,0.0,10611.9
10,Manufacture of chemicals and chemical products,124.9,7.7,0.9,21.3,0.0,26.9,156.0,0.0,0.1,0.0,0.7,0.0,66.4,118.2,55.8,1178.5,1674.1,807.7,3984.8,2793.3,1707.5,801.9,1443.5,4.4,0.2,0.9,7688.0,547.5,1788.0,542.6,325.1,27.7,27.5,8.6,0.0,7.0,712.2,249.2,0.0,4951.7,1.0,43.8,19.6,0.0,650.6,658.3,1550.9,6176.2,0.1,1.4,43.1,2.5,2.9,198.3,68.9,2.6,0.1,0.2,72.5,0.2,0.1,57.0,0.1,0.0,0.1,55700.5
11,Manufacture of basic pharmaceutical products and pharmaceutical preparations,136.8,8.4,1.0,23.3,0.0,29.5,170.9,0.0,0.1,0.0,0.8,0.0,72.8,129.6,61.2,1291.2,1834.2,885.0,4365.8,3060.4,1870.8,878.5,1581.6,4.9,0.2,1.0,9970.0,599.8,1959.0,594.5,356.2,30.4,30.2,9.5,0.0,7.7,780.3,273.1,0.0,5425.2,1.0,48.0,21.4,0.0,712.8,721.3,1699.2,6766.8,0.1,1.5,47.2,2.7,3.1,217.3,75.5,2.8,0.2,0.2,79.5,0.2,0.2,62.4,0.1,0.0,0.2,61026.5
12,Manufacture of rubber and plastic products,28.0,1.7,0.2,4.8,0.0,6.0,35.0,0.0,0.0,0.0,0.2,0.0,14.9,26.5,12.5,264.4,375.6,181.2,894.0,626.7,383.1,179.9,323.9,1.0,0.0,0.2,1230.9,122.8,401.1,121.7,72.9,6.2,6.2,1.9,0.0,1.6,159.8,55.9,0.0,1110.9,0.2,9.8,4.4,0.0,146.0,147.7,347.9,1385.6,0.0,0.3,9.7,0.6,0.6,44.5,15.5,0.6,0.0,0.0,16.3,0.0,0.0,12.8,0.0,0.0,0.0,12496.1
13,Manufacture of other non-metallic mineral products,32.4,2.0,0.2,5.5,0.0,7.0,40.4,0.0,0.0,0.0,0.2,0.0,17.2,30.6,14.5,305.3,433.7,209.3,1032.4,723.7,442.4,207.7,374.0,1.1,0.0,0.2,1163.8,141.8,463.2,140.6,84.2,7.2,7.1,2.2,0.0,1.8,184.5,64.6,0.0,1282.9,0.2,11.4,5.1,0.0,168.6,170.6,401.8,1600.1,0.0,0.4,11.2,0.6,0.7,51.4,17.8,0.7,0.0,0.0,18.8,0.0,0.0,14.8,0.0,0.0,0.0,14430.8
14,Manufacture of basic metals,29.1,1.8,0.2,5.0,0.0,6.3,36.4,0.0,0.0,0.0,0.2,0.0,15.5,27.6,13.0,274.8,390.4,188.4,929.3,651.4,398.2,187.0,336.6,1.0,0.0,0.2,842.9,127.7,417.0,126.5,75.8,6.5,6.4,2.0,0.0,1.6,166.1,58.1,0.0,1154.7,0.2,10.2,4.6,0.0,151.7,153.5,361.7,1440.3,0.0,0.3,10.1,0.6,0.7,46.3,16.1,0.6,0.0,0.0,16.9,0.0,0.0,13.3,0.0,0.0,0.0,12989.5
15,"Manufacture of fabricated metal products, except machinery and equipment",64.5,4.0,0.5,11.0,0.0,13.9,80.6,0.0,0.0,0.0,0.4,0.0,34.3,61.1,28.8,608.9,865.0,417.4,2058.9,1443.3,882.3,414.3,745.9,2.3,0.1,0.5,1495.6,282.9,923.9,280.4,168.0,14.3,14.2,4.5,0.0,3.6,368.0,128.8,0.0,2558.5,0.5,22.6,10.1,0.0,336.2,340.2,801.3,3191.2,0.1,0.7,22.3,1.3,1.5,102.5,35.6,1.3,0.1,0.1,37.5,0.1,0.1,29.4,0.1,0.0,0.1,28780.0
16,"Manufacture of computer, electronic and optical products",58.7,3.6,0.4,10.0,0.0,12.6,73.3,0.0,0.0,0.0,0.3,0.0,31.2,55.6,26.2,554.1,787.1,379.8,1873.4,1313.3,802.8,377.0,678.7,2.1,0.1,0.4,4426.1,257.4,840.6,255.1,152.8,13.0,12.9,4.1,0.0,3.3,334.8,117.2,0.0,2328.0,0.4,20.6,9.2,0.0,305.9,309.5,729.1,2903.7,0.1,0.7,20.3,1.2,1.4,93.2,32.4,1.2,0.1,0.1,34.1,0.1,0.1,26.8,0.1,0.0,0.1,26187.4
17,Manufacture of electrical equipment,38.5,2.4,0.3,6.6,0.0,8.3,48.1,0.0,0.0,0.0,0.2,0.0,20.5,36.4,17.2,363.2,516.0,249.0,1228.2,860.9,526.3,247.1,444.9,1.4,0.1,0.3,2184.4,168.7,551.1,167.2,100.2,8.5,8.5,2.7,0.0,2.2,219.5,76.8,0.0,1526.2,0.3,13.5,6.0,0.0,200.5,202.9,478.0,1903.6,0.0,0.4,13.3,0.8,0.9,61.1,21.2,0.8,0.0,0.0,22.4,0.0,0.0,17.6,0.0,0.0,0.0,17167.5
18,Manufacture of machinery and equipment n.e.c.,91.9,5.6,0.7,15.7,0.0,19.8,114.8,0.0,0.1,0.0,0.5,0.0,48.9,87.0,41.1,867.5,1232.3,594.6,2933.1,2056.1,1256.9,590.2,1062.6,3.3,0.1,0.7,6920.3,403.0,1316.1,399.4,239.3,20.4,20.3,6.4,0.0,5.2,524.2,183.4,0.0,3644.9,0.7,32.3,14.4,0.0,478.9,484.6,1141.6,4546.2,0.1,1.0,31.7,1.8,2.1,146.0,50.7,1.9,0.1,0.1,53.4,0.1,0.1,42.0,0.1,0.0,0.1,41000.3
19,"Manufacture of motor vehicles, trailers and semi-trailers",98.2,6.0,0.7,16.7,0.0,21.2,122.6,0.0,0.1,0.0,0.5,0.0,52.2,93.0,43.9,926.7,1316.5,635.2,3133.5,2196.6,1342.8,630.6,1135.2,3.5,0.1,0.7,813.2,430.5,1406.1,426.7,255.6,21.8,21.6,6.8,0.0,5.5,560.0,196.0,0.0,3893.8,0.8,34.5,15.4,0.0,511.6,517.7,1219.6,4856.8,0.1,1.1,33.9,2.0,2.3,156.0,54.2,2.0,0.1,0.1,57.0,0.1,0.1,44.8,0.1,0.0,0.1,43801.1
20,Manufacture of other transport equipment,22.5,1.4,0.2,3.8,0.0,4.8,28.1,0.0,0.0,0.0,0.1,0.0,12.0,21.3,10.0,212.1,301.3,145.4,717.2,502.8,307.3,144.3,259.8,0.8,0.0,0.2,257.8,98.5,321.8,97.7,58.5,5.0,5.0,1.6,0.0,1.3,128.2,44.9,0.0,891.3,0.2,7.9,3.5,0.0,117.1,118.5,279.1,1111.7,0.0,0.3,7.8,0.4,0.5,35.7,12.4,0.5,0.0,0.0,13.1,0.0,0.0,10.3,0.0,0.0,0.0,10025.7
21,Manufacture of furniture; other manufacturing,25.9,1.6,0.2,4.4,0.0,5.6,32.4,0.0,0.0,0.0,0.1,0.0,13.8,24.5,11.6,244.6,347.4,167.6,826.9,579.7,354.3,166.4,299.6,0.9,0.0,0.2,2621.1,113.6,371.0,112.6,67.5,5.8,5.7,1.8,0.0,1.5,147.8,51.7,0.0,1027.6,0.2,9.1,4.1,0.0,135.0,136.6,321.8,1281.7,0.0,0.3,8.9,0.5,0.6,41.2,14.3,0.5,0.0,0.0,15.1,0.0,0.0,11.8,0.0,0.0,0.0,11558.7
22,Repair and installation of machinery and equipment,21.9,1.3,0.2,3.7,0.0,4.7,27.4,0.0,0.0,0.0,0.1,0.0,11.7,20.8,9.8,206.9,293.9,141.8,699.5,490.3,299.7,140.8,253.4,0.8,0.0,0.2,765.7,96.1,313.9,95.3,57.1,4.9,4.8,1.5,0.0,1.2,125.0,43.7,0.0,869.2,0.2,7.7,3.4,0.0,114.2,115.6,272.2,1084.2,0.0,0.2,7.6,0.4,0.5,34.8,12.1,0.5,0.0,0.0,12.7,0.0,0.0,10.0,0.0,0.0,0.0,9777.8
23,"Electricity, gas, steam and air conditioning supply",336.3,20.6,2.5,57.3,0.0,72.4,419.9,0.0,0.3,0.0,1.9,0.0,178.9,318.4,150.3,3173.2,4507.8,2174.9,10729.5,7521.3,4597.8,2159.1,3886.9,11.9,0.5,2.5,11781.5,1474.2,4814.5,1461.1,875.3,74.6,74.1,23.2,0.0,18.9,1917.6,671.1,0.0,13332.9,2.6,118.0,52.7,0.0,1751.9,1772.6,4175.9,16630.1,0.3,3.8,116.1,6.7,7.7,534.0,185.4,6.9,0.4,0.4,195.3,0.4,0.4,153.5,0.3,0.0,0.4,149979.6
24,"Water collection, treatment and supply",19.2,1.2,0.1,3.3,0.0,4.1,24.0,0.0,0.0,0.0,0.1,0.0,10.2,18.2,8.6,181.0,257.2,124.1,612.2,429.1,262.3,123.2,221.8,0.7,0.0,0.1,4577.0,84.1,274.7,83.4,49.9,4.3,4.2,1.3,0.0,1.1,109.4,38.3,0.0,760.7,0.1,6.7,3.0,0.0,100.0,101.1,238.3,948.8,0.0,0.2,6.6,0.4,0.4,30.5,10.6,0.4,0.0,0.0,11.1,0.0,0.0,8.8,0.0,0.0,0.0,8557.2
25,"Sewerage, waste management, remediation activities",63.9,3.9,0.5,10.9,0.0,13.8,79.8,0.0,0.0,0.0,0.4,0.0,34.0,60.5,28.5,602.7,856.2,413.1,2037.8,1428.5,873.2,410.1,738.2,2.3,0.1,0.5,6278.7,280.0,914.4,277.5,166.2,14.2,14.1,4.4,0.0,3.6,364.2,127.5,0.0,2532.3,0.5,22.4,10.0,0.0,332.7,336.7,793.1,3158.6,0.1,0.7,22.0,1.3,1.5,101.4,35.2,1.3,0.1,0.1,37.1,0.1,0.1,29.1,0.1,0.0,0.1,28485.5
26,Construction,151.8,9.3,1.1,25.9,0.0,32.7,189.6,0.0,0.1,0.0,0.8,0.0,80.8,143.8,67.9,1432.7,2035.3,982.0,4844.3,3395.8,2075.9,974.8,1754.9,5.4,0.2,1.1,74345.1,665.6,2173.7,659.7,395.2,33.7,33.5,10.5,0.0,8.5,865.8,303.0,0.0,6019.8,1.2,53.3,23.8,0.0,791.0,800.3,1885.4,7508.4,0.1,1.7,52.4,3.0,3.5,241.1,83.7,3.1,0.2,0.2,88.2,0.2,0.2,69.3,0.2,0.0,0.2,67715.2
27,Wholesale and retail trade and repair of motor vehicles and motorcycles,84.1,5.2,0.6,14.3,0.0,18.1,105.1,0.0,0.1,0.0,0.5,0.0,44.8,79.7,37.6,794.0,1128.0,544.2,2684.9,1882.1,1150.5,540.3,972.6,3.0,0.1,0.6,797.4,368.9,1204.7,365.6,219.0,18.7,18.5,5.8,0.0,4.7,479.9,167.9,0.0,3336.4,0.6,29.5,13.2,0.0,438.4,443.6,1045.0,4161.4,0.1,1.0,29.0,1.7,1.9,133.6,46.4,1.7,0.1,0.1,48.9,0.1,0.1,38.4,0.1,0.0,0.1,37530.0
28,"Wholesale trade, except of motor vehicles and motorcycles",321.3,19.7,2.4,54.7,0.0,69.2,401.2,0.0,0.2,0.0,1.8,0.0,170.9,304.2,143.6,3031.5,4306.5,2077.8,10250.3,7185.4,4392.4,2062.7,3713.3,11.4,0.5,2.4,4453.3,1408.3,4599.5,1395.8,836.2,71.3,70.8,22.2,0.0,18.1,1832.0,641.1,0.0,12737.5,2.5,112.7,50.3,0.0,1673.6,1693.5,3989.4,15887.5,0.3,3.6,110.9,6.4,7.4,510.2,177.2,6.6,0.4,0.4,186.6,0.4,0.4,146.6,0.3,0.0,0.4,143282.1
29,"Retail trade, except of motor vehicles and motorcycles",248.0,15.2,1.9,42.3,0.0,53.4,309.7,0.0,0.2,0.0,1.4,0.0,131.9,234.8,110.8,2340.2,3324.5,1604.0,7913.0,5546.9,3390.8,1592.3,2866.6,8.8,0.4,1.9,6423.0,1087.2,3550.7,1077.6,645.6,55.1,54.7,17.1,0.0,14.0,1414.2,494.9,0.0,9833.0,1.9,87.0,38.9,0.0,1292.0,1307.3,3079.7,12264.7,0.2,2.8,85.6,4.9,5.7,393.8,136.8,5.1,0.3,0.3,144.0,0.3,0.3,113.2,0.2,0.0,0.3,110609.7
30,Land transport and transport via pipelines,91.3,5.6,0.7,15.6,0.0,19.7,114.0,0.0,0.1,0.0,0.5,0.0,48.6,86.4,40.8,861.2,1223.4,590.3,2912.0,2041.3,1247.8,586.0,1054.9,3.2,0.1,0.7,4061.8,400.1,1306.6,396.5,237.6,20.3,20.1,6.3,0.0,5.1,520.4,182.1,0.0,3618.5,0.7,32.0,14.3,0.0,475.5,481.1,1133.3,4513.4,0.1,1.0,31.5,1.8,2.1,144.9,50.3,1.9,0.1,0.1,53.0,0.1,0.1,41.6,0.1,0.0,0.1,40704.3
31,Water transport,15.0,0.9,0.1,2.6,0.0,3.2,18.8,0.0,0.0,0.0,0.1,0.0,8.0,14.2,6.7,141.9,201.5,97.2,479.7,336.3,205.6,96.5,173.8,0.5,0.0,0.1,522.1,65.9,215.2,65.3,39.1,3.3,3.3,1.0,0.0,0.8,85.7,30.0,0.0,596.1,0.1,5.3,2.4,0.0,78.3,79.2,186.7,743.5,0.0,0.2,5.2,0.3,0.3,23.9,8.3,0.3,0.0,0.0,8.7,0.0,0.0,6.9,0.0,0.0,0.0,6705.3
32,Air transport,7.6,0.5,0.1,1.3,0.0,1.6,9.5,0.0,0.0,0.0,0.0,0.0,4.0,7.2,3.4,71.8,102.0,49.2,242.8,170.2,104.0,48.9,88.0,0.3,0.0,0.1,427.8,33.4,109.0,33.1,19.8,1.7,1.7,0.5,0.0,0.4,43.4,15.2,0.0,301.7,0.1,2.7,1.2,0.0,39.6,40.1,94.5,376.3,0.0,0.1,2.6,0.2,0.2,12.1,4.2,0.2,0.0,0.0,4.4,0.0,0.0,3.5,0.0,0.0,0.0,3394.1
33,Warehousing and support activities for transportation,90.0,5.5,0.7,15.3,0.0,19.4,112.4,0.0,0.1,0.0,0.5,0.0,47.9,85.2,40.2,849.5,1206.8,582.3,2872.4,2013.6,1230.9,578.0,1040.6,3.2,0.1,0.7,18202.5,394.7,1288.9,391.2,234.3,20.0,19.8,6.2,0.0,5.1,513.4,179.7,0.0,3569.4,0.7,31.6,14.1,0.0,469.0,474.6,1117.9,4452.1,0.1,1.0,31.1,1.8,2.1,143.0,49.6,1.9,0.1,0.1,52.3,0.1,0.1,41.1,0.1,0.0,0.1,40151.7
34,Postal and courier activities,21.2,1.3,0.2,3.6,0.0,4.6,26.5,0.0,0.0,0.0,0.1,0.0,11.3,20.1,9.5,200.1,284.2,137.1,676.5,474.2,289.9,136.1,245.1,0.8,0.0,0.2,159.4,92.9,303.6,92.1,55.2,4.7,4.7,1.5,0.0,1.2,120.9,42.3,0.0,840.7,0.2,7.4,3.3,0.0,110.5,111.8,263.3,1048.5,0.0,0.2,7.3,0.4,0.5,33.7,11.7,0.4,0.0,0.0,12.3,0.0,0.0,9.7,0.0,0.0,0.0,9456.3
35,Accommodation and food service activities,181.0,11.1,1.4,30.8,0.0,39.0,226.0,0.0,0.1,0.0,1.0,0.0,96.3,171.4,80.9,1708.0,2426.4,1170.7,5775.3,4048.5,2474.8,1162.2,2092.2,6.4,0.3,1.4,51423.3,793.5,2591.5,786.5,471.2,40.2,39.9,12.5,0.0,10.2,1032.2,361.2,0.0,7176.7,1.4,63.5,28.4,0.0,943.0,954.1,2247.8,8951.5,0.2,2.0,62.5,3.6,4.2,287.4,99.8,3.7,0.2,0.2,105.1,0.2,0.2,82.6,0.2,0.0,0.2,80729.1
36,Publishing activities,39.9,2.4,0.3,6.8,0.0,8.6,49.8,0.0,0.0,0.0,0.2,0.0,21.2,37.8,17.8,376.5,534.9,258.1,1273.1,892.4,545.5,256.2,461.2,1.4,0.1,0.3,503.4,174.9,571.3,173.4,103.9,8.9,8.8,2.8,0.0,2.2,227.5,79.6,0.0,1582.0,0.3,14.0,6.3,0.0,207.9,210.3,495.5,1973.2,0.0,0.5,13.8,0.8,0.9,63.4,22.0,0.8,0.0,0.0,23.2,0.0,0.0,18.2,0.0,0.0,0.0,17795.6
37,"Motion picture, video, television programme production; programming and broadcasting activities",26.2,1.6,0.2,4.5,0.0,5.6,32.7,0.0,0.0,0.0,0.1,0.0,13.9,24.8,11.7,247.1,351.1,169.4,835.7,585.8,358.1,168.2,302.7,0.9,0.0,0.2,77.7,114.8,375.0,113.8,68.2,5.8,5.8,1.8,0.0,1.5,149.4,52.3,0.0,1038.5,0.2,9.2,4.1,0.0,136.4,138.1,325.2,1295.3,0.0,0.3,9.0,0.5,0.6,41.6,14.4,0.5,0.0,0.0,15.2,0.0,0.0,12.0,0.0,0.0,0.0,11681.5
38,Telecommunications,43.7,2.7,0.3,7.5,0.0,9.4,54.6,0.0,0.0,0.0,0.2,0.0,23.3,41.4,19.6,412.8,586.4,282.9,1395.8,978.5,598.1,280.9,505.7,1.6,0.1,0.3,34261.7,191.8,626.3,190.1,113.9,9.7,9.6,3.0,0.0,2.5,249.5,87.3,0.0,1734.5,0.3,15.3,6.9,0.0,227.9,230.6,543.2,2163.4,0.0,0.5,15.1,0.9,1.0,69.5,24.1,0.9,0.0,0.1,25.4,0.1,0.0,20.0,0.0,0.0,0.0,19511.1
39,"Computer programming, consultancy, and information service activities",150.8,9.2,1.1,25.7,0.0,32.5,188.3,0.0,0.1,0.0,0.8,0.0,80.2,142.8,67.4,1422.8,2021.3,975.2,4811.0,3372.5,2061.6,968.1,1742.9,5.3,0.2,1.1,9538.2,661.0,2158.8,655.1,392.5,33.5,33.2,10.4,0.0,8.5,859.9,300.9,0.0,5978.4,1.2,52.9,23.6,0.0,785.5,794.8,1872.4,7456.8,0.1,1.7,52.0,3.0,3.5,239.5,83.2,3.1,0.2,0.2,87.6,0.2,0.2,68.8,0.2,0.0,0.2,67249.7
40,"Financial service activities, except insurance and pension funding",59.8,3.7,0.5,10.2,0.0,12.9,74.6,0.0,0.0,0.0,0.3,0.0,31.8,56.6,26.7,564.0,801.2,386.6,1907.0,1336.8,817.2,383.7,690.8,2.1,0.1,0.4,6941.1,262.0,855.7,259.7,155.6,13.3,13.2,4.1,0.0,3.4,340.8,119.3,0.0,2369.7,0.5,21.0,9.4,0.0,311.4,315.0,742.2,2955.7,0.1,0.7,20.6,1.2,1.4,94.9,33.0,1.2,0.1,0.1,34.7,0.1,0.1,27.3,0.1,0.0,0.1,26656.0
41,"Insurance, reinsurance and pension funding, except compulsory social security",14.4,0.9,0.1,2.5,0.0,3.1,18.0,0.0,0.0,0.0,0.1,0.0,7.7,13.6,6.4,135.9,193.1,93.2,459.6,322.2,196.9,92.5,166.5,0.5,0.0,0.1,120.4,63.1,206.2,62.6,37.5,3.2,3.2,1.0,0.0,0.8,82.1,28.7,0.0,571.1,0.1,5.1,2.3,0.0,75.0,75.9,178.9,712.3,0.0,0.2,5.0,0.3,0.3,22.9,7.9,0.3,0.0,0.0,8.4,0.0,0.0,6.6,0.0,0.0,0.0,6424.0
42,Activities auxiliary to financial services and insurance activities,13.7,0.8,0.1,2.3,0.0,2.9,17.1,0.0,0.0,0.0,0.1,0.0,7.3,12.9,6.1,128.9,183.1,88.3,435.7,305.5,186.7,87.7,157.9,0.5,0.0,0.1,246.4,59.9,195.5,59.3,35.5,3.0,3.0,0.9,0.0,0.8,77.9,27.3,0.0,541.5,0.1,4.8,2.1,0.0,71.1,72.0,169.6,675.4,0.0,0.2,4.7,0.3,0.3,21.7,7.5,0.3,0.0,0.0,7.9,0.0,0.0,6.2,0.0,0.0,0.0,6090.9

In [90]:
invTableNama.shape

(66, 67)

In [91]:
#TEST after constructions, but before reproportioning
#control test to understand how to fix invTableNama
v=0
for i in range(65):
    v+=invTableNama.iloc[i,27] #*buyingSectorsPurchases[i]
v

np.float64(1150294.196651554)

In [92]:
#TEST
sum(buyingSectorsPurchases)

2914103.387763791

In [93]:
#TEST
print(GrossFixedCapitalFormation[26]*correctionCoef)

1150294.196651554

In [94]:
#as an axample, row 0 true sum
invTableNama.iloc[0,1:-1].sum()

np.float64(58541.799340650956)

In [95]:
#as an axample, row 0 expected sum
invTableNama.iloc[0,-1]

87269.68016368477

In [96]:
#reproportion without modifying the nama sectors

In [97]:
#METHOD 1
#reconcile row totals, not modifying the cols listed in a vector

In [98]:
#num to be used
col_indices = list(enumerate(invTableNama.columns))
col_indices

[(0, 'sectors'),
 (1, 'Products of agriculture, hunting and related services'),
 (2, 'Products of forestry, logging and related services'),
 (3,
  'Fish and other fishing products; aquaculture products; support services to fishing'),
 (4, 'Mining and quarrying'),
 (5, 'Food, beverages and tobacco products'),
 (6, 'Textiles, wearing apparel, leather and related products'),
 (7,
  'Wood and of products of wood and cork, except furniture; articles of straw and plaiting materials'),
 (8, 'Paper and paper products'),
 (9, 'Printing and recording services'),
 (10, 'Coke and refined petroleum products'),
 (11, 'Chemicals and chemical products'),
 (12, 'Basic pharmaceutical products and pharmaceutical preparations'),
 (13, 'Rubber and plastic products'),
 (14, 'Other non-metallic mineral products'),
 (15, 'Basic metals'),
 (16, 'Fabricated metal products, except machinery and equipment'),
 (17, 'Computer, electronic and optical products'),
 (18, 'Electrical equipment'),
 (19, 'Machinery and equipment n.e.c.'),
 (20, 'Motor vehicles, trailers and semi-trailers'),
 (21, 'Other transport equipment'),
 (22, 'Furniture and other manufactured goods'),
 (23, 'Repair and installation services of machinery and equipment'),
 (24, 'Electricity, gas, steam and air conditioning'),
 (25, 'Natural water; water treatment and supply services'),
 (26,
  'Sewerage services; sewage sludge; waste collection, treatment and disposal services; materials recovery services; remediation services and other waste management services'),
 (27, 'Constructions and construction works'),
 (28,
  'Wholesale and retail trade and repair services of motor vehicles and motorcycles'),
 (29, 'Wholesale trade services, except of motor vehicles and motorcycles'),
 (30, 'Retail trade services, except of motor vehicles and motorcycles'),
 (31, 'Land transport services and transport services via pipelines'),
 (32, 'Water transport services'),
 (33, 'Air transport services'),
 (34, 'Warehousing and support services for transportation'),
 (35, 'Postal and courier services'),
 (36, 'Accommodation and food services'),
 (37, 'Publishing services'),
 (38,
  'Motion picture, video and television programme production services, sound recording and music publishing; programming and broadcasting services'),
 (39, 'Telecommunications services'),
 (40,
  'Computer programming, consultancy and related services; Information services'),
 (41, 'Financial services, except insurance and pension funding'),
 (42,
  'Insurance, reinsurance and pension funding services, except compulsory social security'),
 (43, 'Services auxiliary to financial services and insurance services'),
 (44, 'Imputed rents of owner-occupied dwellings'),
 (45, 'Real estate services excluding imputed rents'),
 (46,
  'Legal and accounting services; services of head offices; management consultancy services'),
 (47,
  'Architectural and engineering services; technical testing and analysis services'),
 (48, 'Scientific research and development services'),
 (49, 'Advertising and market research services'),
 (50,
  'Other professional, scientific and technical services and veterinary services'),
 (51, 'Rental and leasing services'),
 (52, 'Employment services'),
 (53,
  'Travel agency, tour operator and other reservation services and related services'),
 (54,
  'Security and investigation services; services to buildings and landscape; office administrative, office support and other business support services'),
 (55,
  'Public administration and defence services; compulsory social security services'),
 (56, 'Education services'),
 (57, 'Human health services'),
 (58, 'Residential care services; social work services without accommodation'),
 (59,
  'Creative, arts, entertainment, library, archive, museum, other cultural services; gambling and betting services'),
 (60, 'Sporting services and amusement and recreation services'),
 (61, 'Services furnished by membership organisations'),
 (62, 'Repair services of computers and personal and household goods'),
 (63, 'Other personal services'),
 (64,
  'Services of households as employers; undifferentiated goods and services produced by households for own use'),
 (65, 'Services provided by extraterritorial organisations and bodies'),
 (66, 'Totals')]

invTableNama

In [99]:
#other sectors to be corrected in invTableNama, besides 'constructions' (special case, above)

In [100]:
nama.columns

Index(['Row index', 'Dwellings', 'Other buildings', 'Transport equipment',
       'Computer hardware', 'Telecommunications', 'Other machinery',
       'Cultivated biological resources', 'R & D', 'Computer software and db'],
      dtype='object')

Sector associations (to be used!) applying shares on the left to cols on the right

    from nama 'Dwellings'                       [1] to mini_naio [27] (done above)

    from nama 'Other buildings'                 [2] to mini_naio [27] (done above)

    from nama 'Transport equipment'             [3] to mini_naio [20, 21]

    from nama 'Computer hardware'               [4] to mini_naio [17]

    from nama 'Telecommunications'              [5] to mini_naio [39]

    from nama 'Other machinery'                 [6] to mini_naio [18, 19, 23]

    from nama 'Cultivated biological resources' [7] to mini_naio [1, 2, 3]

    from nama 'R & D'                           [8] to mini_naio [48]

    from nama 'Computer software and db'        [9] to mini_naio [40]

In [101]:
#substitutions

def substitutions(namaCol,mini_naioRow):
    tot = nama.iloc[:,namaCol].sum()

    #shares from nama
    namaShares = [x / tot for x in nama.iloc[:,namaCol]]
    namaShares.append(1.0)
    namaShares = pd.Series(namaShares)

    salesFromMiniNaio = mini_naio.iloc[mini_naioRow,6]*correctionCoef
    invTableNamaCol=mini_naioRow
    invTableNama.iloc[:,invTableNamaCol] = namaShares * salesFromMiniNaio

substitutions(3,20)
substitutions(3,21)
substitutions(4,17)
substitutions(5,39)
substitutions(6,18)
substitutions(6,19)
substitutions(6,23)
substitutions(7,1)
substitutions(7,2)
substitutions(7,3)
substitutions(8,48)
substitutions(9,40)

In [102]:
#**********************************

# Get all rows and columns except the last one in both directions (the totals) for the IPF calculation below
data_part_for_IPF = invTableNama.iloc[:-1, 1:-1]
data_partNu =data_part_for_IPF.to_numpy()

#**********************************

invTableNama

In [103]:
#Numbers of the cols to be excluded
excluded_cols = [1,2,3,17,18,19,20,21,23,27,39,40,48]
#excluded_cols = [27]
# Get all column indices
all_cols = list(range(invTableNama.shape[1]))
all_cols[1:-1]
#given a row, e.g., 0
invTableNama.iloc[0,1:-1].sum()

np.float64(43595.11229992165)

In [104]:
#all_cols[1:-1]

In [105]:
# Get columns to modify (i.e., those NOT in exclude list)
cols_to_modify = [i for i in all_cols[1:-1] if i not in excluded_cols]
#cols_to_modify

In [106]:
#rows
new_sum=invTableNama.iloc[:,1:-1].sum(axis=1)

In [107]:
#new_sum

In [108]:
#invTableNama['Totals']

In [109]:
diff=invTableNama['Totals'] - new_sum
#diff

In [110]:
#within each row
cols_to_modify_sum = invTableNama.iloc[:, cols_to_modify].sum(axis=1)

In [111]:
#cols_to_modify_sum

In [112]:
type(cols_to_modify_sum)

pandas.core.series.Series

In [113]:
#within each row
excluded_cols_sum = invTableNama.iloc[:, excluded_cols].sum(axis=1)

In [114]:
#excluded_cols_sum

In [115]:
#for each row
correctionsCols_to_modify = [1.0]*len(diff)
correctionsExcludedCols   = [1.0]*len(diff)
for i in range(len(diff)-1):
    if cols_to_modify_sum[i] > 0: 
        correctionsCols_to_modify[i] = 1.0 + diff[i]/cols_to_modify_sum[i]
        if correctionsCols_to_modify[i] < 0.0:
            correctionsCols_to_modify[i] = 0.0
            diff2=diff[i]+cols_to_modify_sum[i] #if here, diff<0 and partially compensated by cols_to_modify_sum[i]
            correctionsExcludedCols[i]=1+diff2/excluded_cols_sum[i]
    if i==26: print(diff[i],diff2,correctionsCols_to_modify[i],correctionsExcludedCols[i])

-124025.4406391142 -111818.35467602708 0.0 0.37717296415524293

In [116]:
#for i in range(len(correctionsCols_to_modify)):
#    print(i,correctionsCols_to_modify[i])

In [117]:
#for i in range(len(correctionsExcludedCols)):
#    print(i,correctionsExcludedCols[i])

In [118]:
#APPLAY CORRECTIONS
for i in range(len(diff)-1):
    for j in range(1,67):
        if j in cols_to_modify:
            invTableNama.iloc[i,j]*=correctionsCols_to_modify[i]
        else:
            invTableNama.iloc[i,j]*=correctionsExcludedCols[i]

In [119]:
# Get all rows and columns except the last one in both directions (the totals)
data_part = invTableNama.iloc[:-1, 1:-1]

#Fill last column with row totals
invTableNama.iloc[:-1, -1] = data_part.sum(axis=1)

#THE LAST COL HAS CHANDED if compared with buying values, see below activating the print

# Fill last row with column totals
invTableNama.iloc[-1, 1:-1] = data_part.sum(axis=0)

#THE LAST ROW HAS CHANGED if compared with GrossFixedCapitalFormation[col]*correctionCoef, see below activating the print

In [120]:
#sum of the last col excluding the last row
invTableNama.iloc[:-1, -1].sum()

2914103.3877637903

In [121]:
#sum of the last row excluding the last col
invTableNama.iloc[-1, 1:-1].sum()

np.float64(2914103.3877637903)

In [122]:
# Fill bottom-right cell with grand total
invTableNama.iloc[-1, -1] = data_part.values.sum()
invTableNama.iloc[-1, -1]

2914103.3877637866

In [123]:
invTableNama.shape[0]

66

tot=0
for i in range(0,65):
    print(invTableNama.iloc[i,-1],buyingSectorsPurchases[i],invTableNama.iloc[i,-1]-buyingSectorsPurchases[i])
    tot+=invTableNama.iloc[i,-1]-buyingSectorsPurchases[i]
print('tot',tot)

In [124]:
invTableNama.shape[1]

67

tot=0
for j in range(1,66):
    print(invTableNama.iloc[-1,j],GrossFixedCapitalFormation[j-1]*correctionCoef,\
          invTableNama.iloc[-1,j]-GrossFixedCapitalFormation[j-1]*correctionCoef)
    tot+=invTableNama.iloc[-1,j]-GrossFixedCapitalFormation[j-1]*correctionCoef
print('tot', tot)

In [125]:
invTableNama

,sectors,"Products of agriculture, hunting and related services","Products of forestry, logging and related services",Fish and other fishing products; aquaculture products; support services to fishing,Mining and quarrying,"Food, beverages and tobacco products","Textiles, wearing apparel, leather and related products","Wood and of products of wood and cork, except furniture; articles of straw and plaiting materials",Paper and paper products,Printing and recording services,Coke and refined petroleum products,Chemicals and chemical products,Basic pharmaceutical products and pharmaceutical preparations,Rubber and plastic products,Other non-metallic mineral products,Basic metals,"Fabricated metal products, except machinery and equipment","Computer, electronic and optical products",Electrical equipment,Machinery and equipment n.e.c.,"Motor vehicles, trailers and semi-trailers",Other transport equipment,Furniture and other manufactured goods,Repair and installation services of machinery and equipment,"Electricity, gas, steam and air conditioning",Natural water; water treatment and supply services,"Sewerage services; sewage sludge; waste collection, treatment and disposal services; materials recovery services; remediation services and other waste management services",Constructions and construction works,Wholesale and retail trade and repair services of motor vehicles and motorcycles,"Wholesale trade services, except of motor vehicles and motorcycles","Retail trade services, except of motor vehicles and motorcycles",Land transport services and transport services via pipelines,Water transport services,Air transport services,Warehousing and support services for transportation,Postal and courier services,Accommodation and food services,Publishing services,"Motion picture, video and television programme production services, sound recording and music publishing; programming and broadcasting services",Telecommunications services,"Computer programming, consultancy and related services; Information services","Financial services, except insurance and pension funding","Insurance, reinsurance and pension funding services, except compulsory social security",Services auxiliary to financial services and insurance services,Imputed rents of owner-occupied dwellings,Real estate services excluding imputed rents,Legal and accounting services; services of head offices; management consultancy services,Architectural and engineering services; technical testing and analysis services,Scientific research and development services,Advertising and market research services,"Other professional, scientific and technical services and veterinary services",Rental and leasing services,Employment services,"Travel agency, tour operator and other reservation services and related services","Security and investigation services; services to buildings and landscape; office administrative, office support and other business support services",Public administration and defence services; compulsory social security services,Education services,Human health services,Residential care services; social work services without accommodation,"Creative, arts, entertainment, library, archive, museum, other cultural services; gambling and betting services",Sporting services and amusement and recreation services,Services furnished by membership organisations,Repair services of computers and personal and household goods,Other personal services,Services of households as employers; undifferentiated goods and services produced by households for own use,Services provided by extraterritorial organisations and bodies,Totals
0,"Crop and animal production, hunting and related service activities",5122.1,314.0,38.6,125.9,0.1,159.2,922.7,0.1,0.6,0.0,4.1,0.0,393.1,699.6,330.2,6972.3,589.4,1449.5,7150.9,2960.8,1809.9,4744.0,2590.5,26.2,1.1,5.5,5720.4,3239.1,10578.6,3210.4,1923.3,164.0,162.8,51.1,0.0,41.6,4213.5,1474.5,0.0,4.0,5.7,259.2,115.8,0.0,3849.3,3894.8,9175.5,112.6,0.7,8.3,255.0,14.7,17.0,1173.4,407.5,15.2,0.8,0.9,429.1,0.9,0.8,337.2,0.7,0.0,0.8,87269.7
1,Forestry and logging,731.7,44.9,5.5,16.9,0.0,21.3,123.7,0.0,0.1,0.0,0.5,0.0,52.7,93.8,44.3,934.9,109.9,62.4,307.6,249.2,152.3,636.1,111.4,3.5,0.1,0.7,657.9,434.3,1418.4,430.5,257.9,22.0,21.8,6.8,0.0,5.6,565.0,197.7,0.0,64.1,0.8,34.8,15.5,0.0,516.1,522.2,1230.3,11.8,0.1,1.1,34.2,2.0,2.3,157.3,54.6,2.0,0.1,0.1,57.5,0.1,0.1,45.2,0.1,0.0,0.1,10474.2
2,Fishing and aquaculture,0.0,0.0,0.0,3.2,0.0,4.1,23.5,0.0,0.0,0.0,0.1,0.0,10.0,17.8,8.4,177.6,2.2,56.0,276.0,737.4,450.8,120.8,100.0,0.7,0.0,0.1,135.4,82.5,269.4,81.8,49.0,4.2,4.1,1.3,0.0,1.1,107.3,37.6,0.0,2.9,0.1,6.6,2.9,0.0,98.0,99.2,233.7,40.9,0.0,0.2,6.5,0.4,0.4,29.9,10.4,0.4,0.0,0.0,10.9,0.0,0.0,8.6,0.0,0.0,0.0,3314.7
3,Mining and quarrying,3.3,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,840.2,575.3,2838.3,634.6,387.9,0.0,1028.2,0.0,0.0,0.0,10300.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,870.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2222.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,19702.4
4,Manufacture of food products; beverages and tobacco products,30.7,1.9,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1687.9,2359.0,11637.7,2786.7,1703.5,0.0,4216.0,0.0,0.0,0.0,10248.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4123.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2828.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,41624.6
5,"Manufacture of textiles, wearing apparel, leather and related products",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,429.4,308.4,1521.5,219.8,134.3,0.0,551.2,0.0,0.0,0.0,744.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1091.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1579.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6579.5
6,"Manufacture of wood and of products of wood and cork, except furniture; manufacture of articles of straw and plaiting materials",136.4,8.4,1.0,7.3,0.0,9.3,53.7,0.0,0.0,0.0,0.2,0.0,22.9,40.7,19.2,405.9,198.7,180.7,891.3,193.3,118.2,276.2,322.9,1.5,0.1,0.3,832.0,188.6,615.8,186.9,112.0,9.5,9.5,3.0,0.0,2.4,245.3,85.8,0.0,53.7,0.3,15.1,6.7,0.0,224.1,226.7,534.1,22.5,0.0,0.5,14.8,0.9,1.0,68.3,23.7,0.9,0.0,0.1,25.0,0.1,0.0,19.6,0.0,0.0,0.0,6417.3
7,Manufacture of paper and paper products,0.0,0.0,0.0,7.7,0.0,9.7,56.5,0.0,0.0,0.0,0.2,0.0,24.1,42.8,20.2,426.8,136.5,107.4,529.6,4.6,2.8,290.4,191.9,1.6,0.1,0.3,428.2,198.3,647.5,196.5,117.7,10.0,10.0,3.1,0.0,2.5,257.9,90.3,0.0,58.3,0.3,15.9,7.1,0.0,235.6,238.4,561.6,47.4,0.0,0.5,15.6,0.9,1.0,71.8,24.9,0.9,0.0,0.1,26.3,0.1,0.1,20.6,0.0,0.0,0.1,5143.1
8,Printing and reproduction of recorded media,0.0,0.0,0.0,2.4,0.0,3.0,17.5,0.0,0.0,0.0,0.1,0.0,7.5,13.3,6.3,132.2,104.3,94.5,466.0,52.5,32.1,90.0,168.8,0.5,0.0,0.1,210.6,61.4,200.6,60.9,36.5,3.1,3.1,1.0,0.0,0.8,79.9,28.0,0.0,361.6,0.1,4.9,2.2,0.0,73.0,73.9,174.0,18.4,0.0,0.2,4.8,0.3,0.3,22.2,7.7,0.3,0.0,0.0,8.1,0.0,0.0,6.4,0.0,0.0,0.0,2635.2
9,Manufacture of coke and refined petroleum products,0.0,0.0,0.0,4.6,0.0,5.8,33.4,0.0,0.0,0.0,0.1,0.0,14.2,25.3,11.9,252.1,320.8,436.5,2153.4,300.4,183.7,171.5,780.1,0.9,0.0,0.2,1617.5,117.1,382.4,116.1,69.5,5.9,5.9,1.8,0.0,1.5,152.3,53.3,0.0,1141.4,0.2,9.4,4.2,0.0,139.2,140.8,331.7,1530.4,0.0,0.3,9.2,0.5,0.6,42.4,14.7,0.6,0.0,0.0,15.5,0.0,0.0,12.2,0.0,0.0,0.0,10611.9
10,Manufacture of chemicals and chemical products,3.7,0.2,0.0,5.1,0.0,6.5,37.6,0.0,0.0,0.0,0.2,0.0,16.0,28.5,13.4,283.9,2559.8,2848.9,14054.4,2634.6,1610.5,193.2,5091.4,1.1,0.0,0.2,7688.0,131.9,430.8,130.7,78.3,6.7,6.6,2.1,0.0,1.7,171.6,60.0,0.0,4542.9,0.2,10.6,4.7,0.0,156.8,158.6,373.6,12246.8,0.0,0.3,10.4,0.6,0.7,47.8,16.6,0.6,0.0,0.0,17.5,0.0,0.0,13.7,0.0,0.0,0.0,55700.5
11,Manufacture of basic pharmaceutical products and pharmaceutical preparations,1.8,0.1,0.0,35.7,0.0,45.1,261.4,0.0,0.2,0.0,1.2,0.0,111.4,198.2,93.6,1975.5,1062.3,1372.9,6772.6,866.0,529.4,1344.2,2453.5,7.4,0.3,1.6,9970.0,917.8,2997.3,909.6,544.9,46.5,46.1,14.5,0.0,11.8,1193.8,417.8,0.0,3764.3,1.6,73.5,32.8,0.0,1090.6,1103.6,2599.7,17401.4,0.2,2.4,72.3,4.2,4.8,332.5,115.5,4.3,0.2,0.3,121.6,0.3,0.2,95.5,0.2,0.0,0.2,61026.5
12,Manufacture of rubber and plastic products,31.3,1.9,0.2,15.8,0.0,20.0,115.7,0.0,0.1,0.0,0.5,0.0,49.3,87.8,41.4,874.7,414.1,313.2,1544.9,186.6,114.1,595.1,559.6,3.3,0.1,0.7,1230.9,406.3,1327.1,402.7,241.3,20.6,20.4,6.4,0.0,5.2,528.6,185.0,0.0,101.1,0.7,32.5,14.5,0.0,482.9,488.6,1151.1,545.7,0.1,1.0,32.0,1.8,2.1,147.2,51.1,1.9,0.1,0.1,53.8,0.1,0.1,42.3,0.1,0.0,0.1,12496.1
13,Manufacture of other non-metallic mineral products,0.0,0.0,0.0,20.0,0.0,25.3,146.6,0.0,0.1,0.0,0.6,0.0,62.4,111.1,52.5,1107.5,329.7,233.6,1152.4,762.6,466.2,753.6,417.5,4.2,0.2,0.9,1163.8,514.5,1680.4,510.0,305.5,26.1,25.9,8.1,0.0,6.6,669.3,234.2,0.0,186.6,0.9,41.2,18.4,0.0,611.4,618.7,1457.5,282.0,0.1,1.3,40.5,2.3,2.7,186.4,64.7,2.4,0.1,0.1,68.2,0.1,0.1,53.6,0.1,0.0,0.1,14430.8
14,Manufacture of basic metals,0.0,0.0,0.0,21.2,0.0,26.8,155.2,0.0,0.1,0.0,0.7,0.0,66.1,117.7,55.5,1172.7,214.2,195.1,962.6,27.9,17.1,797.9,348.7,4.4,0.2,0.9,842.9,544.8,1779.3,540.0,323.5,27.6,27.4,8.6,0.0,7.0,708.7,248.0,0.0,197.5,1.0,43.6,19.5,0.0,647.4,655.1,1543.3,191.4,0.1,1.4,42.9,2.5,2.9,197.4,68.5,2.6,0.1,0.2,72.2,0.2,0.1,56.7,0.1,0.0,0.1,12989.5
15,"Manufacture of fabricated metal products, except machinery and equipment",9.2,0.6,0.1,45.8,0.0,57.9,335.7,0.0,0.2,0.0,1.5,0.0,143.0,254.5,120.1,2536.4,954.7,463.6,2286.9,199.8,122.1,1725.8,828.5,9.5,0.4,2.0,1495.6,1178.3,3848.3,1167.9,699.7,59.7,59.2,18.6,0.0,15.1,1532.8,536.4,0.0,336.2,2.1,94.3,42.1,0.0,1400.3,1416.9,3337.9,471.6,0.3,3.0,92.8,5.3,6.2,426.9,148.2,5.5,0.3,0.3,156.1,0.3,0.3,122.7,0.3,0.0,0.3,28780.0
16,"Manufacture of computer, electronic and optical products",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2224.1,410.0,2022.8,290.9,177.8,0.0,732.8,0.0,0.0,0.0,1819.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6903.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11605.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,26187.4
17,Manufacture of electrical equipment,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2837.4,534.3,2635.7,228.7,139.8,0.0,954.8,0.0,0.0,0.0,1282.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2250.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6303.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17167.5
18,Manufacture of machinery and equipment n.e.c.,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2134.6,1362.3,6720.8,1182.5,722.9,0.0,2434.7,0.0,0.0,0.0,5168.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7018.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14256.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,41000.3
19,"Manufacture of motor vehicles, trailers and semi-trailers",0.0,0.0,0.0,73.3,0.0,92.6,536.9,0.0,0.3,0.0,2.4,0.0,228.7,407.1,192.2,4057.0,1181.1,506.6,2499.4,0.0,0.0,2760.4,905.4,15.2,0.6,3.2,813.2,1884.8,6155.4,1868.1,1119.1,95.4,94.7,29.7,0.0,24.2,2451.7,858.0,0.0,492.1,3.3,150.8,67.4,0.0,2239.8,2266.3,5339.0,2835.7,0.4,4.9,148.4,8.5,9.9,682.8,237.1,8.9,0.5,0.5,249.7,0.5,0.5,196.2,0.4,0.0,0.5,43801.1
20,Manufacture of other transport equipment,0.0,0.0,0.0,16.0,0.0,20.2,117.2,0.0,0.1,0.0,0.5,0.0,49.9,88.9,42.0,885.9,279.7,39.7,196.0,396.2,242.2,602.8,71.0,3.3,0.1,0.7,257.8,411.6,1344.1,407.9,244.4,20.8,20.7,6.5,0.0,5.3,535.4,187.3,0.0,105.7,0.7,32.9,14.7,0.0,489.1,494.9,1165.8,889.3,0.1,1.1,32.4,1.9,2.2,149.1,51.8,1.9,0.1,0.1,54.5,0.1,0.1,42.8,0.1,0.0,0.1,10025.7
21,Manufacture of furniture; other manufacturing,0.0,0.0,0.0,15.5,0.0,19.6,113.6,0.0,0.1,0.0,0.5,0.0,48.4,86.1,40.7,858.4,220.9,110.0,542.8,142.4,87.0,584.1,196.6,3.2,0.1,0.7,2621.1,398.8,1302.4,395.3,236.8,20.2,20.0,6.3,0.0,5.1,518.8,181.5,0.0,198.7,0.7,31.9,14.3,0.0,473.9,479.5,1129.7,125.0,0.1,1.0,31.4,1.8,2.1,144.5,50.2,1.9,0.1,0.1,52.8,0.1,0.1,41.5,0.1,0.0,0.1,11558.7
22,Repair and installation of machinery and equipment,0.0,0.0,0.0,14.2,0.0,18.0,104.3,0.0,0.1,0.0,0.5,0.0,44.4,79.1,37.3,788.2,408.5,77.5,382.6,310.6,189.8,536.3,138.6,3.0,0.1,0.6,765.7,366.2,1195.9,362.9,217.4,18.5,18.4,5.8,0.0,4.7,476.3,166.7,0.0,506.0,0.6,29.3,13.1,0.0,435.2,440.3,1037.3,282.6,0.1,0.9,28.8,1.7,1.9,132.6,46.1,1.7,0.1,0.1,48.5,0.1,0.1,38.1,0.1,0.0,0.1,9777.8
23,"Electricity, gas, steam and air conditioning supply",1.8,0.1,0.0,269.0,0.1,340.1,1971.4,0.1,1.2,0.0,8.7,0.1,839.9,1494.7,705.6,14897.1,1352.1,1027.1,5067.2,210.5,128.7,10136.2,1835.7,56.0,2.3,11.9,11781.5,6920.8,22602.5,6859.4,4109.4,350.5,347.9,109.1,0.0,88.8,9002.7,3150.4,0.0,1435.9,12.1,553.9,247.4,0.0,8224.5,8321.9,19604.6,208.6,1.5,17.8,544.9,31.4,36.3,2507.1,870.6,32.5,1.7,1.9,916.8,2.0,1.8,720.4,1.6,0.0,1.8,149979.6
24,"Water collection, treatment and supply",0.0,0.0,0.0,5.8,0.0,7.4,42.9,0.0,0.0,0.0,0.2,0.0,18.3,32.5,15.3,323.9,44.4,55.2,272.4,263.0,160.8,220.4,98.7,1.2,0.1,0.3,4577.0,150.5,491.4,149.1,89.3,7.6,7.6,2.4,0.0,1.9,195.7,68.5,0.0,311.9,0.3,12.0,5.4,0.0,178.8,180.9,426.2,14.2,0.0,0.4,11.8,0.7,0.8,54.5,18.9,0.7,0.0,0.0,19.9,0.0,0.0,15.7,0.0,0.0,0.0,8557.2
25,"Sewerage, waste management, remediation activities",0.0,0.0,0.0,41.3,0.0,52.2,302.6,0.0,0.2,0.0,1.3,0.0,128.9,229.4,108.3,2286.3,237.6,125.4,618.7,861.7,526.8,1555.6,224.1,8.6,0.4,1.8,6278.7,1062.2,3468.9,1052.7,630.7,53.8,53.4,16.7,0.0,13.6,1381.7,483.5,0.0,75.1,1.9,85.0,38.0,0.0,1262.2,1277.2,3008.8,56.9,0.2,2.7,83.6,4.8,5.6,384.8,133.6,5.0,0.3,0.3,140.7,0.3,0.3,110.6,0.2,0.0,0.3,28485.5
26,Construction,2.8,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2674.2,1984.6,9790.7,10106.5,6178.1,0.0,3546.8,0.0,0.0,0.0,28041.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4363.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1026.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,67715.2
27,Wholesale and retail trade and repair of motor vehicles and motorcycles,0.0,0.0,0.0,65.3,0.0,82.5,478.4,0.0,0.3,0.0,2.1,0.0,203.8,362.7,171.2,3615.1,43.3,20.2,99.8,3412.8,2086.3,2459.7,36.2,13.6,0.6,2.9,797.4,1679.5,5484.9,1664.6,997.2,85.0,84.4,26.5,0.0,21.6,2184.7,764.5,0.0,213.7,2.9,134.4,60.0,0.0,1995.8,2019.4,4757.4,18.4,0.4,4.3,132.2,7.6,8.8,608.4,211.3,7.9,0.4,0.5,222.5,0.5,0.4,174.8,0.4,0.0,0.4,37530.0
28,"Wholesale trade, except of motor vehicles and motorcycles",5.5,0.3,0.0,266.8,0.1,337.3,1955.2,0.1,1.2,0.0,8.6,0.1,833.0,1482.4,699.8,14774.7,1826.1,680.5,3356.8,1933.4,1181.9,10052.9,1216.1,55.5,2.3,11.8,4453.3,6864.0,22416.8,6803.0,4075.6,347.6,345.0,108.2,0.0,88.1,8928.7,3124.5,0.0,1658.9,12.0,549.3,245.3,0.0,8156.9,8253.5,19443.5,1081.9,1.5,17.7,540.4,31.1,36.0,2486.5,863.5,32.3,1.7,1.9,909.3,2.0,1.8,714.5,1.6,0.0,1.8,143282.1
29,"Retail trade, except of motor vehicles and motorcycles",1.8,0.1,0.0,202.8,0.1,256.4,1486.0,0.1,0.9,0.0,6.6,0.1,633.1,1126.7,531.9,11229.3,1011.3,408.0,2012.7,1237.0,756.2,7640.6,729.1,42.2,1.7,8.9,6423.0,5216.8,17037.5,5170.5,3097.6,264.2,262.2,82.3,0.0,66.9,6786.1,2374.7,0.0,2312.8,9.1,417.5,186.5,0.0,6199.5,6272.9,14777.7,39.1,1.1,13.4,410.7,23.7,27.4,1889.8,656.3,24.5,1.3,1.5,691.1,1.5,1.3,543.1,1.2,0.0,1.3,110609.7
30,Land transport and transport via pipelines,3.7,0.2,0.0,38.9,0.0,49.2,285.3,0.0,0.2,0.0,1.3,0.0,121.6,216.3,102.1,2156.2,180.9,133.3,657.4,9998.5,6112.1,1467.1,238.2,8.1,0.3,1.7,4061.8,1001.7,3271.5,992.8,594.8,50.7,50.4,15.8,0.0,12.9,1303.1,456.0,0.0,847.4,1.8,80.2,35.8,0.0,1190.4,1204.5,2837.6,98.9,0.2,2.6,78.9,4.5,5.3,362.9,126.0,4.7,0.3,0.3,132.7,0.3,0.3,104.3,0.2,0.0,0.3,40704.3
31,Water transport,0.0,0.0,0.0,4.1,0.0,5.1,29.8,0.0,0.0,0.0,0.1,0.0,12.7,22.6,10.7,225.6,0.0,0.0,0.0,2576.9,1575.2,153.5,0.0,0.8,0.0,0.2,522.1,104.8,342.2,103.9,62.2,5.3,5.3,1.7,0.0,1.3,136.3,47.7,0.0,109.2,0.2,8.4,3.7,0.0,124.5,126.0,296.8,0.0,0.0,0.3,8.2,0.5,0.6,38.0,13.2,0.5,0.0,0.0,13.9,0.0,0.0,10.9,0.0,0.0,0.0,6705.3
32,Air transport,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11.6,50.4,248.4,1663.0,1016.6,0.0,90.0,0.0,0.0,0.0,262.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,25.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,26.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3394.1
33,Warehousing and support activities for transportation,0.0,0.0,0.0,34.9,0.0,44.1,255.7,0.0,0.2,0.0,1.1,0.0,109.0,193.9,91.5,1932.4,889.2,219.2,1081.3,1287.4,787.0,1314.8,391.7,7.3,0.3,1.5,18202.5,897.8,2931.9,889.8,533.1,45.5,45.1,14.2,0.0,11.5,1167.8,408.7,0.0,730.7,1.6,71.8,32.1,0.0,1066.9,1079.5,2543.1,97.8,0.2,2.3,70.7,4.1,4.7,325.2,112.9,4.2,0.2,0.3,118.9,0.3,0.2,93.5,0.2,0.0,0.2,40151.7
34,Postal and courier activities,0.0,0.0,0.0,17.7,0.0,22.4,129.6,0.0,0.1,0.0,0.6,0.0,55.2,98.3,46.4,979.6,360.8,39.0,192.2,101.3,61.9,666.5,69.6,3.7,0.2,0.8,159.4,455.1,1486.2,451.0,270.2,23.0,22.9,7.2,0.0,5.8,592.0,207.2,0.0,104.0,0.8,36.4,16.3,0.0,540.8,547.2,1289.1,21.9,0.1,1.2,35.8,2.1,2.4,164.9,57.2,2.1,0.1,0.1,60.3,0.1,0.1,47.4,0.1,0.0,0.1,9456.3
35,Accommodation and food service activities,37.7,2.3,0.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5998.8,2422.8,11952.1,6054.6,3701.2,0.0,4329.8,0.0,0.0,0.0,42085.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4055.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,89.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,80729.1
36,Publishing activities,0.0,0.0,0.0,31.0,0.0,39.2,227.1,0.0,0.1,0.0,1.0,0.0,96.8,172.2,81.3,1716.1,72.2,5.0,24.7,73.0,44.6,1167.7,9.0,6.4,0.3,1.4,503.4,797.3,2603.8,790.2,473.4,40.4,40.1,12.6,0.0,10.2,1037.1,362.9,0.0,2220.3,1.4,63.8,28.5,0.0,947.5,958.7,2258.4,221.0,0.2,2.1,62.8,3.6,4.2,288.8,100.3,3.7,0.2,0.2,105.6,0.2,0.2,83.0,0.2,0.0,0.2,17795.6
37,"Motion picture, video, television programme production; programming and broadcasting activities",0.0,0.0,0.0,21.4,0.0,27.0,156.8,0.0,0.1,0.0,0.7,0.0,66.8,118.9,56.1,1184.7,96.6,51.4,253.6,75.2,46.0,806.1,91.9,4.5,0.2,0.9,77.7,550.4,1797.5,545.5,326.8,27.9,27.7,8.7,0.0,7.1,716.0,250.5,0.0,871.6,1.0,44.0,19.7,0.0,654.1,661.8,1559.1,23.1,0.1,1.4,43.3,2.5,2.9,199.4,69.2,2.6,0.1,0.2,72.9,0.2,0.1,57.3,0.1,0.0,0.1,11681.5
38,Telecommunications,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1681.8,388.9,1918.5,1186.6,725.4,0.0,695.0,0.0,0.0,0.0,4809.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7457.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,648.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,19511.1
39,"Computer programming, consultancy, and information service activities",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5940.0,435.3,2147.2,1477.1,902.9,0.0,777.9,0.0,0.0,0.0,4642.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,41690.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9236.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,67249.7
40,"Financial service activities, except insurance and pension funding",0.0,0.0,0.0,2.6,0.0,3.3,19.0,0.0,0.0,0.0,0.1,0.0,8.1,14.4,6.8,143.8,783.7,107.4,529.8,5552.4,3394.2,97.8,191.9,0.5,0.0,0.1,6941.1,66.8,218.2,66.2,39.7,3.4,3.4,1.1,0.0,0.9,86.9,30.4,0.0,7253.7,0.1,5.3,2.4,0.0,79.4,80.3,189.2,676.6,0.0,0.2,5.3,0.3,0.4,24.2,8.4,0.3,0.0,0.0,8.8,0.0,0.0,7.0,0.0,0.0,0.0,26656.0
41,"Insurance, reinsurance and pension funding, except compulsory social security",0.0,0.0,0.0,11.1,0.0,14.0,81.4,0.0,0.1,0.0,0.4,0.0,34.7,61.7,29.1,615.1,152.1,6.1,30.2,0.0,0.0,418.6,10.9,2.3,0.1,0.5,120.4,285.8,933.3,283.2,169.7,14.5,14.4,4.5,0.0,3.7,371.7,130.1,0.0,791.3,0.5,22.9,10.2,0.0,339.6,343.6,809.5,71.7,0.1,0.7,22.5,1.3,1.5,103.5,36.0,1.3,0.1,0.1,37.9,0.1,0.1,29.7,0.1,0.0,0.1,6424.0
42,Activities auxiliary to financial services and insurance activities,0.0,0.0,0.0,10.8,0.0,13.7,79.1,0.0,0.0,0.0,0.3,0.0,33.7,60.0,28.3,598.0,174.3,8.7,42.9,0.0,0.0,406.9,15.6,2.2,0.1,0.5,246.4,277.8,907.4,275.4,165.0,14.1,14.0,4.4,0.0,3.6,361.4,126.5,0.0,491.5,0.5,22.2,9.9,0.0,330.2,334.1,787.0,16.0,0.1,0.7,21.9,1.3,1.5,100.6,34.9,1.3,0.1,0.1,36.8,0.1,0.1,28.9,0.1,0.0,0.1,6090.9

In [126]:
invTableNama.iloc[:-3, 1:-1] #= invTableNama.iloc[:-3, 1:-1].div(invTableNama.iloc[:-3, -1], axis=0)
for i in range(len(diff)-3):
    for j in range(1,66):
        invTableNama.iloc[i, j]/=invTableNama.iloc[i, 66]

In [127]:
pd.options.display.float_format = '{:.4f}'.format
invTableNama

,sectors,"Products of agriculture, hunting and related services","Products of forestry, logging and related services",Fish and other fishing products; aquaculture products; support services to fishing,Mining and quarrying,"Food, beverages and tobacco products","Textiles, wearing apparel, leather and related products","Wood and of products of wood and cork, except furniture; articles of straw and plaiting materials",Paper and paper products,Printing and recording services,Coke and refined petroleum products,Chemicals and chemical products,Basic pharmaceutical products and pharmaceutical preparations,Rubber and plastic products,Other non-metallic mineral products,Basic metals,"Fabricated metal products, except machinery and equipment","Computer, electronic and optical products",Electrical equipment,Machinery and equipment n.e.c.,"Motor vehicles, trailers and semi-trailers",Other transport equipment,Furniture and other manufactured goods,Repair and installation services of machinery and equipment,"Electricity, gas, steam and air conditioning",Natural water; water treatment and supply services,"Sewerage services; sewage sludge; waste collection, treatment and disposal services; materials recovery services; remediation services and other waste management services",Constructions and construction works,Wholesale and retail trade and repair services of motor vehicles and motorcycles,"Wholesale trade services, except of motor vehicles and motorcycles","Retail trade services, except of motor vehicles and motorcycles",Land transport services and transport services via pipelines,Water transport services,Air transport services,Warehousing and support services for transportation,Postal and courier services,Accommodation and food services,Publishing services,"Motion picture, video and television programme production services, sound recording and music publishing; programming and broadcasting services",Telecommunications services,"Computer programming, consultancy and related services; Information services","Financial services, except insurance and pension funding","Insurance, reinsurance and pension funding services, except compulsory social security",Services auxiliary to financial services and insurance services,Imputed rents of owner-occupied dwellings,Real estate services excluding imputed rents,Legal and accounting services; services of head offices; management consultancy services,Architectural and engineering services; technical testing and analysis services,Scientific research and development services,Advertising and market research services,"Other professional, scientific and technical services and veterinary services",Rental and leasing services,Employment services,"Travel agency, tour operator and other reservation services and related services","Security and investigation services; services to buildings and landscape; office administrative, office support and other business support services",Public administration and defence services; compulsory social security services,Education services,Human health services,Residential care services; social work services without accommodation,"Creative, arts, entertainment, library, archive, museum, other cultural services; gambling and betting services",Sporting services and amusement and recreation services,Services furnished by membership organisations,Repair services of computers and personal and household goods,Other personal services,Services of households as employers; undifferentiated goods and services produced by households for own use,Services provided by extraterritorial organisations and bodies,Totals
0,"Crop and animal production, hunting and related service activities",0.0587,0.0036,0.0004,0.0014,0.0000,0.0018,0.0106,0.0000,0.0000,0.0000,0.0000,0.0000,0.0045,0.0080,0.0038,0.0799,0.0068,0.0166,0.0819,0.0339,0.0207,0.0544,0.0297,0.0003,0.0000,0.0001,0.0655,0.0371,0.1212,0.0368,0.0220,0.0019,0.0019,0.0006,0.0000,0.0005,0.0483,0.0169,0.0000,0.0000,0.0001,0.0030,0.0013,0.0000,0.0441,0.0446,0.1051,0.0013,0.0000,0.0001,0.0029,0.0002,0.0002,0.0134,0.0047,0.0002,0.0000,0.0000,0.0049,0.0000,0.0000,0.0039,0.0000,0.0000,0.0000,87269.6802
1,Forestry and logging,0.0699,0.0043,0.0005,0.0016,0.0000,0.0020,0.0118,0.0000,0.0000,0.0000,0.0001,0.0000,0.0050,0.0090,0.0042,0.0893,0.0105,0.0060,0.0294,0.0238,0.0145,0.0607,0.0106,0.0003,0.0000,0.0001,0.0628,0.0415,0.1354,0.0411,0.0246,0.0021,0.0021,0.0007,0.0000,0.0005,0.0539,0.0189,0.0000,0.0061,0.0001,0.0033,0.0015,0.0000,0.0493,0.0499,0.1175,0.0011,0.0000,0.0001,0.0033,0.0002,0.0002,0.0150,0.0052,0.0002,0.0000,0.0000,0.0055,0.0000,0.0000,0.0043,0.0000,0.0000,0.0000,10474.2173
2,Fishing and aquaculture,0.0000,0.0000,0.0000,0.0010,0.0000,0.0012,0.0071,0.0000,0.0000,0.0000,0.0000,0.0000,0.0030,0.0054,0.0025,0.0536,0.0007,0.0169,0.0833,0.2225,0.1360,0.0365,0.0302,0.0002,0.0000,0.0000,0.0408,0.0249,0.0813,0.0247,0.0148,0.0013,0.0013,0.0004,0.0000,0.0003,0.0324,0.0113,0.0000,0.0009,0.0000,0.0020,0.0009,0.0000,0.0296,0.0299,0.0705,0.0123,0.0000,0.0001,0.0020,0.0001,0.0001,0.0090,0.0031,0.0001,0.0000,0.0000,0.0033,0.0000,0.0000,0.0026,0.0000,0.0000,0.0000,3314.7286
3,Mining and quarrying,0.0002,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0426,0.0292,0.1441,0.0322,0.0197,0.0000,0.0522,0.0000,0.0000,0.0000,0.5228,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0442,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1128,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,19702.4198
4,Manufacture of food products; beverages and tobacco products,0.0007,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0405,0.0567,0.2796,0.0669,0.0409,0.0000,0.1013,0.0000,0.0000,0.0000,0.2462,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0991,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0680,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,41624.6100
5,"Manufacture of textiles, wearing apparel, leather and related products",0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0653,0.0469,0.2313,0.0334,0.0204,0.0000,0.0838,0.0000,0.0000,0.0000,0.1132,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1658,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.2400,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,6579.4844
6,"Manufacture of wood and of products of wood and cork, except furniture; manufacture of articles of straw and plaiting materials",0.0213,0.0013,0.0002,0.0011,0.0000,0.0014,0.0084,0.0000,0.0000,0.0000,0.0000,0.0000,0.0036,0.0063,0.0030,0.0632,0.0310,0.0282,0.1389,0.0301,0.0184,0.0430,0.0503,0.0002,0.0000,0.0001,0.1296,0.0294,0.0960,0.0291,0.0174,0.0015,0.0015,0.0005,0.0000,0.0004,0.0382,0.0134,0.0000,0.0084,0.0001,0.0024,0.0011,0.0000,0.0349,0.0353,0.0832,0.0035,0.0000,0.0001,0.0023,0.0001,0.0002,0.0106,0.0037,0.0001,0.0000,0.0000,0.0039,0.0000,0.0000,0.0031,0.0000,0.0000,0.0000,6417.2947
7,Manufacture of paper and paper products,0.0000,0.0000,0.0000,0.0015,0.0000,0.0019,0.0110,0.0000,0.0000,0.0000,0.0000,0.0000,0.0047,0.0083,0.0039,0.0830,0.0265,0.0209,0.1030,0.0009,0.0005,0.0565,0.0373,0.0003,0.0000,0.0001,0.0833,0.0386,0.1259,0.0382,0.0229,0.0020,0.0019,0.0006,0.0000,0.0005,0.0501,0.0175,0.0000,0.0113,0.0001,0.0031,0.0014,0.0000,0.0458,0.0464,0.1092,0.0092,0.0000,0.0001,0.0030,0.0002,0.0002,0.0140,0.0048,0.0002,0.0000,0.0000,0.0051,0.0000,0.0000,0.0040,0.0000,0.0000,0.0000,5143.0639
8,Printing and reproduction of recorded media,0.0000,0.0000,0.0000,0.0009,0.0000,0.0011,0.0066,0.0000,0.0000,0.0000,0.0000,0.0000,0.0028,0.0050,0.0024,0.0502,0.0396,0.0358,0.1768,0.0199,0.0122,0.0341,0.0641,0.0002,0.0000,0.0000,0.0799,0.0233,0.0761,0.0231,0.0138,0.0012,0.0012,0.0004,0.0000,0.0003,0.0303,0.0106,0.0000,0.1372,0.0000,0.0019,0.0008,0.0000,0.0277,0.0280,0.0660,0.0070,0.0000,0.0001,0.0018,0.0001,0.0001,0.0084,0.0029,0.0001,0.0000,0.0000,0.0031,0.0000,0.0000,0.0024,0.0000,0.0000,0.0000,2635.2253
9,Manufacture of coke and refined petroleum products,0.0000,0.0000,0.0000,0.0004,0.0000,0.0005,0.0031,0.0000,0.0000,0.0000,0.0000,0.0000,0.0013,0.0024,0.0011,0.0238,0.0302,0.0411,0.2029,0.0283,0.0173,0.0162,0.0735,0.0001,0.0000,0.0000,0.1524,0.0110,0.0360,0.0109,0.0066,0.0006,0.0006,0.0002,0.0000,0.0001,0.0144,0.0050,0.0000,0.1076,0.0000,0.0009,0.0004,0.0000,0.0131,0.0133,0.0313,0.1442,0.0000,0.0000,0.0009,0.0001,0.0001,0.0040,0.0014,0.0001,0.0000,0.0000,0.0015,0.0000,0.0000,0.0011,0.0000,0.0000,0.0000,10611.8869
10,Manufacture of chemicals and chemical products,0.0001,0.0000,0.0000,0.0001,0.0000,0.0001,0.0007,0.0000,0.0000,0.0000,0.0000,0.0000,0.0003,0.0005,0.0002,0.0051,0.0460,0.0511,0.2523,0.0473,0.0289,0.0035,0.0914,0.0000,0.0000,0.0000,0.1380,0.0024,0.0077,0.0023,0.0014,0.0001,0.0001,0.0000,0.0000,0.0000,0.0031,0.0011,0.0000,0.0816,0.0000,0.0002,0.0001,0.0000,0.0028,0.0028,0.0067,0.2199,0.0000,0.0000,0.0002,0.0000,0.0000,0.0009,0.0003,0.0000,0.0000,0.0000,0.0003,0.0000,0.0000,0.0002,0.0000,0.0000,0.0000,55700.4691
11,Manufacture of basic pharmaceutical products and pharmaceutical preparations,0.0000,0.0000,0.0000,0.0006,0.0000,0.0007,0.0043,0.0000,0.0000,0.0000,0.0000,0.0000,0.0018,0.0032,0.0015,0.0324,0.0174,0.0225,0.1110,0.0142,0.0087,0.0220,0.0402,0.0001,0.0000,0.0000,0.1634,0.0150,0.0491,0.0149,0.0089,0.0008,0.0008,0.0002,0.0000,0.0002,0.0196,0.0068,0.0000,0.0617,0.0000,0.0012,0.0005,0.0000,0.0179,0.0181,0.0426,0.2851,0.0000,0.0000,0.0012,0.0001,0.0001,0.0054,0.0019,0.0001,0.0000,0.0000,0.0020,0.0000,0.0000,0.0016,0.0000,0.0000,0.0000,61026.5205
12,Manufacture of rubber and plastic products,0.0025,0.0002,0.0000,0.0013,0.0000,0.0016,0.0093,0.0000,0.0000,0.0000,0.0000,0.0000,0.0039,0.0070,0.0033,0.0700,0.0331,0.0251,0.1236,0.0149,0.0091,0.0476,0.0448,0.0003,0.0000,0.0001,0.0985,0.0325,0.1062,0.0322,0.0193,0.0016,0.0016,0.0005,0.0000,0.0004,0.0423,0.0148,0.0000,0.0081,0.0001,0.0026,0.0012,0.0000,0.0386,0.0391,0.0921,0.0437,0.0000,0.0001,0.0026,0.0001,0.0002,0.0118,0.0041,0.0002,0.0000,0.0000,0.0043,0.0000,0.0000,0.0034,0.0000,0.0000,0.0000,12496.0561
13,Manufacture of other non-metallic mineral products,0.0000,0.0000,0.0000,0.0014,0.0000,0.0018,0.0102,0.0000,0.0000,0.0000,0.0000,0.0000,0.0043,0.0077,0.0036,0.0767,0.0228,0.0162,0.0799,0.0528,0.0323,0.0522,0.0289,0.0003,0.0000,0.0001,0.0806,0.0357,0.1164,0.0353,0.0212,0.0018,0.0018,0.0006,0.0000,0.0005,0.0464,0.0162,0.0000,0.0129,0.0001,0.0029,0.0013,0.0000,0.0424,0.0429,0.1010,0.0195,0.0000,0.0001,0.0028,0.0002,0.0002,0.0129,0.0045,0.0002,0.0000,0.0000,0.0047,0.0000,0.0000,0.0037,0.0000,0.0000,0.0000,14430.7984
14,Manufacture of basic metals,0.0000,0.0000,0.0000,0.0016,0.0000,0.0021,0.0119,0.0000,0.0000,0.0000,0.0001,0.0000,0.0051,0.0091,0.0043,0.0903,0.0165,0.0150,0.0741,0.0021,0.0013,0.0614,0.0268,0.0003,0.0000,0.0001,0.0649,0.0419,0.1370,0.0416,0.0249,0.0021,0.0021,0.0007,0.0000,0.0005,0.0546,0.0191,0.0000,0.0152,0.0001,0.0034,0.0015,0.0000,0.0498,0.0504,0.1188,0.0147,0.0000,0.0001,0.0033,0.0002,0.0002,0.0152,0.0053,0.0002,0.0000,0.0000,0.0056,0.0000,0.0000,0.0044,0.0000,0.0000,0.0000,12989.4821
15,"Manufacture of fabricated metal products, except machinery and equipment",0.0003,0.0000,0.0000,0.0016,0.0000,0.0020,0.0117,0.0000,0.0000,0.0000,0.0001,0.0000,0.0050,0.0088,0.0042,0.0881,0.0332,0.0161,0.0795,0.0069,0.0042,0.0600,0.0288,0.0003,0.0000,0.0001,0.0520,0.0409,0.1337,0.0406,0.0243,0.0021,0.0021,0.0006,0.0000,0.0005,0.0533,0.0186,0.0000,0.0117,0.0001,0.0033,0.0015,0.0000,0.0487,0.0492,0.1160,0.0164,0.0000,0.0001,0.0032,0.0002,0.0002,0.0148,0.0052,0.0002,0.0000,0.0000,0.0054,0.0000,0.0000,0.0043,0.0000,0.0000,0.0000,28780.0381
16,"Manufacture of computer, electronic and optical products",0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0849,0.0157,0.0772,0.0111,0.0068,0.0000,0.0280,0.0000,0.0000,0.0000,0.0695,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.2636,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.4432,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,26187.3550
17,Manufacture of electrical equipment,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1653,0.0311,0.1535,0.0133,0.0081,0.0000,0.0556,0.0000,0.0000,0.0000,0.0747,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1311,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.3672,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,17167.4943
18,Manufacture of machinery and equipment n.e.c.,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0521,0.0332,0.1639,0.0288,0.0176,0.0000,0.0594,0.0000,0.0000,0.0000,0.1260,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1712,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.3477,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,41000.3186
19,"Manufacture of motor vehicles, trailers and semi-trailers",0.0000,0.0000,0.0000,0.0017,0.0000,0.0021,0.0123,0.0000,0.0000,0.0000,0.0001,0.0000,0.0052,0.0093,0.0044,0.0926,0.0270,0.0116,0.0571,0.0000,0.0000,0.0630,0.0207,0.0003,0.0000,0.0001,0.0186,0.0430,0.1405,0.0426,0.0256,0.0022,0.0022,0.0007,0.0000,0.0006,0.0560,0.0196,0.0000,0.0112,0.0001,0.0034,0.0015,0.0000,0.0511,0.0517,0.1219,0.0647,0.0000,0.0001,0.0034,0.0002,0.0002,0.0156,0.0054,0.0002,0.0000,0.0000,0.0057,0.0000,0.0000,0.0045,0.0000,0.0000,0.0000,43801.1108
20,Manufacture of other transport equipment,0.0000,0.0000,0.0000,0.0016,0.0000,0.0020,0.0117,0.0000,0.0000,0.0000,0.0001,0.0000,0.0050,0.0089,0.0042,0.0884,0.0279,0.0040,0.0196,0.0395,0.0242,0.0601,0.0071,0.0003,0.0000,0.0001,0.0257,0.0410,0.1341,0.0407,0.0244,0.0021,0.0021,0.0006,0.0000,0.0005,0.0534,0.0187,0.0000,0.0105,0.0001,0.0033,0.0015,0.0000,0.0488,0.0494,0.1163,0.0887,0.0000,0.0001,0.0032,0.0002,0.0002,0.0149,0.0052,0.0002,0.0000,0.0000,0.0054,0.0000,0.0000,0.0043,0.0000,0.0000,0.0000,10025.7397
21,Manufacture of furniture; other manufacturing,0.0000,0.0000,0.0000,0.0013,0.0000,0.0017,0.0098,0.0000,0.0000,0.0000,0.0000,0.0000,0.0042,0.0075,0.0035,0.0743,0.0191,0.0095,0.0470,0.0123,0.0075,0.0505,0.0170,0.0003,0.0000,0.0001,0.2268,0.0345,0.1127,0.0342,0.0205,0.0017,0.0017,0.0005,0.0000,0.0004,0.0449,0.0157,0.0000,0.0172,0.0001,0.0028,0.0012,0.0000,0.0410,0.0415,0.0977,0.0108,0.0000,0.0001,0.0027,0.0002,0.0002,0.0125,0.0043,0.0002,0.0000,0.0000,0.0046,0.0000,0.0000,0.0036,0.0000,0.0000,0.0000,11558.7451
22,Repair and installation of machinery and equipment,0.0000,0.0000,0.0000,0.0015,0.0000,0.0018,0.0107,0.0000,0.0000,0.0000,0.0000,0.0000,0.0045,0.0081,0.0038,0.0806,0.0418,0.0079,0.0391,0.0318,0.0194,0.0548,0.0142,0.0003,0.0000,0.0001,0.0783,0.0375,0.1223,0.0371,0.0222,0.0019,0.0019,0.0006,0.0000,0.0005,0.0487,0.0170,0.0000,0.0517,0.0001,0.0030,0.0013,0.0000,0.0445,0.0450,0.1061,0.0289,0.0000,0.0001,0.0029,0.0002,0.0002,0.0136,0.0047,0.0002,0.0000,0.0000,0.0050,0.0000,0.0000,0.0039,0.0000,0.0000,0.0000,9777.7604
23,"Electricity, gas, steam and air conditioning supply",0.0000,0.0000,0.0000,0.0018,0.0000,0.0023,0.0131,0.0000,0.0000,0.0000,0.0001,0.0000,0.0056,0.0100,0.0047,0.0993,0.0090,0.0068,0.0338,0.0014,0.0009,0.0676,0.0122,0.0004,0.0000,0.0001,0.0786,0.0461,0.1507,0.0457,0.0274,0.0023,0.0023,0.0007,0.0000,0.0006,0.0600,0.0210,0.0000,0.0096,0.0001,0.0037,0.0016,0.0000,0.0548,0.0555,0.1307,0.0014,0.0000,0.0001,0.0036,0.0002,0.0002,0.0167,0.0058,0.0002,0.0000,0.0000,0.0061,0.0000,0.0000,0.0048,0.0000,0.0000,0.0000,149979.6173
24,"Water collection, treatment and supply",0.0000,0.0000,0.0000,0.0007,0.0000,0.0009,0.0050,0.0000,0.0000,0.0000,0.0000,0.0000,0.0021,0.0038,0.0018,0.0378,0.0052,0.0065,0.0318,0.0307,0.0188,0.0258,0.0115,0.0001,0.0000,0.0000,0.5349,0.0176,0.0574,0.0174,0.0104,0.0009,0.0009,0.0003,0.0000,0.0002,0.0229,0.0080,0.0000,0.0365,0.0000,0.0014,0.0006,0.0000,0.0209,0.0211,0.0498,0.0017,0.0000,0.0000,0.0014,0.0001,0.0001,0.0064,0.0022,0.0001,0.0000,0.0000,0.0023,0.0000,0.0000,0.0018,0.0000,0.0000,0.0000,8557.2061
25,"Sewerage, waste management, remediation activities",0.0000,0.0000,0.0000,0.0014,0.0000,0.0018,0.0106,0.0000,0.0000,0.0000,0.0000,0.0000,0.0045,0.0081,0.0038,0.0803,0.0083,0.0044,0.0217,0.0303,0.0185,0.0546,0.0079,0.0003,0.0000,0.0001,0.2204,0.0373,0.1218,0.0370,0.0221,0.0019,0.0019,0.0006,0.0000,0.0005,0.0485,0.0170,0.0000,0.0026,0.0001,0.0030,0.0013,0.0000,0.0443,0.0448,0.1056,0.0020,0.0000,0.0001,0.0029,0.0002,0.0002,0.0135,0.0047,0.0002,0.0000,0.0000,0.0049,0.0000,0.0000,0.0039,0.0000,0.0000,0.0000,28485.5199
26,Construction,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0395,0.0293,0.1446,0.1492,0.0912,0.0000,0.0524,0.0000,0.0000,0.0000,0.4141,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0644,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0152,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,67715.2048
27,Wholesale and retail trade and repair of motor vehicles and motorcycles,0.0000,0.0000,0.0000,0.0017,0.0000,0.0022,0.0127,0.0000,0.0000,0.0000,0.0001,0.0000,0.0054,0.0097,0.0046,0.0963,0.0012,0.0005,0.0027,0.0909,0.0556,0.0655,0.0010,0.0004,0.0000,0.0001,0.0212,0.0447,0.1461,0.0444,0.0266,0.0023,0.0022,0.0007,0.0000,0.0006,0.0582,0.0204,0.0000,0.0057,0.0001,0.0036,0.0016,0.0000,0.0532,0.0538,0.1268,0.0005,0.0000,0.0001,0.0035,0.0002,0.0002,0.0162,0.0056,0.0002,0.0000,0.0000,0.0059,0.0000,0.0000,0.0047,0.0000,0.0000,0.0000,37530.0062
28,"Wholesale trade, except of motor vehicles and motorcycles",0.0000,0.0000,0.0000,0.0019,0.0000,0.0024,0.0136,0.0000,0.0000,0.0000,0.0001,0.0000,0.0058,0.0103,0.0049,0.1031,0.0127,0.0047,0.0234,0.0135,0.0082,0.0702,0.0085,0.0004,0.0000,0.0001,0.0311,0.0479,0.1565,0.0475,0.0284,0.0024,0.0024,0.0008,0.0000,0.0006,0.0623,0.0218,0.0000,0.0116,0.0001,0.0038,0.0017,0.0000,0.0569,0.0576,0.1357,0.0076,0.0000,0.0001,0.0038,0.0002,0.0003,0.0174,0.0060,0.0002,0.0000,0.0000,0.0063,0.0000,0.0000,0.0050,0.0000,0.0000,0.0000,143282.1231
29,"Retail trade, except of motor vehicles and motorcycles",0.0000,0.0000,0.0000,0.0018,0.0000,0.0023,0.0134,0.0000,0.0000,0.0000,0.0001,0.0000,0.0057,0.0102,0.0048,0.1015,0.0091,0.0037,0.0182,0.0112,0.0068,0.0691,0.0066,0.0004,0.0000,0.0001,0.0581,0.0472,0.1540,0.0467,0.0280,0.0024,0.0024,0.0007,0.0000,0.0006,0.0614,0.0215,0.0000,0.0209,0.0001,0.0038,0.0017,0.0000,0.0560,0.0567,0.1336,0.0004,0.0000,0.0001,0.0037,0.0002,0.0002,0.0171,0.0059,0.0002,0.0000,0.0000,0.0062,0.0000,0.0000,0.0049,0.0000,0.0000,0.0000,110609.7212
30,Land transport and transport via pipelines,0.0001,0.0000,0.0000,0.0010,0.0000,0.0012,0.0070,0.0000,0.0000,0.0000,0.0000,0.0000,0.0030,0.0053,0.0025,0.0530,0.0044,0.0033,0.0162,0.2456,0.1502,0.0360,0.0059,0.0002,0.0000,0.0000,0.0998,0.0246,0.0804,0.0244,0.0146,0.0012,0.0012,0.0004,0.0000,0.0003,0.0320,0.0112,0.0000,0.0208,0.0000,0.0020,0.0009,0.0000,0.0292,0.0296,0.0697,0.0024,0.0000,0.0001,0.0019,0.0001,0.0001,0.0089,0.0031,0.0001,0.0000,0.0000,0.0033,0.0000,0.0000,0.0026,0.0000,0.0000,0.0000,40704.2518

In [128]:
invTableNama.iloc[:-1,:-1].shape

(65, 66)

In [129]:
invTableNama.iloc[:-1,:-1].to_pickle("./invTableNama.xp")

<span style="color: DodgerBlue;">
==============================================================================================  
    
### create investment table, nama, with IPF version

IPF (Iterative Proportional Fitting) or Furness algorithm 
see:  
Michael Lahr and Louis De Mesnard. Biproportional techniques in input-
output analysis: table updating and structural analysis. Economic Systems Research, 16(2):115–134,
2004. (Reffering to Furness);  
Kenneth P Furness. Time function iteration. Traffic Engineering and Control, 7(7):458–460,
1965. (Difficult to find).

For a direct presentation, use [_Iterative proportional fitting_ in Wikipedia](https://en.wikipedia.org/wiki/Iterative_proportional_fitting)

==============================================================================================  
</span>

In [130]:
np.set_printoptions(threshold=np.inf)

In [131]:
#data_partNu is saved above, after nama column insertion, but before the raw correction inserted
#data_partNu

In [132]:
len(buyingSectorsPurchases)

65

In [133]:
len(GrossFixedCapitalFormation)

65

In [134]:
correctionCoef

np.float64(0.8776735944593085)

In [135]:
GrossFixedCapitalFormationCorrected = np.array(GrossFixedCapitalFormation)*correctionCoef

In [136]:
GrossFixedCapitalFormationCorrected.sum()

np.float64(2914103.3789870543)

In [137]:
def ipf(matrix_seed, row_totals, col_totals, max_iter=1000, tol=1e-6):
    """
    Runs the IPF algorithm to adjust the matrix to row and column totals.

    Args:
        matrix_seed (np.ndarray): initial matrix (seed).
        row_totals (np.ndarray): array of row totals.
        col_totals (np.ndarray): array of column totals.
        max_iter (int): maximum number of iterations.
        tol (float): convergence tolerance.

    Returns:
        np.ndarray: estimated matrix.
    """
    T = matrix_seed.astype(float)
    count=0
    for _ in range(max_iter):
        count+=1
        # Resizing across rows
        row_sums = T.sum(axis=1, keepdims=True)
        np.divide(T, row_sums, out=T, where=row_sums != 0)
        T *= row_totals[:, np.newaxis]

        # Resizing across columns
        col_sums = T.sum(axis=0, keepdims=True)
        np.divide(T, col_sums, out=T, where=col_sums != 0)
        T *= col_totals[np.newaxis, :]

        # Convergence control
        if np.all(np.abs(T.sum(axis=1) - row_totals) < tol) and \
           np.all(np.abs(T.sum(axis=0) - col_totals) < tol):
            break

    print('iterations = ',count)

    return T

In [138]:
bSP = np.array(buyingSectorsPurchases)

In [139]:
np.sum(data_partNu)

2914103.3805692466

In [140]:
data_part_adj = ipf(data_partNu,bSP,GrossFixedCapitalFormationCorrected,max_iter=1000, tol=1e-2)

iterations =  30

In [141]:
np.sum(data_part_adj)

np.float64(2914103.378987055)

In [142]:
data_part_adj.shape

(65, 65)

In [143]:
tot=0
for i in range(65):
    for j in range(65):
        tot+=abs(data_part_adj[i,j]-data_partNu[i,j])
tot

np.float64(2306949.2603041655)

very huge difference

In [144]:
#row test
for i in range(65):
    print(np.sum(data_part_adj[i, :]),bSP[i],np.sum(data_part_adj[i, :])-bSP[i])

87269.68015708454 87269.68016368477 -6.600224878638983e-06
10474.217246462484 10474.217260554517 -1.4092032870394178e-05
3314.728640304631 3314.7286303589467 9.945684269041521e-06
19702.41988564415 19702.419822338423 6.330572796287015e-05
41624.61016647061 41624.609969521654 0.00019694895308930427
6579.484460607758 6579.484397176533 6.343122458929429e-05
6417.294666951277 6417.294664186711 2.7645655791275203e-06
5143.06387600573 5143.063869708754 6.296975698205642e-06
2635.2253495732125 2635.225338895352 1.0677860700525343e-05
10611.886992627296 10611.886911777669 8.084962792054284e-05
55700.4695585901 55700.46907269352 0.0004858965767198242
61026.521094661446 61026.52045931569 0.0006353457574732602
12496.056137058704 12496.056081260198 5.579850585490931e-05
14430.798459675754 14430.798420140105 3.9535649193567224e-05
12989.482091384074 12989.482062754898 2.8629176085814834e-05
28780.03823010076 28780.038146130024 8.397073543164879e-05
26187.355360400714 26187.355046425848 0.00031397486600326374
17167.494488878663 17167.494297225297 0.0001916533656185493
41000.31901163808 41000.31857398842 0.00043764965812442824
43801.11114164541 43801.110775484995 0.0003661604132503271
10025.739767400062 10025.739677648504 8.975155833468307e-05
11558.745085642697 11558.74511088037 -2.523767398088239e-05
9777.760400175068 9777.760358037252 4.213781539874617e-05
149979.61681327637 149979.61725286717 -0.0004395908035803586
8557.206033602914 8557.206084553547 -5.095063352200668e-05
28485.51978546759 28485.519932858148 -0.00014739055768586695
67715.2048389417 67715.20478862397 5.031772889196873e-05
37530.00626426528 37530.00623902961 2.5235669454559684e-05
143282.1232664633 143282.1231107478 0.00015571550466120243
110609.72104353025 110609.72122426344 -0.00018073318642564118
40704.25185790657 40704.25178946342 6.844315066700801e-05
6705.260943878974 6705.260929085752 1.4793222362641245e-05
3394.094122196415 3394.0941117964194 1.0399995517218485e-05
40151.721463489164 40151.721698323825 -0.00023483466065954417
9456.33015829039 9456.33015151278 6.777609087293968e-06
80729.14465552676 80729.14479331418 -0.00013778741413261741
17795.571640364873 17795.57154381381 9.655106259742752e-05
11681.459341364995 11681.45929715438 4.421061385073699e-05
19511.06395504468 19511.06385007167 0.00010497300900169648
67249.65083094618 67249.65022832574 0.0006026204355293885
26655.95076538618 26655.95066435996 0.00010102622036356479
6424.0348215708345 6424.034785724611 3.5846223909175023e-05
6090.9369028784095 6090.936885153171 1.7725238649290986e-05
500084.4916198667 500084.49738058116 -0.005760714469943196
629444.6744353339 629444.6811616754 -0.0067263414384797215
19239.26722822789 19239.267160060546 6.816734457970597e-05
7312.337540963701 7312.337497209594 4.3754106627602596e-05
4825.753763955835 4825.7536930995175 7.085631750669563e-05
2172.129476566896 2172.1294635977797 1.2969116141903214e-05
2284.6739547944267 2284.6739484082746 6.386152108461829e-06
3504.481449496471 3504.4814368639773 1.2632493962883018e-05
3881.0408714467317 3881.040875740288 -4.293556230550166e-06
313.31450036709725 313.31449882731613 1.5397811239381554e-06
6683.862767899225 6683.862751297045 1.6602180039626546e-05
107330.53232583043 107330.53274561175 -0.0004197813250357285
29247.15173272974 29247.15139764891 0.00033508082924527116
112416.46792310117 112416.4675125133 0.0004105878615519032
56326.04071379848 56326.04085322122 -0.00013942273653810844
4022.480739147404 4022.480729974563 9.172841146209976e-06
3201.619871872416 3201.619887922663 -1.6050247268140083e-05
175.74281981482724 175.7428200786476 -2.6382036821814836e-07
19.308318620937857 19.308318539199735 8.173812204859132e-08
194.6351598453458 194.63515968781306 1.5753275306451542e-07
0.0 0.0 0.0
0.0 0.0 0.0

In [145]:
#col test
for j in range(65):
    print(np.sum(data_part_adj[:, j]),GrossFixedCapitalFormationCorrected[j],\
          np.sum(data_part_adj[:, j])-GrossFixedCapitalFormationCorrected[j])

6533.9463947836575 6533.946394783657 9.094947017729282e-13
400.5614517752838 400.5614517752838 0.0
49.29014906483477 49.290149064834765 7.105427357601002e-15
1113.2762941559656 1113.2762941559654 2.2737367544323206e-13
0.4827204769526197 0.4827204769526197 0.0
1407.6743479454512 1407.674347945451 2.2737367544323206e-13
8159.038045548567 8159.038045548567 0.0
0.45639026911884045 0.45639026911884045 0.0
5.029069696251838 5.029069696251838 0.0
0.0 0.0 0.0
35.96706390094245 35.967063900942456 -7.105427357601002e-15
0.3159624940053511 0.31596249400535104 5.551115123125783e-17
3476.184252103095 3476.184252103094 9.094947017729282e-13
6186.2560003386025 6186.2560003386025 0.0
2920.2394671647344 2920.239467164734 4.547473508864641e-13
61654.972644824506 61654.9726448245 7.275957614183426e-12
87586.95363858974 87586.95363858974 0.0
42258.78993712724 42258.789937127236 7.275957614183426e-12
208473.3261714426 208473.3261714426 0.0
146138.27058847935 146138.27058847938 -2.9103830456733704e-11
89334.33155127065 89334.33155127066 -1.4551915228366852e-11
41950.87570998307 41950.87570998308 -7.275957614183426e-12
75522.75959491015 75522.75959491015 0.0
231.6180615778115 231.6180615778115 0.0
9.584195651495648 9.584195651495648 0.0
49.044400458386164 49.04440045838616 7.105427357601002e-15
1150294.196651554 1150294.196651554 0.0
28643.325368712703 28643.325368712703 0.0
93545.21636929562 93545.21636929564 -1.4551915228366852e-11
28389.098435341617 28389.09843534162 -3.637978807091713e-12
17007.57646690437 17007.57646690437 0.0
1450.443382203453 1450.4433822034532 -2.2737367544323206e-13
1439.8147549745513 1439.814754974551 2.2737367544323206e-13
451.633278236871 451.633278236871 0.0
0.0 0.0 0.0
367.578478095503 367.578478095503 0.0
37259.56991982297 37259.56991982296 7.275957614183426e-12
13038.622375192097 13038.622375192095 1.8189894035458565e-12
0.0 0.0 0.0
259059.05311273847 259059.05311273845 2.9103830456733704e-11
50.05372509201436 50.05372509201436 0.0
2292.3956613682685 2292.395661368268 4.547473508864641e-13
1023.7184805773373 1023.7184805773375 -1.1368683772161603e-13
0.0 0.0 0.0
34038.69213961213 34038.69213961214 -7.275957614183426e-12
34441.77251460352 34441.77251460352 0.0
81137.70274567138 81137.7027456714 -1.4551915228366852e-11
323123.64350420726 323123.6435042072 5.820766091346741e-11
6.099831481492194 6.099831481492194 0.0
73.79479582213864 73.79479582213865 -1.4210854715202004e-14
2255.0506499240237 2255.050649924024 -4.547473508864641e-13
129.92202218781145 129.92202218781142 2.842170943040401e-14
150.34548673087954 150.34548673087954 0.0
10376.076652096559 10376.076652096559 0.0
3603.2099514291895 3603.2099514291895 0.0
134.64390612600255 134.64390612600252 2.842170943040401e-14
7.196923474566328 7.196923474566329 -8.881784197001252e-16
8.013159917413487 8.013159917413487 0.0
3794.455027661874 3794.4550276618734 4.547473508864641e-13
8.16236442847157 8.16236442847157 0.0
7.407565137236565 7.407565137236563 1.7763568394002505e-15
2981.729279192554 2981.7292791925533 4.547473508864641e-13
6.503561334943476 6.503561334943476 0.0
0.06143715161215159 0.0614371516121516 -1.3877787807814457e-17
7.354904721569005 7.354904721569006 -8.881784197001252e-16

In [146]:
for i in range(65):
    for j in range(65):
        if data_part_adj[i,j]<0: print('error')

In [147]:
#Iterative Proportional Fitting table
invTableNamaIPF = pd.DataFrame(data_part_adj)

In [148]:
invTableNamaIPF.insert(0, 'tmp', '')

In [149]:
invTableNamaIPF.columns=[mini_naio['IND_USE (Labels)']]

In [150]:
invTableNamaIPF.rename(columns={'Total': 'sectors'}, inplace=True)

In [151]:
invTableNamaIPF['sectors']=nama.index.tolist()

In [152]:
invTableNamaIPF['Totals'] = ''

In [153]:
invTableNamaIPF.loc[len(invTableNamaIPF)] = [''] * invTableNamaIPF.shape[1]

In [154]:
#Fill last column with row totals
invTableNamaIPF.iloc[:-1, -1] = data_part_adj.sum(axis=1)

# Fill last row with column totals
invTableNamaIPF.iloc[-1, 1:-1] = data_part_adj.sum(axis=0)

# grand total
invTableNamaIPF.iloc[-1,-1] = data_part_adj.sum()

In [155]:
invTableNamaIPF

IND_USE (Labels),sectors,"Products of agriculture, hunting and related services","Products of forestry, logging and related services",Fish and other fishing products; aquaculture products; support services to fishing,Mining and quarrying,"Food, beverages and tobacco products","Textiles, wearing apparel, leather and related products","Wood and of products of wood and cork, except furniture; articles of straw and plaiting materials",Paper and paper products,Printing and recording services,Coke and refined petroleum products,Chemicals and chemical products,Basic pharmaceutical products and pharmaceutical preparations,Rubber and plastic products,Other non-metallic mineral products,Basic metals,"Fabricated metal products, except machinery and equipment","Computer, electronic and optical products",Electrical equipment,Machinery and equipment n.e.c.,"Motor vehicles, trailers and semi-trailers",Other transport equipment,Furniture and other manufactured goods,Repair and installation services of machinery and equipment,"Electricity, gas, steam and air conditioning",Natural water; water treatment and supply services,"Sewerage services; sewage sludge; waste collection, treatment and disposal services; materials recovery services; remediation services and other waste management services",Constructions and construction works,Wholesale and retail trade and repair services of motor vehicles and motorcycles,"Wholesale trade services, except of motor vehicles and motorcycles","Retail trade services, except of motor vehicles and motorcycles",Land transport services and transport services via pipelines,Water transport services,Air transport services,Warehousing and support services for transportation,Postal and courier services,Accommodation and food services,Publishing services,"Motion picture, video and television programme production services, sound recording and music publishing; programming and broadcasting services",Telecommunications services,"Computer programming, consultancy and related services; Information services","Financial services, except insurance and pension funding","Insurance, reinsurance and pension funding services, except compulsory social security",Services auxiliary to financial services and insurance services,Imputed rents of owner-occupied dwellings,Real estate services excluding imputed rents,Legal and accounting services; services of head offices; management consultancy services,Architectural and engineering services; technical testing and analysis services,Scientific research and development services,Advertising and market research services,"Other professional, scientific and technical services and veterinary services",Rental and leasing services,Employment services,"Travel agency, tour operator and other reservation services and related services","Security and investigation services; services to buildings and landscape; office administrative, office support and other business support services",Public administration and defence services; compulsory social security services,Education services,Human health services,Residential care services; social work services without accommodation,"Creative, arts, entertainment, library, archive, museum, other cultural services; gambling and betting services",Sporting services and amusement and recreation services,Services furnished by membership organisations,Repair services of computers and personal and household goods,Other personal services,Services of households as employers; undifferentiated goods and services produced by households for own use,Services provided by extraterritorial organisations and bodies,Totals
0,"Crop and animal production, hunting and related service activities",5234.5090,320.8999,39.4876,31.2521,0.0136,39.5164,229.0417,0.0128,0.1412,0.0000,1.0097,0.0089,97.5840,173.6615,81.9774,1730.7876,2058.7681,4331.9556,21370.6354,11716.9509,7162.5726,1177.6512,7741.8507,6.5020,0.2690,1.3768,11257.1058,804.0797,2626.0153,796.9430,477.4392,40.7171,40.4187,12.6783,0.0000,10.3187,1045.9562,366.0221,0.0000,23.7246,1.4051,64.3525,28.7380,0.0000,955.5392,966.8546,2277.7097,1264.1269,0.1712,2.0716,63.3041,3.6472,4.2205,291.2788,101.1498,3.7797,0.2020,0.2249,106.5185,0.2291,0.2079,83.7035,0.1826,0.0017,0.2065,87269.6802
1,Forestry and logging,1006.1265,61.6803,7.5899,5.0467,0.0022,6.3813,36.9869,0.0021,0.0228,0.0000,0.1630,0.0014,15.7584,28.0438,13.2381,279.4967,516.4434,250.7443,1236.9850,1326.8078,811.0776,190.1733,448.1174,1.0500,0.0434,0.2223,1741.9976,129.8470,424.0627,128.6945,77.0994,6.5752,6.5270,2.0474,0.0000,1.6663,168.9065,59.1072,0.0000,506.1729,0.2269,10.3920,4.6408,0.0000,154.3055,156.1327,367.8165,179.0366,0.0277,0.3345,10.2227,0.5890,0.6816,47.0372,16.3342,0.6104,0.0326,0.0363,17.2012,0.0370,0.0336,13.5169,0.0295,0.0003,0.0333,10474.2172
2,Fishing and aquaculture,0.0000,0.0000,0.0000,0.5387,0.0002,0.6812,3.9483,0.0002,0.0024,0.0000,0.0174,0.0002,1.6822,2.9936,1.4131,29.8356,3.5192,75.8929,374.3991,1324.4574,809.6409,20.3006,135.6320,0.1121,0.0046,0.0237,120.9332,13.8609,45.2677,13.7379,8.2302,0.7019,0.6967,0.2186,0.0000,0.1779,18.0304,6.3096,0.0000,7.6909,0.0242,1.1093,0.4954,0.0000,16.4718,16.6668,39.2636,208.3498,0.0030,0.0357,1.0912,0.0629,0.0728,5.0211,1.7436,0.0652,0.0035,0.0039,1.8362,0.0039,0.0036,1.4429,0.0031,0.0000,0.0036,3314.7286
3,Mining and quarrying,0.9128,0.0560,0.0069,1.7096,0.0007,2.1617,12.5296,0.0007,0.0077,0.0000,0.0552,0.0005,5.3383,9.5000,4.4845,94.6815,785.3879,460.1872,2270.2202,672.1070,410.8591,64.4225,822.4232,0.3557,0.0147,0.0753,5425.4799,43.9866,143.6542,43.5962,26.1180,2.2274,2.2111,0.6936,0.0000,0.5645,57.2183,20.0230,0.0000,1367.3527,0.0769,3.5204,1.5721,0.0000,52.2721,52.8911,124.6004,6680.6981,0.0094,0.1133,3.4630,0.1995,0.2309,15.9342,5.5333,0.2068,0.0111,0.0123,5.8270,0.0125,0.0114,4.5789,0.0100,0.0001,0.0113,19702.4199
4,Manufacture of food products; beverages and tobacco products,8.2835,0.5078,0.0625,1.8729,0.0008,2.3682,13.7265,0.0008,0.0085,0.0000,0.0605,0.0005,5.8482,10.4076,4.9129,103.7266,1556.9666,1861.9482,9185.4628,2912.5582,1780.4469,70.5770,3327.5792,0.3897,0.0161,0.0825,5326.2920,48.1887,157.3779,47.7610,28.6131,2.4402,2.4223,0.7598,0.0000,0.6184,62.6845,21.9358,0.0000,6390.7936,0.0842,3.8567,1.7223,0.0000,57.2657,57.9439,136.5038,8389.9110,0.0103,0.1242,3.7938,0.2186,0.2529,17.4564,6.0619,0.2265,0.0121,0.0135,6.3837,0.0137,0.0125,5.0164,0.0109,0.0001,0.0124,41624.6102
5,"Manufacture of textiles, wearing apparel, leather and related products",0.0000,0.0000,0.0000,0.1160,0.0001,0.1467,0.8503,0.0000,0.0005,0.0000,0.0037,0.0000,0.3623,0.6447,0.3043,6.4255,274.7295,168.8422,832.9412,159.3100,97.3862,4.3720,301.7461,0.0241,0.0010,0.0051,268.3718,2.9851,9.7489,2.9586,1.7725,0.1512,0.1501,0.0471,0.0000,0.0383,3.8831,1.3588,0.0000,1172.7429,0.0052,0.2389,0.1067,0.0000,3.5474,3.5894,8.4559,3248.6668,0.0006,0.0077,0.2350,0.0135,0.0157,1.0814,0.3755,0.0140,0.0008,0.0008,0.3954,0.0009,0.0008,0.3107,0.0007,0.0000,0.0008,6579.4845
6,"Manufacture of wood and of products of wood and cork, except furniture; manufacture of articles of straw and plaiting materials",93.8199,5.7516,0.7077,1.5468,0.0007,1.9559,11.3365,0.0006,0.0070,0.0000,0.0500,0.0004,4.8300,8.5954,4.0575,85.6659,467.1341,363.4340,1792.9123,514.9838,314.8096,58.2882,649.5108,0.3218,0.0133,0.0681,1101.9850,39.7982,129.9755,39.4450,23.6310,2.0153,2.0005,0.6275,0.0000,0.5107,51.7700,18.1164,0.0000,212.1582,0.0695,3.1851,1.4224,0.0000,47.2947,47.8548,112.7360,170.1752,0.0085,0.1025,3.1333,0.1805,0.2089,14.4169,5.0064,0.1871,0.0100,0.0111,5.2722,0.0113,0.0103,4.1429,0.0090,0.0001,0.0102,6417.2947
7,Manufacture of paper and paper products,0.0000,0.0000,0.0000,1.7008,0.0007,2.1505,12.4648,0.0007,0.0077,0.0000,0.0549,0.0005,5.3107,9.4509,4.4613,94.1920,440.3823,296.2662,1461.5562,16.8221,10.2834,64.0895,529.4719,0.3538,0.0146,0.0749,778.0985,43.7592,142.9116,43.3708,25.9829,2.2159,2.1996,0.6900,0.0000,0.5616,56.9225,19.9195,0.0000,316.1073,0.0765,3.5022,1.5640,0.0000,52.0019,52.6177,123.9563,491.5174,0.0093,0.1127,3.4451,0.1985,0.2297,15.8518,5.5047,0.2057,0.0110,0.0122,5.7969,0.0125,0.0113,4.5553,0.0099,0.0001,0.0112,5143.0639
8,Printing and reproduction of recorded media,0.0000,0.0000,0.0000,0.4099,0.0002,0.5184,3.0044,0.0002,0.0019,0.0000,0.0132,0.0001,1.2801,2.2780,1.0753,22.7035,158.3201,122.6339,604.9839,90.2129,55.1471,15.4478,219.1650,0.0853,0.0035,0.0181,180.0609,10.5475,34.4466,10.4539,6.2628,0.5341,0.5302,0.1663,0.0000,0.1354,13.7203,4.8013,0.0000,921.6602,0.0184,0.8441,0.3770,0.0000,12.5342,12.6827,29.8778,89.5971,0.0022,0.0272,0.8304,0.0478,0.0554,3.8208,1.3268,0.0496,0.0027,0.0030,1.3973,0.0030,0.0027,1.0980,0.0024,0.0000,0.0027,2635.2253
9,Manufacture of coke and refined petroleum products,0.0000,0.0000,0.0000,0.9609,0.0004,1.2151,7.0426,0.0004,0.0043,0.0000,0.0310,0.0003,3.0005,5.3397,2.5206,53.2182,283.3337,329.8693,1627.3288,300.6405,183.7816,36.2104,589.5256,0.1999,0.0083,0.0423,804.9088,24.7238,80.7447,24.5044,14.6803,1.2520,1.2428,0.3898,0.0000,0.3173,32.1610,11.2544,0.0000,1693.4630,0.0432,1.9787,0.8836,0.0000,29.3809,29.7288,70.0350,4345.5923,0.0053,0.0637,1.9465,0.1121,0.1298,8.9562,3.1102,0.1162,0.0062,0.0069,3.2752,0.0070,0.0064,2.5737,0.0056,0.0001,0.0063,10611.8870
10,Manufacture of chemicals and chemical products,0.7489,0.0459,0.0056,3.9652,0.0017,5.0138,29.0606,0.0016,0.0179,0.0000,0.1281,0.0011,12.3814,22.0340,10.4012,219.6010,1777.3264,1692.4974,8349.5188,2072.5862,1266.9721,149.4195,3024.7452,0.8250,0.0341,0.1747,3007.5441,102.0210,333.1867,101.1155,60.5771,5.1661,5.1283,1.6086,0.0000,1.3092,132.7101,46.4406,0.0000,5299.0133,0.1783,8.1650,3.6463,0.0000,121.2381,122.6737,288.9940,27338.3660,0.0217,0.2628,8.0320,0.4628,0.5355,36.9572,12.8338,0.4796,0.0256,0.0285,13.5150,0.0291,0.0264,10.6202,0.0232,0.0002,0.0262,55700.4696
11,Manufacture of basic pharmaceutical products and pharmaceutical preparations,0.3987,0.0244,0.0030,4.6254,0.0020,5.8486,33.8991,0.0019,0.0209,0.0000,0.1494,0.0013,14.4428,25.7026,12.1330,256.1634,785.3132,868.3522,4283.8015,725.3580,443.4114,174.2970,1551.8749,0.9623,0.0398,0.2038,4152.5533,119.0070,388.6606,117.9507,70.6629,6.0263,5.9821,1.8764,0.0000,1.5272,154.8056,54.1727,0.0000,4674.8436,0.2080,9.5244,4.2533,0.0000,141.4236,143.0983,337.1100,41357.9590,0.0253,0.3066,9.3693,0.5398,0.6247,43.1104,14.9706,0.5594,0.0299,0.0333,15.7652,0.0339,0.0308,12.3885,0.0270,0.0003,0.0306,61026.5211
12,Manufacture of rubber and plastic products,18.9191,1.1598,0.1427,2.6439,0.0011,3.3431,19.3771,0.0011,0.0119,0.0000,0.0854,0.0008,8.2557,14.6919,6.9353,146.4256,854.4472,552.9333,2727.7604,436.2590,266.6852,99.6299,988.1743,0.5501,0.0228,0.1165,1431.1011,68.0256,222.1623,67.4218,40.3916,3.4447,3.4194,1.0726,0.0000,0.8730,88.4885,30.9657,0.0000,350.4313,0.1189,5.4443,2.4312,0.0000,80.8391,81.7964,192.6955,3620.4306,0.0145,0.1753,5.3556,0.3086,0.3571,24.6423,8.5573,0.3198,0.0171,0.0190,9.0115,0.0194,0.0176,7.0814,0.0154,0.0001,0.0175,12496.0561
13,Manufacture of other non-metallic mineral products,0.0000,0.0000,0.0000,3.6567,0.0016,4.6237,26.7994,0.0015,0.0165,0.0000,0.1181,0.0010,11.4180,20.3196,9.5919,202.5140,814.8048,493.9637,2436.8483,2135.4427,1305.3962,137.7932,882.7868,0.7608,0.0315,0.1611,1620.4970,94.0828,307.2617,93.2478,55.8636,4.7642,4.7293,1.4834,0.0000,1.2074,122.3840,42.8271,0.0000,774.6188,0.1644,7.5297,3.3625,0.0000,111.8046,113.1286,266.5076,2240.9298,0.0200,0.2424,7.4070,0.4267,0.4938,34.0816,11.8352,0.4423,0.0236,0.0263,12.4634,0.0268,0.0243,9.7939,0.0214,0.0002,0.0242,14430.7985
14,Manufacture of basic metals,0.0000,0.0000,0.0000,4.7991,0.0021,6.0682,35.1721,0.0020,0.0217,0.0000,0.1550,0.0014,14.9852,26.6678,12.5886,265.7834,772.0151,601.6196,2967.9421,114.0182,69.6994,180.8426,1075.1840,0.9985,0.0413,0.2114,1711.3912,123.4762,403.2564,122.3802,73.3166,6.2526,6.2068,1.9469,0.0000,1.5846,160.6192,56.2071,0.0000,1195.8673,0.2158,9.8821,4.4131,0.0000,146.7346,148.4722,349.7699,2217.1506,0.0263,0.3181,9.7211,0.5601,0.6481,44.7294,15.5328,0.5804,0.0310,0.0345,16.3572,0.0352,0.0319,12.8537,0.0280,0.0003,0.0317,12989.4821
15,"Manufacture of fabricated metal products, except machinery and equipment",8.9193,0.5468,0.0673,9.7607,0.0042,12.3419,71.5348,0.0040,0.0441,0.0000,0.3153,0.0028,30.4776,54.2383,25.6033,540.5630,3157.8097,1312.0309,6472.5809,748.7432,457.7068,367.8064,2344.7948,2.0307,0.0840,0.4300,2787.2808,251.1318,820.1623,248.9028,149.1148,12.7168,12.6236,3.9597,0.0000,3.2228,326.6751,114.3168,0.0000,1868.0947,0.4388,20.0987,8.9755,0.0000,298.4359,301.9700,711.3789,5015.6215,0.0535,0.6470,19.7713,1.1391,1.3182,90.9728,31.5913,1.1805,0.0631,0.0703,33.2681,0.0716,0.0649,26.1425,0.0570,0.0005,0.0645,28780.0382
16,"Manufacture of computer, electronic and optical products",0.0000,0.0000,0.0000,0.5169,0.0002,0.6535,3.7880,0.0002,0.0023,0.0000,0.0167,0.0001,1.6139,2.8721,1.3558,28.6245,1041.5135,164.2925,810.4965,154.3487,94.3534,19.4765,293.6152,0.1075,0.0044,0.0228,480.0531,13.2982,43.4302,13.1802,7.8961,0.6734,0.6685,0.2097,0.0000,0.1707,17.2985,6.0534,0.0000,5431.0961,0.0232,1.0643,0.4753,0.0000,15.8031,15.9903,37.6698,17473.6924,0.0028,0.0343,1.0470,0.0603,0.0698,4.8173,1.6729,0.0625,0.0033,0.0037,1.7617,0.0038,0.0034,1.3843,0.0030,0.0000,0.0034,26187.3554
17,Manufacture of electrical equipment,0.0000,0.0000,0.0000,0.5538,0.0002,0.7002,4.0585,0.0002,0.0025,0.0000,0.0179,0.0002,1.7292,3.0772,1.4526,30.6689,1520.2413,244.9278,1208.2909,138.8193,84.8603,20.8675,437.7225,0.1152,0.0048,0.0244,387.2053,14.2480,46.5320,14.1215,8.4600,0.7215,0.7162,0.2247,0.0000,0.1828,18.5339,6.4858,0.0000,2025.9029,0.0249,1.1403,0.5092,0.0000,16.9318,17.1323,40.3602,10858.2113,0.0030,0.0367,1.1217,0.0646,0.0748,5.1613,1.7923,0.0670,0.0036,0.0040,1.8875,0.0041,0.0037,1.4832,0.0032,0.0000,0.0037,17167.4945
18,Manufacture of machinery and equipment n.e.c.,0.0000,0.0000,0.0000,1.7091,0.0007,2.1610,12.5256,0.0007,0.0077,0.0000,0.0552,0.0005,5.3366,9.4970,4.4831,94.6516,1162.1192,634.6055,3130.6699,729.4366,445.9046,64.4023,1134.1347,0.3556,0.0147,0.0753,1585.2179,43.9727,143.6090,43.5824,26.1097,2.2267,2.2104,0.6933,0.0000,0.5643,57.2002,20.0167,0.0000,6418.7339,0.0768,3.5192,1.5716,0.0000,52.2556,52.8744,124.5612,24953.0219,0.0094,0.1133,3.4619,0.1995,0.2308,15.9292,5.5316,0.2067,0.0110,0.0123,5.8252,0.0125,0.0114,4.5775,0.0100,0.0001,0.0113,41000.3190
19,"Manufacture of motor vehicles, trailers and semi-trailers",0.0000,0.0000,0.0000,11.5379,0.0050,14.5890,84.5594,0.0047,0.0521,0.0000,0.3728,0.0033,36.0268,64.1137,30.2651,638.9857,3034.4512,1113.7163,5494.2447,0.0000,0.0000,434.7745,1990.3770,2.4005,0.0993,0.5083,1177.1994,296.8564,969.4929,294.2217,176.2647,15.0322,14.9221,4.6807,0.0000,3.8095,386.1543,135.1309,0.0000,2124.0587,0.5188,23.7581,10.6097,0.0000,352.7735,356.9509,840.9027,23422.6165,0.0632,0.7648,23.3711,1.3465,1.5582,107.5366,37.3433,1.3954,0.0746,0.0830,39.3253,0.0846,0.0768,30.9023,0.0674,0.0006,0.0762,43801.1111
20,Manufacture of other transport equipment,0.0000,0.0000,0.0000,2.0893,0.0009,2.6418,15.3121,0.0009,0.0094,0.0000,0.0675,0.0006,6.5238,11.6098,5.4804,115.7084,568.5670,69.1102,340.9381,912.3716,557.7328,78.7296,123.5102,0.4347,0.0180,0.0920,295.2241,53.7552,175.5571,53.2781,31.9183,2.7221,2.7021,0.8476,0.0000,0.6898,69.9254,24.4697,0.0000,360.9280,0.0939,4.3022,1.9212,0.0000,63.8807,64.6372,152.2718,5811.4696,0.0114,0.1385,4.2321,0.2438,0.2822,19.4729,6.7622,0.2527,0.0135,0.0150,7.1211,0.0153,0.0139,5.5958,0.0122,0.0001,0.0138,10025.7398
21,Manufacture of furniture; other manufacturing,0.0000,0.0000,0.0000,3.4423,0.0015,4.3526,25.2283,0.0014,0.0156,0.0000,0.1112,0.0010,10.7486,19.1284,9.0296,190.6416,641.6418,273.4387,1348.9426,468.6212,286.4682,129.7151,488.6758,0.7162,0.0296,0.1516,4289.5463,88.5672,289.2486,87.7811,52.5887,4.4849,4.4520,1.3965,0.0000,1.1366,115.2093,40.3164,0.0000,969.5862,0.1548,7.0883,3.1654,0.0000,105.2501,106.4964,250.8836,1167.4713,0.0189,0.2282,6.9728,0.4017,0.4649,32.0836,11.1414,0.4163,0.0223,0.0248,11.7327,0.0252,0.0229,9.2197,0.0201,0.0002,0.0227,11558.7451
22,Repair and installation of machinery and equipment,0.0000,0.0000,0.0000,2.3615,0.0010,2.9860,17.3070,0.0010,0.0107,0.0000,0.0763,0.0007,7.3737,13.1223,6.1944,130.7831,962.2602,156.3012,771.0735,828.8761,506.6920,88.9866,279.3336,0.4913,0.0203,0.1040,1016.1937,60.7585,198.4290,60.2192,36.0766,3.0767,3.0541,0.9580,0.0000,0.7797,79.0353,27.6576,0.0000,2002.3371,0.1062,4.8627,2.1715,0.0000,72.2032,73.0582,172.1100,2140.3621,0.0129,0.1565,4.7834,0.2756,0.3189,22.0098,7.6432,0.2856,0.0153,0.0170,8.0488,0.0173,0.0157,6.3249,0.0138,0.0001,0.0156,9777.7604
23,"Electricity, gas, steam and air conditioning supply",3.1720,0.1945,0.0239,90.4456,0.0392,114.3634,662.8629,0.0371,0.4086,0.0000,2.9221,0.0257,282.4148,502.5886,237.2483,5009.0208,7952.4399,5169.2328,25501.1360,1402.9482,857.6223,3408.2053,9238.1898,18.8173,0.7786,3.9845,39042.9882,2327.0631,7599.8725,2306.4090,1381.7426,117.8380,116.9745,36.6919,0.0000,29.8631,3027.0707,1059.2938,0.0000,14188.7005,4.0665,186.2406,83.1697,0.0000,2765.3976,2798.1450,6591.8517,3943.8460,0.4956,5.9953,183.2066,10.5552,12.2145,842.9812,292.7348,10.9388,0.5847,0.6510,308.2720,0.6631,0.6018,242.2439,0.5284,0.0050,0.5975,149979.6168
24,"Water collection, treatment and supply",0.0000,0.0000,0.0000,1.6865,0.0007,2.1324,12.3599,0.0007,0.0076,0.0000,0.0545,0.0005,5.2660,9.3714,4.4238,93.3994,85.3502,90.8140,448.0083,572.7828,350.1421,63.5502,162.2981,0.3509,0.0145,0.0743,4956.9014,43.3910,141.7091,43.0059,25.7643,2.1972,2.1811,0.6842,0.0000,0.5568,56.4435,19.7518,0.0000,1007.2258,0.0758,3.4727,1.5508,0.0000,51.5643,52.1749,122.9133,87.8780,0.0092,0.1118,3.4161,0.1968,0.2278,15.7184,5.4584,0.2040,0.0109,0.0121,5.7481,0.0124,0.0112,4.5169,0.0099,0.0001,0.0111,8557.2060
25,"Sewerage, waste management, remediation activities",0.0000,0.0000,0.0000,10.5793,0.0046,13.3769,77.5338,0.0043,0.0478,0.0000,0.3418,0.0030,33.0335,58.7868,27.7505,585.8955,860.4830,388.7097,1917.6038,3536.6335,2161.9442,398.6512,694.6823,2.2010,0.0911,0.4661,12814.0216,272.1921,888.9425,269.7762,161.6198,13.7833,13.6823,4.2918,0.0000,3.4930,354.0706,123.9036,0.0000,456.9412,0.4757,21.7842,9.7282,0.0000,323.4632,327.2936,771.0362,662.4055,0.0580,0.7013,21.4293,1.2346,1.4287,98.6019,34.2406,1.2795,0.0684,0.0761,36.0580,0.0776,0.0704,28.3348,0.0618,0.0006,0.0699,28485.5198
26,Construction,0.8900,0.0546,0.0067,2.8645,0.0012,3.6221,20.9938,0.0012,0.0129,0.0000,0.0925,0.0008,8.9445,15.9177,7.5140,158.6429,2925.2556,1857.5869,9163.9470,12526.2241,7657.2814,107.9428,3319.7847,0.5960,0.0247,0.1262,17282.5463,73.7014,240.6989,73.0473,43.7618,3.7321,3.7048,1.1621,0.0000,0.9458,95.8717,33.5494,0.0000,8019.2960,0.1288,5.8985,2.6341,0.0000,87.5841,88.6213,208.7734,3610.6224,0.0157,0.1899,5.8024,0.3343,0.3869,26.6984,9.2713,0.3464,0.0185,0.0206,9.7634,0.0210,0.0191,7.6722,0.0167,0.0002,0.0189,67715.2048
27,Wholesale and retail trade and repair of motor vehicles and motorcycles,0.0000,0.0000,0.0000,15.8858,0.0069,20.0867,116.4245,0.0065,0.0718,0.0000,0.5132,0.0045,49.6030,88.2741,41.6700,879.7789,178.7278,71.4924,352.6902,15963.7770,9758.6576,598.6134,127.7676,3.3050,0.1368,0.6998,1854.7547,408.7228,1334.8332,405.0951,242.6877,20.6969,20.5453,6.4445,0.0000,5.2451,531.6713,186.0532,0.0000,1482.2365,0.7142,32.7111,14.6078,0.0000,485.7114,491.4631,1157.7855,243.7885,0.0870,1.0530,32.1782,1.8539,2.1453,148.0603,51.4156,1.9213,0.1027,0.1143,54.1446,0.1165,0.1057,42.5475,0.0928,0.0009,0.1050,37530.0063

In [156]:
for i in range(63): #rows 63 and 64 have 0 tot
    for j in range(1,66):
        invTableNamaIPF.iloc[i, j]/=invTableNamaIPF.iloc[i, 66]

In [157]:
invTableNamaIPF

IND_USE (Labels),sectors,"Products of agriculture, hunting and related services","Products of forestry, logging and related services",Fish and other fishing products; aquaculture products; support services to fishing,Mining and quarrying,"Food, beverages and tobacco products","Textiles, wearing apparel, leather and related products","Wood and of products of wood and cork, except furniture; articles of straw and plaiting materials",Paper and paper products,Printing and recording services,Coke and refined petroleum products,Chemicals and chemical products,Basic pharmaceutical products and pharmaceutical preparations,Rubber and plastic products,Other non-metallic mineral products,Basic metals,"Fabricated metal products, except machinery and equipment","Computer, electronic and optical products",Electrical equipment,Machinery and equipment n.e.c.,"Motor vehicles, trailers and semi-trailers",Other transport equipment,Furniture and other manufactured goods,Repair and installation services of machinery and equipment,"Electricity, gas, steam and air conditioning",Natural water; water treatment and supply services,"Sewerage services; sewage sludge; waste collection, treatment and disposal services; materials recovery services; remediation services and other waste management services",Constructions and construction works,Wholesale and retail trade and repair services of motor vehicles and motorcycles,"Wholesale trade services, except of motor vehicles and motorcycles","Retail trade services, except of motor vehicles and motorcycles",Land transport services and transport services via pipelines,Water transport services,Air transport services,Warehousing and support services for transportation,Postal and courier services,Accommodation and food services,Publishing services,"Motion picture, video and television programme production services, sound recording and music publishing; programming and broadcasting services",Telecommunications services,"Computer programming, consultancy and related services; Information services","Financial services, except insurance and pension funding","Insurance, reinsurance and pension funding services, except compulsory social security",Services auxiliary to financial services and insurance services,Imputed rents of owner-occupied dwellings,Real estate services excluding imputed rents,Legal and accounting services; services of head offices; management consultancy services,Architectural and engineering services; technical testing and analysis services,Scientific research and development services,Advertising and market research services,"Other professional, scientific and technical services and veterinary services",Rental and leasing services,Employment services,"Travel agency, tour operator and other reservation services and related services","Security and investigation services; services to buildings and landscape; office administrative, office support and other business support services",Public administration and defence services; compulsory social security services,Education services,Human health services,Residential care services; social work services without accommodation,"Creative, arts, entertainment, library, archive, museum, other cultural services; gambling and betting services",Sporting services and amusement and recreation services,Services furnished by membership organisations,Repair services of computers and personal and household goods,Other personal services,Services of households as employers; undifferentiated goods and services produced by households for own use,Services provided by extraterritorial organisations and bodies,Totals
0,"Crop and animal production, hunting and related service activities",0.0600,0.0037,0.0005,0.0004,0.0000,0.0005,0.0026,0.0000,0.0000,0.0000,0.0000,0.0000,0.0011,0.0020,0.0009,0.0198,0.0236,0.0496,0.2449,0.1343,0.0821,0.0135,0.0887,0.0001,0.0000,0.0000,0.1290,0.0092,0.0301,0.0091,0.0055,0.0005,0.0005,0.0001,0.0000,0.0001,0.0120,0.0042,0.0000,0.0003,0.0000,0.0007,0.0003,0.0000,0.0109,0.0111,0.0261,0.0145,0.0000,0.0000,0.0007,0.0000,0.0000,0.0033,0.0012,0.0000,0.0000,0.0000,0.0012,0.0000,0.0000,0.0010,0.0000,0.0000,0.0000,87269.6802
1,Forestry and logging,0.0961,0.0059,0.0007,0.0005,0.0000,0.0006,0.0035,0.0000,0.0000,0.0000,0.0000,0.0000,0.0015,0.0027,0.0013,0.0267,0.0493,0.0239,0.1181,0.1267,0.0774,0.0182,0.0428,0.0001,0.0000,0.0000,0.1663,0.0124,0.0405,0.0123,0.0074,0.0006,0.0006,0.0002,0.0000,0.0002,0.0161,0.0056,0.0000,0.0483,0.0000,0.0010,0.0004,0.0000,0.0147,0.0149,0.0351,0.0171,0.0000,0.0000,0.0010,0.0001,0.0001,0.0045,0.0016,0.0001,0.0000,0.0000,0.0016,0.0000,0.0000,0.0013,0.0000,0.0000,0.0000,10474.2172
2,Fishing and aquaculture,0.0000,0.0000,0.0000,0.0002,0.0000,0.0002,0.0012,0.0000,0.0000,0.0000,0.0000,0.0000,0.0005,0.0009,0.0004,0.0090,0.0011,0.0229,0.1130,0.3996,0.2443,0.0061,0.0409,0.0000,0.0000,0.0000,0.0365,0.0042,0.0137,0.0041,0.0025,0.0002,0.0002,0.0001,0.0000,0.0001,0.0054,0.0019,0.0000,0.0023,0.0000,0.0003,0.0001,0.0000,0.0050,0.0050,0.0118,0.0629,0.0000,0.0000,0.0003,0.0000,0.0000,0.0015,0.0005,0.0000,0.0000,0.0000,0.0006,0.0000,0.0000,0.0004,0.0000,0.0000,0.0000,3314.7286
3,Mining and quarrying,0.0000,0.0000,0.0000,0.0001,0.0000,0.0001,0.0006,0.0000,0.0000,0.0000,0.0000,0.0000,0.0003,0.0005,0.0002,0.0048,0.0399,0.0234,0.1152,0.0341,0.0209,0.0033,0.0417,0.0000,0.0000,0.0000,0.2754,0.0022,0.0073,0.0022,0.0013,0.0001,0.0001,0.0000,0.0000,0.0000,0.0029,0.0010,0.0000,0.0694,0.0000,0.0002,0.0001,0.0000,0.0027,0.0027,0.0063,0.3391,0.0000,0.0000,0.0002,0.0000,0.0000,0.0008,0.0003,0.0000,0.0000,0.0000,0.0003,0.0000,0.0000,0.0002,0.0000,0.0000,0.0000,19702.4199
4,Manufacture of food products; beverages and tobacco products,0.0002,0.0000,0.0000,0.0000,0.0000,0.0001,0.0003,0.0000,0.0000,0.0000,0.0000,0.0000,0.0001,0.0003,0.0001,0.0025,0.0374,0.0447,0.2207,0.0700,0.0428,0.0017,0.0799,0.0000,0.0000,0.0000,0.1280,0.0012,0.0038,0.0011,0.0007,0.0001,0.0001,0.0000,0.0000,0.0000,0.0015,0.0005,0.0000,0.1535,0.0000,0.0001,0.0000,0.0000,0.0014,0.0014,0.0033,0.2016,0.0000,0.0000,0.0001,0.0000,0.0000,0.0004,0.0001,0.0000,0.0000,0.0000,0.0002,0.0000,0.0000,0.0001,0.0000,0.0000,0.0000,41624.6102
5,"Manufacture of textiles, wearing apparel, leather and related products",0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0001,0.0000,0.0000,0.0000,0.0000,0.0000,0.0001,0.0001,0.0000,0.0010,0.0418,0.0257,0.1266,0.0242,0.0148,0.0007,0.0459,0.0000,0.0000,0.0000,0.0408,0.0005,0.0015,0.0004,0.0003,0.0000,0.0000,0.0000,0.0000,0.0000,0.0006,0.0002,0.0000,0.1782,0.0000,0.0000,0.0000,0.0000,0.0005,0.0005,0.0013,0.4938,0.0000,0.0000,0.0000,0.0000,0.0000,0.0002,0.0001,0.0000,0.0000,0.0000,0.0001,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,6579.4845
6,"Manufacture of wood and of products of wood and cork, except furniture; manufacture of articles of straw and plaiting materials",0.0146,0.0009,0.0001,0.0002,0.0000,0.0003,0.0018,0.0000,0.0000,0.0000,0.0000,0.0000,0.0008,0.0013,0.0006,0.0133,0.0728,0.0566,0.2794,0.0802,0.0491,0.0091,0.1012,0.0001,0.0000,0.0000,0.1717,0.0062,0.0203,0.0061,0.0037,0.0003,0.0003,0.0001,0.0000,0.0001,0.0081,0.0028,0.0000,0.0331,0.0000,0.0005,0.0002,0.0000,0.0074,0.0075,0.0176,0.0265,0.0000,0.0000,0.0005,0.0000,0.0000,0.0022,0.0008,0.0000,0.0000,0.0000,0.0008,0.0000,0.0000,0.0006,0.0000,0.0000,0.0000,6417.2947
7,Manufacture of paper and paper products,0.0000,0.0000,0.0000,0.0003,0.0000,0.0004,0.0024,0.0000,0.0000,0.0000,0.0000,0.0000,0.0010,0.0018,0.0009,0.0183,0.0856,0.0576,0.2842,0.0033,0.0020,0.0125,0.1029,0.0001,0.0000,0.0000,0.1513,0.0085,0.0278,0.0084,0.0051,0.0004,0.0004,0.0001,0.0000,0.0001,0.0111,0.0039,0.0000,0.0615,0.0000,0.0007,0.0003,0.0000,0.0101,0.0102,0.0241,0.0956,0.0000,0.0000,0.0007,0.0000,0.0000,0.0031,0.0011,0.0000,0.0000,0.0000,0.0011,0.0000,0.0000,0.0009,0.0000,0.0000,0.0000,5143.0639
8,Printing and reproduction of recorded media,0.0000,0.0000,0.0000,0.0002,0.0000,0.0002,0.0011,0.0000,0.0000,0.0000,0.0000,0.0000,0.0005,0.0009,0.0004,0.0086,0.0601,0.0465,0.2296,0.0342,0.0209,0.0059,0.0832,0.0000,0.0000,0.0000,0.0683,0.0040,0.0131,0.0040,0.0024,0.0002,0.0002,0.0001,0.0000,0.0001,0.0052,0.0018,0.0000,0.3497,0.0000,0.0003,0.0001,0.0000,0.0048,0.0048,0.0113,0.0340,0.0000,0.0000,0.0003,0.0000,0.0000,0.0014,0.0005,0.0000,0.0000,0.0000,0.0005,0.0000,0.0000,0.0004,0.0000,0.0000,0.0000,2635.2253
9,Manufacture of coke and refined petroleum products,0.0000,0.0000,0.0000,0.0001,0.0000,0.0001,0.0007,0.0000,0.0000,0.0000,0.0000,0.0000,0.0003,0.0005,0.0002,0.0050,0.0267,0.0311,0.1533,0.0283,0.0173,0.0034,0.0556,0.0000,0.0000,0.0000,0.0758,0.0023,0.0076,0.0023,0.0014,0.0001,0.0001,0.0000,0.0000,0.0000,0.0030,0.0011,0.0000,0.1596,0.0000,0.0002,0.0001,0.0000,0.0028,0.0028,0.0066,0.4095,0.0000,0.0000,0.0002,0.0000,0.0000,0.0008,0.0003,0.0000,0.0000,0.0000,0.0003,0.0000,0.0000,0.0002,0.0000,0.0000,0.0000,10611.8870
10,Manufacture of chemicals and chemical products,0.0000,0.0000,0.0000,0.0001,0.0000,0.0001,0.0005,0.0000,0.0000,0.0000,0.0000,0.0000,0.0002,0.0004,0.0002,0.0039,0.0319,0.0304,0.1499,0.0372,0.0227,0.0027,0.0543,0.0000,0.0000,0.0000,0.0540,0.0018,0.0060,0.0018,0.0011,0.0001,0.0001,0.0000,0.0000,0.0000,0.0024,0.0008,0.0000,0.0951,0.0000,0.0001,0.0001,0.0000,0.0022,0.0022,0.0052,0.4908,0.0000,0.0000,0.0001,0.0000,0.0000,0.0007,0.0002,0.0000,0.0000,0.0000,0.0002,0.0000,0.0000,0.0002,0.0000,0.0000,0.0000,55700.4696
11,Manufacture of basic pharmaceutical products and pharmaceutical preparations,0.0000,0.0000,0.0000,0.0001,0.0000,0.0001,0.0006,0.0000,0.0000,0.0000,0.0000,0.0000,0.0002,0.0004,0.0002,0.0042,0.0129,0.0142,0.0702,0.0119,0.0073,0.0029,0.0254,0.0000,0.0000,0.0000,0.0680,0.0020,0.0064,0.0019,0.0012,0.0001,0.0001,0.0000,0.0000,0.0000,0.0025,0.0009,0.0000,0.0766,0.0000,0.0002,0.0001,0.0000,0.0023,0.0023,0.0055,0.6777,0.0000,0.0000,0.0002,0.0000,0.0000,0.0007,0.0002,0.0000,0.0000,0.0000,0.0003,0.0000,0.0000,0.0002,0.0000,0.0000,0.0000,61026.5211
12,Manufacture of rubber and plastic products,0.0015,0.0001,0.0000,0.0002,0.0000,0.0003,0.0016,0.0000,0.0000,0.0000,0.0000,0.0000,0.0007,0.0012,0.0006,0.0117,0.0684,0.0442,0.2183,0.0349,0.0213,0.0080,0.0791,0.0000,0.0000,0.0000,0.1145,0.0054,0.0178,0.0054,0.0032,0.0003,0.0003,0.0001,0.0000,0.0001,0.0071,0.0025,0.0000,0.0280,0.0000,0.0004,0.0002,0.0000,0.0065,0.0065,0.0154,0.2897,0.0000,0.0000,0.0004,0.0000,0.0000,0.0020,0.0007,0.0000,0.0000,0.0000,0.0007,0.0000,0.0000,0.0006,0.0000,0.0000,0.0000,12496.0561
13,Manufacture of other non-metallic mineral products,0.0000,0.0000,0.0000,0.0003,0.0000,0.0003,0.0019,0.0000,0.0000,0.0000,0.0000,0.0000,0.0008,0.0014,0.0007,0.0140,0.0565,0.0342,0.1689,0.1480,0.0905,0.0095,0.0612,0.0001,0.0000,0.0000,0.1123,0.0065,0.0213,0.0065,0.0039,0.0003,0.0003,0.0001,0.0000,0.0001,0.0085,0.0030,0.0000,0.0537,0.0000,0.0005,0.0002,0.0000,0.0077,0.0078,0.0185,0.1553,0.0000,0.0000,0.0005,0.0000,0.0000,0.0024,0.0008,0.0000,0.0000,0.0000,0.0009,0.0000,0.0000,0.0007,0.0000,0.0000,0.0000,14430.7985
14,Manufacture of basic metals,0.0000,0.0000,0.0000,0.0004,0.0000,0.0005,0.0027,0.0000,0.0000,0.0000,0.0000,0.0000,0.0012,0.0021,0.0010,0.0205,0.0594,0.0463,0.2285,0.0088,0.0054,0.0139,0.0828,0.0001,0.0000,0.0000,0.1318,0.0095,0.0310,0.0094,0.0056,0.0005,0.0005,0.0001,0.0000,0.0001,0.0124,0.0043,0.0000,0.0921,0.0000,0.0008,0.0003,0.0000,0.0113,0.0114,0.0269,0.1707,0.0000,0.0000,0.0007,0.0000,0.0000,0.0034,0.0012,0.0000,0.0000,0.0000,0.0013,0.0000,0.0000,0.0010,0.0000,0.0000,0.0000,12989.4821
15,"Manufacture of fabricated metal products, except machinery and equipment",0.0003,0.0000,0.0000,0.0003,0.0000,0.0004,0.0025,0.0000,0.0000,0.0000,0.0000,0.0000,0.0011,0.0019,0.0009,0.0188,0.1097,0.0456,0.2249,0.0260,0.0159,0.0128,0.0815,0.0001,0.0000,0.0000,0.0968,0.0087,0.0285,0.0086,0.0052,0.0004,0.0004,0.0001,0.0000,0.0001,0.0114,0.0040,0.0000,0.0649,0.0000,0.0007,0.0003,0.0000,0.0104,0.0105,0.0247,0.1743,0.0000,0.0000,0.0007,0.0000,0.0000,0.0032,0.0011,0.0000,0.0000,0.0000,0.0012,0.0000,0.0000,0.0009,0.0000,0.0000,0.0000,28780.0382
16,"Manufacture of computer, electronic and optical products",0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0001,0.0000,0.0000,0.0000,0.0000,0.0000,0.0001,0.0001,0.0001,0.0011,0.0398,0.0063,0.0309,0.0059,0.0036,0.0007,0.0112,0.0000,0.0000,0.0000,0.0183,0.0005,0.0017,0.0005,0.0003,0.0000,0.0000,0.0000,0.0000,0.0000,0.0007,0.0002,0.0000,0.2074,0.0000,0.0000,0.0000,0.0000,0.0006,0.0006,0.0014,0.6673,0.0000,0.0000,0.0000,0.0000,0.0000,0.0002,0.0001,0.0000,0.0000,0.0000,0.0001,0.0000,0.0000,0.0001,0.0000,0.0000,0.0000,26187.3554
17,Manufacture of electrical equipment,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0002,0.0000,0.0000,0.0000,0.0000,0.0000,0.0001,0.0002,0.0001,0.0018,0.0886,0.0143,0.0704,0.0081,0.0049,0.0012,0.0255,0.0000,0.0000,0.0000,0.0226,0.0008,0.0027,0.0008,0.0005,0.0000,0.0000,0.0000,0.0000,0.0000,0.0011,0.0004,0.0000,0.1180,0.0000,0.0001,0.0000,0.0000,0.0010,0.0010,0.0024,0.6325,0.0000,0.0000,0.0001,0.0000,0.0000,0.0003,0.0001,0.0000,0.0000,0.0000,0.0001,0.0000,0.0000,0.0001,0.0000,0.0000,0.0000,17167.4945
18,Manufacture of machinery and equipment n.e.c.,0.0000,0.0000,0.0000,0.0000,0.0000,0.0001,0.0003,0.0000,0.0000,0.0000,0.0000,0.0000,0.0001,0.0002,0.0001,0.0023,0.0283,0.0155,0.0764,0.0178,0.0109,0.0016,0.0277,0.0000,0.0000,0.0000,0.0387,0.0011,0.0035,0.0011,0.0006,0.0001,0.0001,0.0000,0.0000,0.0000,0.0014,0.0005,0.0000,0.1566,0.0000,0.0001,0.0000,0.0000,0.0013,0.0013,0.0030,0.6086,0.0000,0.0000,0.0001,0.0000,0.0000,0.0004,0.0001,0.0000,0.0000,0.0000,0.0001,0.0000,0.0000,0.0001,0.0000,0.0000,0.0000,41000.3190
19,"Manufacture of motor vehicles, trailers and semi-trailers",0.0000,0.0000,0.0000,0.0003,0.0000,0.0003,0.0019,0.0000,0.0000,0.0000,0.0000,0.0000,0.0008,0.0015,0.0007,0.0146,0.0693,0.0254,0.1254,0.0000,0.0000,0.0099,0.0454,0.0001,0.0000,0.0000,0.0269,0.0068,0.0221,0.0067,0.0040,0.0003,0.0003,0.0001,0.0000,0.0001,0.0088,0.0031,0.0000,0.0485,0.0000,0.0005,0.0002,0.0000,0.0081,0.0081,0.0192,0.5347,0.0000,0.0000,0.0005,0.0000,0.0000,0.0025,0.0009,0.0000,0.0000,0.0000,0.0009,0.0000,0.0000,0.0007,0.0000,0.0000,0.0000,43801.1111
20,Manufacture of other transport equipment,0.0000,0.0000,0.0000,0.0002,0.0000,0.0003,0.0015,0.0000,0.0000,0.0000,0.0000,0.0000,0.0007,0.0012,0.0005,0.0115,0.0567,0.0069,0.0340,0.0910,0.0556,0.0079,0.0123,0.0000,0.0000,0.0000,0.0294,0.0054,0.0175,0.0053,0.0032,0.0003,0.0003,0.0001,0.0000,0.0001,0.0070,0.0024,0.0000,0.0360,0.0000,0.0004,0.0002,0.0000,0.0064,0.0064,0.0152,0.5797,0.0000,0.0000,0.0004,0.0000,0.0000,0.0019,0.0007,0.0000,0.0000,0.0000,0.0007,0.0000,0.0000,0.0006,0.0000,0.0000,0.0000,10025.7398
21,Manufacture of furniture; other manufacturing,0.0000,0.0000,0.0000,0.0003,0.0000,0.0004,0.0022,0.0000,0.0000,0.0000,0.0000,0.0000,0.0009,0.0017,0.0008,0.0165,0.0555,0.0237,0.1167,0.0405,0.0248,0.0112,0.0423,0.0001,0.0000,0.0000,0.3711,0.0077,0.0250,0.0076,0.0045,0.0004,0.0004,0.0001,0.0000,0.0001,0.0100,0.0035,0.0000,0.0839,0.0000,0.0006,0.0003,0.0000,0.0091,0.0092,0.0217,0.1010,0.0000,0.0000,0.0006,0.0000,0.0000,0.0028,0.0010,0.0000,0.0000,0.0000,0.0010,0.0000,0.0000,0.0008,0.0000,0.0000,0.0000,11558.7451
22,Repair and installation of machinery and equipment,0.0000,0.0000,0.0000,0.0002,0.0000,0.0003,0.0018,0.0000,0.0000,0.0000,0.0000,0.0000,0.0008,0.0013,0.0006,0.0134,0.0984,0.0160,0.0789,0.0848,0.0518,0.0091,0.0286,0.0001,0.0000,0.0000,0.1039,0.0062,0.0203,0.0062,0.0037,0.0003,0.0003,0.0001,0.0000,0.0001,0.0081,0.0028,0.0000,0.2048,0.0000,0.0005,0.0002,0.0000,0.0074,0.0075,0.0176,0.2189,0.0000,0.0000,0.0005,0.0000,0.0000,0.0023,0.0008,0.0000,0.0000,0.0000,0.0008,0.0000,0.0000,0.0006,0.0000,0.0000,0.0000,9777.7604
23,"Electricity, gas, steam and air conditioning supply",0.0000,0.0000,0.0000,0.0006,0.0000,0.0008,0.0044,0.0000,0.0000,0.0000,0.0000,0.0000,0.0019,0.0034,0.0016,0.0334,0.0530,0.0345,0.1700,0.0094,0.0057,0.0227,0.0616,0.0001,0.0000,0.0000,0.2603,0.0155,0.0507,0.0154,0.0092,0.0008,0.0008,0.0002,0.0000,0.0002,0.0202,0.0071,0.0000,0.0946,0.0000,0.0012,0.0006,0.0000,0.0184,0.0187,0.0440,0.0263,0.0000,0.0000,0.0012,0.0001,0.0001,0.0056,0.0020,0.0001,0.0000,0.0000,0.0021,0.0000,0.0000,0.0016,0.0000,0.0000,0.0000,149979.6168
24,"Water collection, treatment and supply",0.0000,0.0000,0.0000,0.0002,0.0000,0.0002,0.0014,0.0000,0.0000,0.0000,0.0000,0.0000,0.0006,0.0011,0.0005,0.0109,0.0100,0.0106,0.0524,0.0669,0.0409,0.0074,0.0190,0.0000,0.0000,0.0000,0.5793,0.0051,0.0166,0.0050,0.0030,0.0003,0.0003,0.0001,0.0000,0.0001,0.0066,0.0023,0.0000,0.1177,0.0000,0.0004,0.0002,0.0000,0.0060,0.0061,0.0144,0.0103,0.0000,0.0000,0.0004,0.0000,0.0000,0.0018,0.0006,0.0000,0.0000,0.0000,0.0007,0.0000,0.0000,0.0005,0.0000,0.0000,0.0000,8557.2060
25,"Sewerage, waste management, remediation activities",0.0000,0.0000,0.0000,0.0004,0.0000,0.0005,0.0027,0.0000,0.0000,0.0000,0.0000,0.0000,0.0012,0.0021,0.0010,0.0206,0.0302,0.0136,0.0673,0.1242,0.0759,0.0140,0.0244,0.0001,0.0000,0.0000,0.4498,0.0096,0.0312,0.0095,0.0057,0.0005,0.0005,0.0002,0.0000,0.0001,0.0124,0.0043,0.0000,0.0160,0.0000,0.0008,0.0003,0.0000,0.0114,0.0115,0.0271,0.0233,0.0000,0.0000,0.0008,0.0000,0.0001,0.0035,0.0012,0.0000,0.0000,0.0000,0.0013,0.0000,0.0000,0.0010,0.0000,0.0000,0.0000,28485.5198
26,Construction,0.0000,0.0000,0.0000,0.0000,0.0000,0.0001,0.0003,0.0000,0.0000,0.0000,0.0000,0.0000,0.0001,0.0002,0.0001,0.0023,0.0432,0.0274,0.1353,0.1850,0.1131,0.0016,0.0490,0.0000,0.0000,0.0000,0.2552,0.0011,0.0036,0.0011,0.0006,0.0001,0.0001,0.0000,0.0000,0.0000,0.0014,0.0005,0.0000,0.1184,0.0000,0.0001,0.0000,0.0000,0.0013,0.0013,0.0031,0.0533,0.0000,0.0000,0.0001,0.0000,0.0000,0.0004,0.0001,0.0000,0.0000,0.0000,0.0001,0.0000,0.0000,0.0001,0.0000,0.0000,0.0000,67715.2048
27,Wholesale and retail trade and repair of motor vehicles and motorcycles,0.0000,0.0000,0.0000,0.0004,0.0000,0.0005,0.0031,0.0000,0.0000,0.0000,0.0000,0.0000,0.0013,0.0024,0.0011,0.0234,0.0048,0.0019,0.0094,0.4254,0.2600,0.0160,0.0034,0.0001,0.0000,0.0000,0.0494,0.0109,0.0356,0.0108,0.0065,0.0006,0.0005,0.0002,0.0000,0.0001,0.0142,0.0050,0.0000,0.0395,0.0000,0.0009,0.0004,0.0000,0.0129,0.0131,0.0308,0.0065,0.0000,0.0000,0.0009,0.0000,0.0001,0.0039,0.0014,0.0001,0.0000,0.0000,0.0014,0.0000,0.0000,0.0011,0.0000,0.0000,0.0000,37530.0063
28,"Wholesale trade, except of motor vehicles and motorcycles",0.0001,0.0000,0.0000,0.0006,0.0000,0.0007,0.0042,0.0000,0.0000,0.0000,0.0000,0.0000,0.0018,0.0032,0.0015,0.0318,0.0714,0.0228,0.1124,0.0857,0.0524,0.0217,0.0407,0.0001,0.0000,0.0000,0.0982,0.0148,0.0483,0.0147,0.0088,0.0007,0.0007,0.0002,0.0000,0.0002,0.0192,0.0067,0.0000,0.1090,0.0000,0.0012,0.0005,0.0000,0.0176,0.0178,0.0419,0.1361,0.0000,0.0000,0.0012,0.0001,0.0001,0.0054,0.0019,0.0001,0.0000,0.0000,0.0020,0.0000,0.0000,0.0015,0.0000,0.0000,0.0000,143282.1233
29,"Retail trade, except of motor vehicles and motorcycles",0.0000,0.0000,0.0000,0.0006,0.0000,0.0008,0.0044,0.0000,0.0000,0.0000,0.0000,0.0000,0.0019,0.0033,0.0016,0.0331,0.0534,0.0184,0.0909,0.0740,0.0452,0.0226,0.0329,0.0001,0.0000,0.0000,0.1910,0.0154,0.0503,0.0153,0.0091,0.0008,0.0008,0.0002,0.0000,0.0002,0.0200,0.0070,0.0000,0.2051,0.0000,0.0012,0.0006,0.0000,0.0183,0.0185,0.0436,0.0066,0.0000,0.0000,0.0012,0.0001,0.0001,0.0056,0.0019,0.0001,0.0000,0.0000,0.0020,0.0000,0.0000,0.0016,0.0000,0.0000,0.0000,110609.7210
30,Land transport and transport via pipelines,0.0000,0.0000,0.0000,0.0002,0.0000,0.0002,0.0012,0.0000,0.0000,0.0000,0.0000,0.0000,0.0005,0.0009,0.0004,0.0091,0.0071,0.0045,0.0222,0.4475,0.2736,0.0062,0.0080,0.0000,0.0000,0.0000,0.0904,0.0042,0.0139,0.0042,0.0025,0.0002,0.0002,0.0001,0.0000,0.0001,0.0055,0.0019,0.0000,0.0562,0.0000,0.0003,0.0002,0.0000,0.0050,0.0051,0.0120,0.0126,0.0000,0.0000,0.0003,0.0000,0.0000,0.0015,0.0005,0.0000,0.0000,0.0000,0.0006,0.0000,0.0000,0.0004,0.0000,0.0000,0.0000,40704.2519

In [158]:
invTableNamaIPF.iloc[:-1,:-1].shape

(65, 66)

In [159]:
invTableNamaIPF.iloc[:-1,:-1].to_pickle("./invTableNamaIPF.xp")